#!/usr/bin/env php
<?php
/**
 * command line script for Unix/Linux.
 *
 * This is the bootstrap script for running worker on Unix/Linux.
 *
 * @author fukaiyao
 * @link http://www.fankongyuan.com/
 */

require_once(dirname(__FILE__).'/worker.php');
