<?php 

$auth = $_SESSION['auth'];
if (empty($auth)) die('用户未登录！');

global $config;
if (!in_array($auth['id'], $config['manager']) && $city_info['user_id'] != $auth['id']) die('用户权限不够!^_^');

if (!empty($_POST)) die;

?>
<?php require_once('inc/umediter_text.html'); ?> 
<div class="container">
	<div class="row clearfix">
		<ol class="breadcrumb forum-breadcrumb">
			<li><a href="?c=forum"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
			<li class="active"><span class="glyphicon glyphicon-edit"></span> 城市设置</li>
		</ol>
	</div>
</div>
<div class="container">
	<div class="forum-add">
		<div class="row clearfix">
			<div class="col-md-12 column">
				<h3><span class="glyphicon glyphicon-edit"></span> 城市设置</h3>
				<hr class="solid">
				<div class="col-md-11 column">
					<form id="forum_city_edit" class="form-horizontal" action="javascript:do_forum_city_edit()">
						<fieldset>
							<!-- Text input-->
							<div class="form-group">
								<label class="col-md-2 control-label">名称</label>  
								<div class="col-md-7">
									<input name="name" type="text" placeholder="城市名称" class="form-control input-md" required="" value="<?php echo $city_info['name'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">背景图片URL</label>  
								<div class="col-md-7">
									<input name="background_url" type="text" placeholder="背景图片URL" class="form-control input-md" value="<?php echo $city_info['background_url'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">首页图片URL</label>  
								<div class="col-md-7">
									<input name="index_img_url" type="text" placeholder="首页图片URL" class="form-control input-md" value="<?php echo $city_info['index_img_url'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">首页图片连接</label>  
								<div class="col-md-7">
									<input name="index_img_link" type="text" placeholder="首页图片连接" class="form-control input-md" value="<?php echo $city_info['index_img_link'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">功能选择</label>  
								<div class="col-md-7">
									<label class="checkbox-inline"><input name="carousel" type="checkbox" <?php if (1 == $city_info['carousel']) echo 'checked="checked"' ?>> 首页滚动图 </label>
									<label class="checkbox-inline"><input name="g_t" type="checkbox" <?php if (1 == $city_info['g_t']) echo 'checked="checked"' ?>> 游客发布 </label>
								</div>
							</div>
							<?php if(in_array($auth['id'], $config['manager'])) { ?>
							<div class="form-group">
								<label class="col-md-2 control-label">用户 ID</label>  
								<div class="col-md-7">
									<input name="user_id" type="text" placeholder="用户ID" class="form-control input-md" required="" value="<?php echo $city_info['user_id'] ?>">
								</div>
							</div>
							<?php } ?>
							<!-- Text input-->
							<div class="form-group">
								<label class="col-md-2 control-label">顶部广告</label>  
								<div class="col-md-9">
									<textarea class="form-control input-lg" id="top_ads_content" name="top_ads" style="width:105%;height:360px"><?php echo $city_info['top_ads'] ?></textarea>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">公共内容</label>  
								<div class="col-md-9">
									<textarea class="form-control input-lg" id="pub_ads_content" name="pub_ads" style="width:105%;height:360px"><?php echo $city_info['pub_ads'] ?></textarea>
								</div>
							</div>
							<!-- token -->
							<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
							<!-- Button -->
							<div class="form-group">
								<label class="col-md-2 control-label"></label>
								<div class="col-md-2">
									<button class="btn btn-primary btn-block">设置</button>
								</div>
								<div class="col-md-5">
								</div>
							</div>
						</fieldset>
					</form>	


				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

var top_ads_content = UM.getEditor("top_ads_content");  
var pub_ads_content = UM.getEditor("pub_ads_content");  

$(document).ready(function(){
	$('li#forum_manage').addClass('active');
});

</script>
