<?php 

$auth = $_SESSION['auth'];
if (empty($auth)) die('用户未登录！');

global $config;
if (!in_array($auth['id'], $config['manager']) && $city_info['user_id'] != $auth['id']) die('用户权限不够!^_^');

if (!empty($_POST)) die;

$carousel_id = intval($_GET['carousel_id']);

$carousel = dt_query_one("SELECT * FROM forum_carousel WHERE id = $carousel_id");
if (!$carousel) die('获取数据失败！');

?>
<div class="container">
	<div class="row clearfix">
		<ol class="breadcrumb forum-breadcrumb">
			<li><a href="?c=forum"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
			<li><a href="?c=forum&a=forum_carousel_manage"><span class="glyphicon glyphicon-edit"></span> 滚动图管理</a></li>
			<li class="active"><span class="glyphicon glyphicon-edit"></span> 设置图片</li>
		</ol>
	</div>
</div>
<div class="container">
	<div class="forum-add">
		<div class="row clearfix">
			<div class="col-md-12 column">
				<h3><span class="glyphicon glyphicon-edit"></span> 设置图片</h3>
				<hr class="solid">
				<div class="col-md-11 column">
					<form id="forum_carousel_edit" class="form-horizontal" action="javascript:do_forum_carousel_edit()">
						<fieldset>
							<!-- carousel_id -->
							<input type="hidden" name="carousel_id" value="<?php echo $carousel_id ?>"/>
							<!-- Text input-->
							<div class="form-group">
								<label class="col-md-2 control-label">图片URL</label>  
								<div class="col-md-7">
									<input name="img_url" type="text" placeholder="图片URL" class="form-control input-md" required="" value="<?php echo $carousel['img_url'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">链接URL</label>  
								<div class="col-md-7">
									<input name="img_link" type="text" placeholder="链接URL" class="form-control input-md" required="" value="<?php echo $carousel['img_link'] ?>">
								</div>
							</div>
							<!-- token -->
							<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
							<!-- Button -->
							<div class="form-group">
								<label class="col-md-2 control-label"></label>
								<div class="col-md-2">
									<button class="btn btn-primary btn-block">设置</button>
								</div>
								<div class="col-md-5">
								</div>
							</div>
						</fieldset>
					</form>	


				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
		});

</script>
