<?php 

$f_ext = 1;
$cond = "WHERE pay > 0 AND city = $forum_city";
$limit = require_once('inc/order_search_limit.php');

$topic_tops = dt_query("SELECT forum_topic.id, title, user_id, user_name, view_c, reply_c, today, today_up_c, l_r_user_id, l_r_user_name, l_r_at, digest, pay, c_at, forum_topic_ext_$f_ext.* FROM forum_topic INNER JOIN forum_topic_ext_$f_ext ON forum_topic.id = forum_topic_ext_$f_ext.id $cond ORDER BY c_at DESC LIMIT $limit");

?>
<link rel="stylesheet" href="forum/forum_ext/ext_1/topic_list.css">
<div class="container">
	<div class="forum-topic-list-ext-1">
		<div class="row clearfix">
			<?php while($topic_l = mysql_fetch_array($topic_tops)) { ?>
			<?php require('forum_ext/ext_'.$f_ext.'/topic_list_item.phtml') ?>	
			<?php } ?>
		</div>
	</div>
</div>
