<?php
return array (
  'cache_lifetime_channel' => '30',
  'cache_lifetime_index' => '10',
  'cache_lifetime_view' => '72',
  'rewrite_channel' => 'list',
  'rewrite_suffix' => 'html',
  'rewrite_view' => 'view',
  'web_beian' => '',
  'web_caching' => '0',
  'web_close' => '0',
  'web_closecon' => '',
  'web_debug' => '0',
  'web_default_theme' => 'default',
  'web_description' => '',
  'web_gzip_open' => '1',
  'web_keywords' => '',
  'web_name' => '我的网站',
  'web_path_depr' => '-',
  'web_path_suffix' => 'html',
  'web_robot_onnotes' => '1',
  'web_seo_name' => '自豪的使用txtcms',
  'web_tongji' => '',
  'web_url' => 'http://txtcms.cm/',
  'web_url_model' => '1',
  'web_url_route' => 
  array (
    'list' => 'list\\/(\\d+)',
    'list_p' => 'list\\/(\\d+)\\/(\\d+)',
    'show' => 'show\\/(\\d+)',
    'show_p' => 'show\\/(\\d+)\\/(\\d+)',
  ),
  'web_url_route_list' => 'list/{id}',
  'web_url_route_list_p' => 'list/{id}/{page}',
  'web_url_route_on' => '1',
  'web_url_route_show' => 'show/{id}',
  'web_url_route_show_p' => 'show/{id}/{page}',
);
?>