<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="charset" content="utf-8">
    <meta http-equiv="content-language" content="utf-8">
    <meta http-equiv="MSThemeCompatible" content="Yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ERR <?php echo $errStatusCode ?></title>
    <style>
        #err-msg{
            font-size: 14px;
            line-height: 18px;
            font-family: Monospaced,Monaco,Droid Sans Mono,Courier New;
        }
    </style>
</head>
<body>
<div>
    <div id="err-msg"><?php echo $errMsg ?></div>
</div>
</body>
</html>