<?php
//域名后缀列表
return array(
    // 域名,类型,服务商
    array('.ac.cn', 'ccSLD', ''),
    array('.com.cn', 'ccSLD', ''),
    array('.edu.cn', 'ccSLD', ''),
    array('.gov.cn', 'ccSLD', ''),
    array('.mil.cn', 'ccSLD', ''),
    array('.net.cn', 'ccSLD', ''),
    array('.org.cn', 'ccSLD', ''),
    array('.bj.cn', 'ccSLD', ''),
    array('.sh.cn', 'ccSLD', ''),
    array('.tj.cn', 'ccSLD', ''),
    array('.cq.cn', 'ccSLD', ''),
    array('.he.cn', 'ccSLD', ''),
    array('.sx.cn', 'ccSLD', ''),
    array('.nm.cn', 'ccSLD', ''),
    array('.ln.cn', 'ccSLD', ''),
    array('.jl.cn', 'ccSLD', ''),
    array('.hl.cn', 'ccSLD', ''),
    array('.js.cn', 'ccSLD', ''),
    array('.zj.cn', 'ccSLD', ''),
    array('.ah.cn', 'ccSLD', ''),
    array('.fj.cn', 'ccSLD', ''),
    array('.jx.cn', 'ccSLD', ''),
    array('.sd.cn', 'ccSLD', ''),
    array('.ha.cn', 'ccSLD', ''),
    array('.hb.cn', 'ccSLD', ''),
    array('.hn.cn', 'ccSLD', ''),
    array('.gd.cn', 'ccSLD', ''),
    array('.gx.cn', 'ccSLD', ''),
    array('.hi.cn', 'ccSLD', ''),
    array('.sc.cn', 'ccSLD', ''),
    array('.gz.cn', 'ccSLD', ''),
    array('.yn.cn', 'ccSLD', ''),
    array('.xz.cn', 'ccSLD', ''),
    array('.sn.cn', 'ccSLD', ''),
    array('.gs.cn', 'ccSLD', ''),
    array('.qh.cn', 'ccSLD', ''),
    array('.nx.cn', 'ccSLD', ''),
    array('.xj.cn', 'ccSLD', ''),
    array('.tw.cn', 'ccSLD', ''),
    array('.hk.cn', 'ccSLD', ''),
    array('.mo.cn', 'ccSLD', ''),
    array('.com.hk', 'ccSLD', ''),
    array('.org.hk', 'ccSLD', ''),
    array('.net.hk', 'ccSLD', ''),
    array('.idv.hk', 'ccSLD', ''),
    array('.edu.hk', 'ccSLD', ''),
    array('.gov.hk', 'ccSLD', ''),
    array('.公司.香港', 'ccSLD', ''),
    array('.組織.香港', 'ccSLD', ''),
    array('.網絡.香港', 'ccSLD', ''),
    array('.個人.香港', 'ccSLD', ''),
    array('.教育.香港', 'ccSLD', ''),
    array('.政府.香港', 'ccSLD', ''),
    array('.com.mo', 'ccSLD', ''),
    array('.net.mo', 'ccSLD', ''),
    array('.org.mo', 'ccSLD', ''),
    array('.edu.mo', 'ccSLD', ''),
    array('.gov.mo', 'ccSLD', ''),
    array('.com.tw', 'ccSLD', ''),
    array('.org.tw', 'ccSLD', ''),
    array('.net.tw', 'ccSLD', ''),
    array('.idv.tw', 'ccSLD', ''),
    array('.商業.tw', 'ccSLD', ''),
    array('.組織.tw', 'ccSLD', ''),
    array('.網路.tw', 'ccSLD', ''),
    array('.ac', 'country-code', 'Network Information Center (AC Domain Registry) c/o Cable and Wireless (Ascension Island)'),
    array('.academy', 'generic', 'Half Oaks, LLC'),
    array('.accountants', 'generic', 'Knob Town, LLC'),
    array('.active', 'generic', 'The Active Network, Inc'),
    array('.actor', 'generic', 'United TLD Holdco Ltd.'),
    array('.ad', 'country-code', 'Andorra Telecom'),
    array('.ae', 'country-code', 'Telecommunication Regulatory Authority (TRA)'),
    array('.aero', 'sponsored', 'Societe Internationale de Telecommunications Aeronautique (SITA INC USA)'),
    array('.af', 'country-code', 'Ministry of Communications and IT'),
    array('.ag', 'country-code', 'UHSA School of Medicine'),
    array('.agency', 'generic', 'Steel Falls, LLC'),
    array('.ai', 'country-code', 'Government of Anguilla'),
    array('.airforce', 'generic', 'United TLD Holdco Ltd.'),
    array('.al', 'country-code', 'Electronic and Postal Communications Authority - AKEP'),
    array('.allfinanz', 'generic', 'Allfinanz Deutsche Vermögensberatung Aktiengesellschaft'),
    array('.alsace', 'generic', 'REGION D ALSACE'),
    array('.am', 'country-code', 'Internet Society'),
    array('.an', 'country-code', 'University of Curacao'),
    array('.ao', 'country-code', 'Faculdade de Engenharia da Universidade Agostinho Neto'),
    array('.aq', 'country-code', 'Antarctica Network Information Centre Limited'),
    array('.ar', 'country-code', 'Presidencia de la Nación – Secretaría Legal y Técnica'),
    array('.archi', 'generic', 'STARTING DOT LIMITED'),
    array('.army', 'generic', 'United TLD Holdco Ltd.'),
    array('.arpa', 'infrastructure', 'Internet Architecture Board (IAB)'),
    array('.as', 'country-code', 'AS Domain Registry'),
    array('.asia', 'sponsored', 'DotAsia Organisation Ltd.'),
    array('.associates', 'generic', 'Baxter Hill, LLC'),
    array('.at', 'country-code', 'nic.at GmbH'),
    array('.attorney', 'generic', 'United TLD Holdco, Ltd'),
    array('.au', 'country-code', '.au Domain Administration (auDA)'),
    array('.auction', 'generic', 'United TLD HoldCo, Ltd.'),
    array('.audio', 'generic', 'Uniregistry, Corp.'),
    array('.autos', 'generic', 'DERAutos, LLC'),
    array('.aw', 'country-code', 'SETAR'),
    array('.ax', 'country-code', 'Ålands landskapsregering'),
    array('.axa', 'generic', 'AXA SA'),
    array('.az', 'country-code', 'IntraNS'),
    array('.ba', 'country-code', 'Universtiy Telinformatic Centre (UTIC)'),
    array('.bar', 'generic', 'Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable'),
    array('.bargains', 'generic', 'Half Hallow, LLC'),
    array('.bayern', 'generic', 'Bayern Connect GmbH'),
    array('.bb', 'country-code', 'Government of Barbados Ministry of Economic Affairs and Development Telecommunications Unit'),
    array('.bd', 'country-code', 'Ministry of Post & Telecommunications Bangladesh Secretariat'),
    array('.be', 'country-code', 'DNS Belgium vzw/asbl'),
    array('.beer', 'generic', 'Top Level Domain Holdings Limited'),
    array('.berlin', 'generic', 'dotBERLIN GmbH & Co. KG'),
    array('.best', 'generic', 'BestTLD Pty Ltd'),
    array('.bf', 'country-code', 'ARCE-AutoritÈ de RÈgulation des Communications Electroniques'),
    array('.bg', 'country-code', 'Register.BG'),
    array('.bh', 'country-code', 'Telecommunications Regulatory Authority (TRA)'),
    array('.bi', 'country-code', 'Centre National de l\'Informatique'),
    array('.bid', 'generic', 'dot Bid Limited'),
    array('.bike', 'generic', 'Grand Hollow, LLC'),
    array('.bio', 'generic', 'STARTING DOT LIMITED'),
    array('.biz', 'generic-restricted', 'NeuStar, Inc.'),
    array('.bj', 'country-code', 'Benin Telecoms S.A.'),
    array('.bl', 'country-code', 'Not assigned'),
    array('.black', 'generic', 'Afilias Limited'),
    array('.blackfriday', 'generic', 'Uniregistry, Corp.'),
    array('.blue', 'generic', 'Afilias Limited'),
    array('.bm', 'country-code', 'Registry General Ministry of Labour and Immigration'),
    array('.bmw', 'generic', 'Bayerische Motoren Werke Aktiengesellschaft'),
    array('.bn', 'country-code', 'Telekom Brunei Berhad'),
    array('.bnpparibas', 'generic', 'BNP Paribas'),
    array('.bo', 'country-code', 'Agencia para el Desarrollo de la Información de la Sociedad en Bolivia'),
    array('.boo', 'generic', 'Charleston Road Registry Inc.'),
    array('.boutique', 'generic', 'Over Galley, LLC'),
    array('.bq', 'country-code', 'Not assigned'),
    array('.br', 'country-code', 'Comite Gestor da Internet no Brasil'),
    array('.brussels', 'generic', 'DNS.be vzw'),
    array('.bs', 'country-code', 'The College of the Bahamas'),
    array('.bt', 'country-code', 'Ministry of Information and Communications'),
    array('.budapest', 'generic', 'Top Level Domain Holdings Limited'),
    array('.build', 'generic', 'Plan Bee LLC'),
    array('.builders', 'generic', 'Atomic Madison, LLC'),
    array('.business', 'generic', 'Spring Cross, LLC'),
    array('.buzz', 'generic', 'DOTSTRATEGY CO.'),
    array('.bv', 'country-code', 'UNINETT Norid A/S'),
    array('.bw', 'country-code', 'Botswana Communications Regulatory Authority (BOCRA)'),
    array('.by', 'country-code', 'Reliable Software Inc.'),
    array('.bz', 'country-code', 'University of Belize'),
    array('.bzh', 'generic', 'Association www.bzh'),
    array('.ca', 'country-code', 'Canadian Internet Registration Authority (CIRA) Autorite Canadienne pour les Enregistrements Internet (ACEI)'),
    array('.cab', 'generic', 'Half Sunset, LLC'),
    array('.cal', 'generic', 'Charleston Road Registry Inc.'),
    array('.camera', 'generic', 'Atomic Maple, LLC'),
    array('.camp', 'generic', 'Delta Dynamite, LLC'),
    array('.cancerresearch', 'generic', 'Australian Cancer Research Foundation'),
    array('.capetown', 'generic', 'ZA Central Registry NPC trading as ZA Central Registry'),
    array('.capital', 'generic', 'Delta Mill, LLC'),
    array('.caravan', 'generic', 'Caravan International, Inc.'),
    array('.cards', 'generic', 'Foggy Hollow, LLC'),
    array('.care', 'generic', 'Goose Cross, LLC'),
    array('.career', 'generic', 'dotCareer LLC'),
    array('.careers', 'generic', 'Wild Corner, LLC'),
    array('.casa', 'generic', 'Top Level Domain Holdings Limited'),
    array('.cash', 'generic', 'Delta Lake, LLC'),
    array('.cat', 'sponsored', 'Fundacio puntCAT'),
    array('.catering', 'generic', 'New Falls. LLC'),
    array('.cc', 'country-code', 'eNIC Cocos (Keeling) Islands Pty. Ltd. d/b/a Island Internet Services'),
    array('.cd', 'country-code', 'Office Congolais des Postes et Télécommunications - OCPT'),
    array('.center', 'generic', 'Tin Mill, LLC'),
    array('.ceo', 'generic', 'CEOTLD Pty Ltd'),
    array('.cern', 'generic', 'European Organization for Nuclear Research ("CERN")'),
    array('.cf', 'country-code', 'Societe Centrafricaine de Telecommunications (SOCATEL)'),
    array('.cg', 'country-code', 'ONPT Congo and Interpoint Switzerland'),
    array('.ch', 'country-code', 'SWITCH The Swiss Education & Research Network'),
    array('.channel', 'generic', 'Charleston Road Registry Inc.'),
    array('.cheap', 'generic', 'Sand Cover, LLC'),
    array('.christmas', 'generic', 'Uniregistry, Corp.'),
    array('.chrome', 'generic', 'Charleston Road Registry Inc.'),
    array('.church', 'generic', 'Holly Fileds, LLC'),
    array('.ci', 'country-code', 'INP-HB Institut National Polytechnique Felix Houphouet Boigny'),
    array('.citic', 'generic', 'CITIC Group Corporation'),
    array('.city', 'generic', 'Snow Sky, LLC'),
    array('.ck', 'country-code', 'Telecom Cook Islands Ltd.'),
    array('.cl', 'country-code', 'NIC Chile (University of Chile)'),
    array('.claims', 'generic', 'Black Corner, LLC'),
    array('.cleaning', 'generic', 'Fox Shadow, LLC'),
    array('.click', 'generic', 'Uniregistry, Corp.'),
    array('.clinic', 'generic', 'Goose Park, LLC'),
    array('.clothing', 'generic', 'Steel Lake, LLC'),
    array('.club', 'generic', '.CLUB DOMAINS, LLC'),
    array('.cm', 'country-code', 'Cameroon Telecommunications (CAMTEL)'),
    array('.cn', 'country-code', 'Computer Network Information Center, Chinese Academy of Sciences'),
    array('.co', 'country-code', '.CO Internet S.A.S.'),
    array('.codes', 'generic', 'Puff Willow, LLC'),
    array('.coffee', 'generic', 'Trixy Cover, LLC'),
    array('.college', 'generic', 'XYZ.COM LLC'),
    array('.cologne', 'generic', 'NetCologne Gesellschaft für Telekommunikation mbH'),
    array('.com', 'generic', 'VeriSign Global Registry Services'),
    array('.community', 'generic', 'Fox Orchard, LLC'),
    array('.company', 'generic', 'Silver Avenue, LLC'),
    array('.computer', 'generic', 'Pine Mill, LLC'),
    array('.condos', 'generic', 'Pine House, LLC'),
    array('.construction', 'generic', 'Fox Dynamite, LLC'),
    array('.consulting', 'generic', 'United TLD Holdco, LTD.'),
    array('.contractors', 'generic', 'Magic Woods, LLC'),
    array('.cooking', 'generic', 'Top Level Domain Holdings Limited'),
    array('.cool', 'generic', 'Koko Lake, LLC'),
    array('.coop', 'sponsored', 'DotCooperation LLC'),
    array('.country', 'generic', 'Top Level Domain Holdings Limited'),
    array('.cr', 'country-code', 'National Academy of Sciences Academia Nacional de Ciencias'),
    array('.credit', 'generic', 'Snow Shadow, LLC'),
    array('.creditcard', 'generic', 'Binky Frostbite, LLC'),
    array('.cruises', 'generic', 'Spring Way, LLC'),
    array('.cu', 'country-code', 'CENIAInternet Industria y San Jose Capitolio Nacional'),
    array('.cuisinella', 'generic', 'SALM S.A.S.'),
    array('.cv', 'country-code', 'Agência Nacional das Comunicações (ANAC)'),
    array('.cw', 'country-code', 'University of Curacao'),
    array('.cx', 'country-code', 'Christmas Island Internet Administration Limited'),
    array('.cy', 'country-code', 'University of Cyprus'),
    array('.cymru', 'generic', 'Nominet UK'),
    array('.cz', 'country-code', 'CZ.NIC, z.s.p.o'),
    array('.dad', 'generic', 'Charleston Road Registry Inc.'),
    array('.dance', 'generic', 'United TLD Holdco Ltd.'),
    array('.dating', 'generic', 'Pine Fest, LLC'),
    array('.day', 'generic', 'Charleston Road Registry Inc.'),
    array('.de', 'country-code', 'DENIC eG'),
    array('.deals', 'generic', 'Sand Sunset, LLC'),
    array('.degree', 'generic', 'United TLD Holdco, Ltd'),
    array('.democrat', 'generic', 'United TLD Holdco Ltd.'),
    array('.dental', 'generic', 'Tin Birch, LLC'),
    array('.dentist', 'generic', 'United TLD Holdco, Ltd'),
    array('.desi', 'generic', 'Desi Networks LLC'),
    array('.diamonds', 'generic', 'John Edge, LLC'),
    array('.diet', 'generic', 'Uniregistry, Corp.'),
    array('.digital', 'generic', 'Dash Park, LLC'),
    array('.direct', 'generic', 'Half Trail, LLC'),
    array('.directory', 'generic', 'Extra Madison, LLC'),
    array('.discount', 'generic', 'Holly Hill, LLC'),
    array('.dj', 'country-code', 'Djibouti Telecom S.A'),
    array('.dk', 'country-code', 'Dansk Internet Forum'),
    array('.dm', 'country-code', 'DotDM Corporation'),
    array('.dnp', 'generic', 'Dai Nippon Printing Co., Ltd.'),
    array('.do', 'country-code', 'Pontificia Universidad Catolica Madre y Maestra Recinto Santo Tomas de Aquino'),
    array('.domains', 'generic', 'Sugar Cross, LLC'),
    array('.durban', 'generic', 'ZA Central Registry NPC trading as ZA Central Registry'),
    array('.dvag', 'generic', 'Deutsche Vermögensberatung Aktiengesellschaft DVAG'),
    array('.dz', 'country-code', 'CERIST'),
    array('.eat', 'generic', 'Charleston Road Registry Inc.'),
    array('.ec', 'country-code', 'NIC.EC (NICEC) S.A.'),
    array('.edu', 'sponsored', 'EDUCAUSE'),
    array('.education', 'generic', 'Brice Way, LLC'),
    array('.ee', 'country-code', 'Eesti Interneti Sihtasutus (EIS)'),
    array('.eg', 'country-code', 'Egyptian Universities Network (EUN) Supreme Council of Universities'),
    array('.eh', 'country-code', 'Not assigned'),
    array('.email', 'generic', 'Spring Madison, LLC'),
    array('.engineer', 'generic', 'United TLD Holdco Ltd.'),
    array('.engineering', 'generic', 'Romeo Canyon'),
    array('.enterprises', 'generic', 'Snow Oaks, LLC'),
    array('.equipment', 'generic', 'Corn Station, LLC'),
    array('.er', 'country-code', 'Eritrea Telecommunication Services Corporation (EriTel)'),
    array('.es', 'country-code', 'Red.es'),
    array('.esq', 'generic', 'Charleston Road Registry Inc.'),
    array('.estate', 'generic', 'Trixy Park, LLC'),
    array('.et', 'country-code', 'Ethio telecom'),
    array('.eu', 'country-code', 'EURid vzw/asbl'),
    array('.eus', 'generic', 'Puntueus Fundazioa'),
    array('.events', 'generic', 'Pioneer Maple, LLC'),
    array('.exchange', 'generic', 'Spring Falls, LLC'),
    array('.expert', 'generic', 'Magic Pass, LLC'),
    array('.exposed', 'generic', 'Victor Beach, LLC'),
    array('.fail', 'generic', 'Atomic Pipe, LLC'),
    array('.farm', 'generic', 'Just Maple, LLC'),
    array('.feedback', 'generic', 'Top Level Spectrum, Inc.'),
    array('.fi', 'country-code', 'Finnish Communications Regulatory Authority'),
    array('.finance', 'generic', 'Cotton Cypress, LLC'),
    array('.financial', 'generic', 'Just Cover, LLC'),
    array('.fish', 'generic', 'Fox Woods, LLC'),
    array('.fishing', 'generic', 'Top Level Domain Holdings Limited'),
    array('.fitness', 'generic', 'Brice Orchard, LLC'),
    array('.fj', 'country-code', 'The University of the South Pacific IT Services'),
    array('.fk', 'country-code', 'Falkland Islands Government'),
    array('.flights', 'generic', 'Fox Station, LLC'),
    array('.florist', 'generic', 'Half Cypress, LLC'),
    array('.fly', 'generic', 'Charleston Road Registry Inc.'),
    array('.fm', 'country-code', 'FSM Telecommunications Corporation'),
    array('.fo', 'country-code', 'FO Council'),
    array('.foo', 'generic', 'Charleston Road Registry Inc.'),
    array('.forsale', 'generic', 'United TLD Holdco, LLC'),
    array('.foundation', 'generic', 'John Dale, LLC'),
    array('.fr', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.frl', 'generic', 'FRLregistry B.V.'),
    array('.frogans', 'generic', 'OP3FT'),
    array('.fund', 'generic', 'John Castle, LLC'),
    array('.furniture', 'generic', 'Lone Fields, LLC'),
    array('.futbol', 'generic', 'United TLD Holdco, Ltd.'),
    array('.ga', 'country-code', 'Agence Nationale des Infrastructures Numériques et des Fréquences (ANINF)'),
    array('.gal', 'generic', 'Asociación puntoGAL'),
    array('.gallery', 'generic', 'Sugar House, LLC'),
    array('.gb', 'country-code', 'Reserved Domain - IANA'),
    array('.gbiz', 'generic', 'Charleston Road Registry Inc.'),
    array('.gd', 'country-code', 'The National Telecommunications Regulatory Commission (NTRC)'),
    array('.ge', 'country-code', 'Caucasus Online'),
    array('.gent', 'generic', 'COMBELL GROUP NV/SA'),
    array('.gf', 'country-code', 'Net Plus'),
    array('.gg', 'country-code', 'Island Networks Ltd.'),
    array('.gh', 'country-code', 'Network Computer Systems Limited'),
    array('.gi', 'country-code', 'Sapphire Networks'),
    array('.gift', 'generic', 'Uniregistry, Corp.'),
    array('.gifts', 'generic', 'Goose Sky, LLC'),
    array('.gives', 'generic', 'United TLD Holdco Ltd.'),
    array('.gl', 'country-code', 'TELE Greenland A/S'),
    array('.glass', 'generic', 'Black Cover, LLC'),
    array('.gle', 'generic', 'Charleston Road Registry Inc.'),
    array('.global', 'generic', 'Dot GLOBAL AS'),
    array('.globo', 'generic', 'Globo Comunicação e Participações S.A'),
    array('.gm', 'country-code', 'GM-NIC'),
    array('.gmail', 'generic', 'Charleston Road Registry Inc.'),
    array('.gmo', 'generic', 'GMO Internet, Inc.'),
    array('.gmx', 'generic', '1&1 Mail & Media GmbH'),
    array('.gn', 'country-code', 'Centre National des Sciences Halieutiques de Boussoura'),
    array('.google', 'generic', 'Charleston Road Registry Inc.'),
    array('.gop', 'generic', 'Republican State Leadership Committee, Inc.'),
    array('.gov', 'sponsored', 'General Services Administration Attn: QTDC, 2E08 (.gov Domain Registration)'),
    array('.gp', 'country-code', 'Networking Technologies Group'),
    array('.gq', 'country-code', 'GETESA'),
    array('.gr', 'country-code', 'ICS-FORTH GR'),
    array('.graphics', 'generic', 'Over Madison, LLC'),
    array('.gratis', 'generic', 'Pioneer Tigers, LLC'),
    array('.green', 'generic', 'Afilias Limited'),
    array('.gripe', 'generic', 'Corn Sunset, LLC'),
    array('.gs', 'country-code', 'Government of South Georgia and South Sandwich Islands (GSGSSI)'),
    array('.gt', 'country-code', 'Universidad del Valle de Guatemala'),
    array('.gu', 'country-code', 'University of Guam Computer Center'),
    array('.guide', 'generic', 'Snow Moon, LLC'),
    array('.guitars', 'generic', 'Uniregistry, Corp.'),
    array('.guru', 'generic', 'Pioneer Cypress, LLC'),
    array('.gw', 'country-code', 'Autoridade Reguladora Nacional - Tecnologias de Informação e Comunicação da Guiné-Bissau'),
    array('.gy', 'country-code', 'University of Guyana'),
    array('.hamburg', 'generic', 'Hamburg Top-Level-Domain GmbH'),
    array('.haus', 'generic', 'United TLD Holdco, LTD.'),
    array('.healthcare', 'generic', 'Silver Glen, LLC'),
    array('.help', 'generic', 'Uniregistry, Corp.'),
    array('.here', 'generic', 'Charleston Road Registry Inc.'),
    array('.hiphop', 'generic', 'Uniregistry, Corp.'),
    array('.hiv', 'generic', 'dotHIV gemeinnuetziger e.V.'),
    array('.hk', 'country-code', 'Hong Kong Internet Registration Corporation Ltd.'),
    array('.hm', 'country-code', 'HM Domain Registry'),
    array('.hn', 'country-code', 'Red de Desarrollo Sostenible Honduras'),
    array('.holdings', 'generic', 'John Madison, LLC'),
    array('.holiday', 'generic', 'Goose Woods, LLC'),
    array('.homes', 'generic', 'DERHomes, LLC'),
    array('.horse', 'generic', 'Top Level Domain Holdings Limited'),
    array('.host', 'generic', 'DotHost Inc.'),
    array('.hosting', 'generic', 'Uniregistry, Corp.'),
    array('.house', 'generic', 'Sugar Park, LLC'),
    array('.how', 'generic', 'Charleston Road Registry Inc.'),
    array('.hr', 'country-code', 'CARNet - Croatian Academic and Research Network'),
    array('.ht', 'country-code', 'Consortium FDS/RDDH'),
    array('.hu', 'country-code', 'Council of Hungarian Internet Providers (CHIP)'),
    array('.ibm', 'generic', 'International Business Machines Corporation'),
    array('.id', 'country-code', 'Perkumpulan Pengelola Nama Domain Internet Indonesia (PANDI)'),
    array('.ie', 'country-code', 'University College Dublin Computing Services Computer Centre'),
    array('.il', 'country-code', 'Internet Society of Israel'),
    array('.im', 'country-code', 'Isle of Man Government'),
    array('.immo', 'generic', 'Auburn Bloom, LLC'),
    array('.immobilien', 'generic', 'United TLD Holdco Ltd.'),
    array('.in', 'country-code', 'National Internet Exchange of India'),
    array('.industries', 'generic', 'Outer House, LLC'),
    array('.info', 'generic', 'Afilias Limited'),
    array('.ing', 'generic', 'Charleston Road Registry Inc.'),
    array('.ink', 'generic', 'Top Level Design, LLC'),
    array('.institute', 'generic', 'Outer Maple, LLC'),
    array('.insure', 'generic', 'Pioneer Willow, LLC'),
    array('.int', 'sponsored', 'Internet Assigned Numbers Authority'),
    array('.international', 'generic', 'Wild Way, LLC'),
    array('.investments', 'generic', 'Holly Glen, LLC'),
    array('.io', 'country-code', 'IO Top Level Domain Registry Cable and Wireless'),
    array('.iq', 'country-code', 'Communications and Media Commission (CMC)'),
    array('.ir', 'country-code', 'Institute for Research in Fundamental Sciences'),
    array('.is', 'country-code', 'ISNIC - Internet Iceland ltd.'),
    array('.it', 'country-code', 'IIT - CNR'),
    array('.je', 'country-code', 'Island Networks (Jersey) Ltd.'),
    array('.jetzt', 'generic', 'New TLD Company AB'),
    array('.jm', 'country-code', 'University of West Indies'),
    array('.jo', 'country-code', 'National Information Technology Center (NITC)'),
    array('.jobs', 'sponsored', 'Employ Media LLC'),
    array('.joburg', 'generic', 'ZA Central Registry NPC trading as ZA Central Registry'),
    array('.jp', 'country-code', 'Japan Registry Services Co., Ltd.'),
    array('.juegos', 'generic', 'Uniregistry, Corp.'),
    array('.kaufen', 'generic', 'United TLD Holdco Ltd.'),
    array('.ke', 'country-code', 'Kenya Network Information Center (KeNIC)'),
    array('.kg', 'country-code', 'AsiaInfo Telecommunication Enterprise'),
    array('.kh', 'country-code', 'Ministry of Post and Telecommunications'),
    array('.ki', 'country-code', 'Ministry of Communications, Transport, and Tourism Development'),
    array('.kim', 'generic', 'Afilias Limited'),
    array('.kitchen', 'generic', 'Just Goodbye, LLC'),
    array('.kiwi', 'generic', 'DOT KIWI LIMITED'),
    array('.km', 'country-code', 'Comores Telecom'),
    array('.kn', 'country-code', 'Ministry of Finance, Sustainable Development Information & Technology'),
    array('.koeln', 'generic', 'NetCologne Gesellschaft für Telekommunikation mbH'),
    array('.kp', 'country-code', 'Star Joint Venture Company'),
    array('.kr', 'country-code', 'Korea Internet & Security Agency (KISA)'),
    array('.krd', 'generic', 'KRG Department of Information Technology'),
    array('.kred', 'generic', 'KredTLD Pty Ltd'),
    array('.kw', 'country-code', 'Ministry of Communications'),
    array('.ky', 'country-code', 'The Information and Communications Technology Authority'),
    array('.kz', 'country-code', 'Association of IT Companies of Kazakhstan'),
    array('.la', 'country-code', 'Lao National Internet Committee (LANIC), Ministry of Posts and Telecommunications'),
    array('.lacaixa', 'generic', 'CAIXA D\'ESTALVIS I PENSIONS DE BARCELONA'),
    array('.land', 'generic', 'Pine Moon, LLC'),
    array('.lawyer', 'generic', 'United TLD Holdco, Ltd'),
    array('.lb', 'country-code', 'American University of Beirut Computing and Networking Services'),
    array('.lc', 'country-code', 'University of Puerto Rico'),
    array('.lease', 'generic', 'Victor Trail, LLC'),
    array('.lgbt', 'generic', 'Afilias Limited'),
    array('.li', 'country-code', 'Universitaet Liechtenstein'),
    array('.life', 'generic', 'Trixy Oaks, LLC'),
    array('.lighting', 'generic', 'John McCook, LLC'),
    array('.limited', 'generic', 'Big Fest, LLC'),
    array('.limo', 'generic', 'Hidden Frostbite, LLC'),
    array('.link', 'generic', 'Uniregistry, Corp.'),
    array('.lk', 'country-code', 'Council for Information Technology LK Domain Registrar'),
    array('.loans', 'generic', 'June Woods, LLC'),
    array('.london', 'generic', 'Dot London Domains Limited'),
    array('.lotto', 'generic', 'Afilias Limited'),
    array('.lr', 'country-code', 'Data Technology Solutions, Inc.'),
    array('.ls', 'country-code', 'National University of Lesotho'),
    array('.lt', 'country-code', 'Kaunas University of Technology'),
    array('.ltda', 'generic', 'InterNetX Corp.'),
    array('.lu', 'country-code', 'RESTENA'),
    array('.luxe', 'generic', 'Top Level Domain Holdings Limited'),
    array('.luxury', 'generic', 'Luxury Partners LLC'),
    array('.lv', 'country-code', 'University of Latvia Institute of Mathematics and Computer Science Department of Network Solutions (DNS)'),
    array('.ly', 'country-code', 'General Post and Telecommunication Company'),
    array('.ma', 'country-code', 'Agence Nationale de Réglementation des Télécommunications (ANRT)'),
    array('.maison', 'generic', 'Victor Frostbite, LLC'),
    array('.management', 'generic', 'John Goodbye, LLC'),
    array('.mango', 'generic', 'PUNTO FA S.L.'),
    array('.market', 'generic', 'Unitied TLD Holdco, Ltd'),
    array('.marketing', 'generic', 'Fern Pass, LLC'),
    array('.mc', 'country-code', 'Gouvernement de Monaco Direction des Communications Electroniques'),
    array('.md', 'country-code', 'MoldData S.E.'),
    array('.me', 'country-code', 'Government of Montenegro'),
    array('.media', 'generic', 'Grand Glen, LLC'),
    array('.meet', 'generic', 'Afilias Limited'),
    array('.melbourne', 'generic', 'The Crown in right of the State of Victoria, represented by its Department of State Development, Business and Innovation'),
    array('.meme', 'generic', 'Charleston Road Registry Inc.'),
    array('.menu', 'generic', 'Wedding TLD2, LLC'),
    array('.mf', 'country-code', 'Not assigned'),
    array('.mg', 'country-code', 'NIC-MG (Network Information Center Madagascar)'),
    array('.mh', 'country-code', 'Office of the Cabinet'),
    array('.miami', 'generic', 'Top Level Domain Holdings Limited'),
    array('.mil', 'sponsored', 'DoD Network Information Center'),
    array('.mini', 'generic', 'Bayerische Motoren Werke Aktiengesellschaft'),
    array('.mk', 'country-code', 'Ministry of Foreign Affairs'),
    array('.ml', 'country-code', 'Agence des Technologies de l’Information et de la Communication'),
    array('.mm', 'country-code', 'Ministry of Communications, Posts & Telegraphs'),
    array('.mn', 'country-code', 'Datacom Co., Ltd.'),
    array('.mo', 'country-code', 'Bureau of Telecommunications Regulation (DSRT)'),
    array('.mobi', 'sponsored', 'Afilias Technologies Limited dba dotMobi'),
    array('.moda', 'generic', 'United TLD Holdco Ltd.'),
    array('.moe', 'generic', 'Interlink Co., Ltd.'),
    array('.monash', 'generic', 'Monash University'),
    array('.mortgage', 'generic', 'United TLD Holdco, Ltd'),
    array('.moscow', 'generic', 'Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)'),
    array('.motorcycles', 'generic', 'DERMotorcycles, LLC'),
    array('.mov', 'generic', 'Charleston Road Registry Inc.'),
    array('.mp', 'country-code', 'Saipan Datacom, Inc.'),
    array('.mq', 'country-code', 'MEDIASERV'),
    array('.mr', 'country-code', 'University of Nouakchott'),
    array('.ms', 'country-code', 'MNI Networks Ltd.'),
    array('.mt', 'country-code', 'NIC (Malta)'),
    array('.mu', 'country-code', 'Internet Direct Ltd'),
    array('.museum', 'sponsored', 'Museum Domain Management Association'),
    array('.mv', 'country-code', 'Dhiraagu Pvt. Ltd. (DHIVEHINET)'),
    array('.mw', 'country-code', 'Malawi Sustainable Development Network Programme (Malawi SDNP)'),
    array('.mx', 'country-code', 'NIC-Mexico ITESM - Campus Monterrey'),
    array('.my', 'country-code', 'MYNIC Berhad'),
    array('.mz', 'country-code', 'Centro de Informatica de Universidade Eduardo Mondlane'),
    array('.na', 'country-code', 'Namibian Network Information Center'),
    array('.nagoya', 'generic', 'GMO Registry, Inc.'),
    array('.name', 'generic-restricted', 'VeriSign Information Services, Inc.'),
    array('.navy', 'generic', 'United TLD Holdco Ltd.'),
    array('.nc', 'country-code', 'Office des Postes et Telecommunications'),
    array('.ne', 'country-code', 'SONITEL'),
    array('.net', 'generic', 'VeriSign Global Registry Services'),
    array('.network', 'generic', 'Trixy Manor, LLC'),
    array('.neustar', 'generic', 'NeuStar, Inc.'),
    array('.new', 'generic', 'Charleston Road Registry Inc.'),
    array('.nexus', 'generic', 'Charleston Road Registry Inc.'),
    array('.nf', 'country-code', 'Norfolk Island Data Services'),
    array('.ng', 'country-code', 'Nigeria Internet Registration Association'),
    array('.ngo', 'generic', 'Public Interest Registry'),
    array('.nhk', 'generic', 'Japan Broadcasting Corporation (NHK)'),
    array('.ni', 'country-code', 'Universidad Nacional del Ingernieria Centro de Computo'),
    array('.ninja', 'generic', 'United TLD Holdco Ltd.'),
    array('.nl', 'country-code', 'SIDN (Stichting Internet Domeinregistratie Nederland)'),
    array('.no', 'country-code', 'UNINETT Norid A/S'),
    array('.np', 'country-code', 'Mercantile Communications Pvt. Ltd.'),
    array('.nr', 'country-code', 'CENPAC NET'),
    array('.nra', 'generic', 'NRA Holdings Company, INC.'),
    array('.nrw', 'generic', 'Minds + Machines GmbH'),
    array('.nu', 'country-code', 'The IUSN Foundation'),
    array('.nyc', 'generic', 'The City of New York by and through the New York City Department of Information Technology & Telecommunications'),
    array('.nz', 'country-code', 'InternetNZ'),
    array('.okinawa', 'generic', 'BusinessRalliart inc.'),
    array('.om', 'country-code', 'Telecommunications Regulatory Authority (TRA)'),
    array('.ong', 'generic', 'Public Interest Registry'),
    array('.onl', 'generic', 'I-REGISTRY Ltd., Niederlassung Deutschland'),
    array('.ooo', 'generic', 'INFIBEAM INCORPORATION LIMITED'),
    array('.org', 'generic', 'Public Interest Registry (PIR)'),
    array('.organic', 'generic', 'Afilias Limited'),
    array('.otsuka', 'generic', 'Otsuka Holdings Co., Ltd.'),
    array('.ovh', 'generic', 'OVH SAS'),
    array('.pa', 'country-code', 'Universidad Tecnologica de Panama'),
    array('.paris', 'generic', 'City of Paris'),
    array('.partners', 'generic', 'Magic Glen, LLC'),
    array('.parts', 'generic', 'Sea Goodbye, LLC'),
    array('.pe', 'country-code', 'Red Cientifica Peruana'),
    array('.pf', 'country-code', 'Gouvernement de la Polynésie française'),
    array('.pg', 'country-code', 'PNG DNS Administration Vice Chancellors Office The Papua New Guinea University of Technology'),
    array('.ph', 'country-code', 'PH Domain Foundation'),
    array('.pharmacy', 'generic', 'National Association of Boards of Pharmacy'),
    array('.photo', 'generic', 'Uniregistry, Corp.'),
    array('.photography', 'generic', 'Sugar Glen, LLC'),
    array('.photos', 'generic', 'Sea Corner, LLC'),
    array('.physio', 'generic', 'PhysBiz Pty Ltd'),
    array('.pics', 'generic', 'Uniregistry, Corp.'),
    array('.pictures', 'generic', 'Foggy Sky, LLC'),
    array('.pink', 'generic', 'Afilias Limited'),
    array('.pizza', 'generic', 'Foggy Moon, LLC'),
    array('.pk', 'country-code', 'PKNIC'),
    array('.pl', 'country-code', 'Research and Academic Computer Network'),
    array('.place', 'generic', 'Snow Galley, LLC'),
    array('.plumbing', 'generic', 'Spring Tigers, LLC'),
    array('.pm', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.pn', 'country-code', 'Pitcairn Island Administration'),
    array('.pohl', 'generic', 'Deutsche Vermögensberatung Aktiengesellschaft DVAG'),
    array('.post', 'sponsored', 'Universal Postal Union'),
    array('.pr', 'country-code', 'Gauss Research Laboratory Inc.'),
    array('.praxi', 'generic', 'Praxi S.p.A.'),
    array('.press', 'generic', 'DotPress Inc.'),
    array('.pro', 'generic-restricted', 'Registry Services Corporation dba RegistryPro'),
    array('.prod', 'generic', 'Charleston Road Registry Inc.'),
    array('.productions', 'generic', 'Magic Birch, LLC'),
    array('.prof', 'generic', 'Charleston Road Registry Inc.'),
    array('.properties', 'generic', 'Big Pass, LLC'),
    array('.property', 'generic', 'Uniregistry, Corp.'),
    array('.ps', 'country-code', 'Ministry Of Telecommunications & Information Technology, Government Computer Center.'),
    array('.pt', 'country-code', 'Associação DNS.PT'),
    array('.pub', 'generic', 'United TLD Holdco Ltd.'),
    array('.pw', 'country-code', 'Micronesia Investment and Development Corporation'),
    array('.py', 'country-code', 'NIC-PY'),
    array('.qa', 'country-code', 'The Supreme Council of Information and Communication Technology (ictQATAR)'),
    array('.qpon', 'generic', 'dotCOOL, Inc.'),
    array('.quebec', 'generic', 'PointQuébec Inc'),
    array('.re', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.realtor', 'generic', 'Real Estate Domains LLC'),
    array('.recipes', 'generic', 'Grand Island, LLC'),
    array('.red', 'generic', 'Afilias Limited'),
    array('.rehab', 'generic', 'United TLD Holdco Ltd.'),
    array('.reise', 'generic', 'dotreise GmbH'),
    array('.reisen', 'generic', 'New Cypress, LLC'),
    array('.ren', 'generic', 'Beijing Qianxiang Wangjing Technology Development Co., Ltd.'),
    array('.rentals', 'generic', 'Big Hollow,LLC'),
    array('.repair', 'generic', 'Lone Sunset, LLC'),
    array('.report', 'generic', 'Binky Glen, LLC'),
    array('.republican', 'generic', 'United TLD Holdco Ltd.'),
    array('.rest', 'generic', 'Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable'),
    array('.restaurant', 'generic', 'Snow Avenue, LLC'),
    array('.reviews', 'generic', 'United TLD Holdco, Ltd.'),
    array('.rich', 'generic', 'I-REGISTRY Ltd., Niederlassung Deutschland'),
    array('.rio', 'generic', 'Empresa Municipal de Informática SA - IPLANRIO'),
    array('.ro', 'country-code', 'National Institute for R&D in Informatics'),
    array('.rocks', 'generic', 'United TLD Holdco, LTD.'),
    array('.rodeo', 'generic', 'Top Level Domain Holdings Limited'),
    array('.rs', 'country-code', 'Serbian National Internet Domain Registry (RNIDS)'),
    array('.rsvp', 'generic', 'Charleston Road Registry Inc.'),
    array('.ru', 'country-code', 'Coordination Center for TLD RU'),
    array('.ruhr', 'generic', 'regiodot GmbH & Co. KG'),
    array('.rw', 'country-code', 'Rwanda Information Communication and Technology Association (RICTA)'),
    array('.ryukyu', 'generic', 'BusinessRalliart inc.'),
    array('.sa', 'country-code', 'Communications and Information Technology Commission'),
    array('.saarland', 'generic', 'dotSaarland GmbH'),
    array('.sarl', 'generic', 'Delta Orchard, LLC'),
    array('.sb', 'country-code', 'Solomon Telekom Company Limited'),
    array('.sc', 'country-code', 'VCS Pty Ltd'),
    array('.sca', 'generic', 'SVENSKA CELLULOSA AKTIEBOLAGET SCA (publ)'),
    array('.scb', 'generic', 'The Siam Commercial Bank Public Company Limited ("SCB")'),
    array('.schmidt', 'generic', 'SALM S.A.S.'),
    array('.schule', 'generic', 'Outer Moon, LLC'),
    array('.scot', 'generic', 'Dot Scot Registry Limited'),
    array('.sd', 'country-code', 'Sudan Internet Society'),
    array('.se', 'country-code', 'The Internet Infrastructure Foundation'),
    array('.services', 'generic', 'Fox Castle, LLC'),
    array('.sexy', 'generic', 'Uniregistry, Corp.'),
    array('.sg', 'country-code', 'Singapore Network Information Centre (SGNIC) Pte Ltd'),
    array('.sh', 'country-code', 'Government of St. Helena'),
    array('.shiksha', 'generic', 'Afilias Limited'),
    array('.shoes', 'generic', 'Binky Galley, LLC'),
    array('.si', 'country-code', 'Academic and Research Network of Slovenia (ARNES)'),
    array('.singles', 'generic', 'Fern Madison, LLC'),
    array('.sj', 'country-code', 'UNINETT Norid A/S'),
    array('.sk', 'country-code', 'SK-NIC, a.s.'),
    array('.sl', 'country-code', 'Sierratel'),
    array('.sm', 'country-code', 'Telecom Italia San Marino S.p.A.'),
    array('.sn', 'country-code', 'Universite Cheikh Anta Diop NIC Senegal'),
    array('.so', 'country-code', 'Ministry of Post and Telecommunications'),
    array('.social', 'generic', 'United TLD Holdco Ltd.'),
    array('.software', 'generic', 'United TLD Holdco, Ltd'),
    array('.sohu', 'generic', 'Sohu.com Limited'),
    array('.solar', 'generic', 'Ruby Town, LLC'),
    array('.solutions', 'generic', 'Silver Cover, LLC'),
    array('.soy', 'generic', 'Charleston Road Registry Inc.'),
    array('.space', 'generic', 'DotSpace Inc.'),
    array('.spiegel', 'generic', 'SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG'),
    array('.sr', 'country-code', 'Telesur'),
    array('.ss', 'country-code', 'Not assigned'),
    array('.st', 'country-code', 'Tecnisys'),
    array('.su', 'country-code', 'Russian Institute for Development of Public Networks (ROSNIIROS)'),
    array('.supplies', 'generic', 'Atomic Fields, LLC'),
    array('.supply', 'generic', 'Half Falls, LLC'),
    array('.support', 'generic', 'Grand Orchard, LLC'),
    array('.surf', 'generic', 'Top Level Domain Holdings Limited'),
    array('.surgery', 'generic', 'Tin Avenue, LLC'),
    array('.suzuki', 'generic', 'SUZUKI MOTOR CORPORATION'),
    array('.sv', 'country-code', 'SVNet'),
    array('.sx', 'country-code', 'SX Registry SA B.V.'),
    array('.sy', 'country-code', 'National Agency for Network Services (NANS)'),
    array('.systems', 'generic', 'Dash Cypress, LLC'),
    array('.sz', 'country-code', 'University of Swaziland Department of Computer Science'),
    array('.tatar', 'generic', 'Limited Liability Company "Coordination Center of Regional Domain of Tatarstan Republic"'),
    array('.tattoo', 'generic', 'Uniregistry, Corp.'),
    array('.tax', 'generic', 'Storm Orchard, LLC'),
    array('.tc', 'country-code', 'Melrex TC'),
    array('.td', 'country-code', 'Société des télécommunications du Tchad (SOTEL TCHAD)'),
    array('.technology', 'generic', 'Auburn Falls, LLC'),
    array('.tel', 'sponsored', 'Telnic Ltd.'),
    array('.tf', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.tg', 'country-code', 'Cafe Informatique et Telecommunications'),
    array('.th', 'country-code', 'Thai Network Information Center Foundation'),
    array('.tienda', 'generic', 'Victor Manor, LLC'),
    array('.tips', 'generic', 'Corn Willow, LLC'),
    array('.tirol', 'generic', 'punkt Tirol GmbH'),
    array('.tj', 'country-code', 'Information Technology Center'),
    array('.tk', 'country-code', 'Telecommunication Tokelau Corporation (Teletok)'),
    array('.tl', 'country-code', 'Ministry of Transport and Communications; National Division of Information and Technology'),
    array('.tm', 'country-code', 'TM Domain Registry Ltd'),
    array('.tn', 'country-code', 'Agence Tunisienne d\'Internet'),
    array('.to', 'country-code', 'Government of the Kingdom of Tonga H.R.H. Crown Prince Tupouto\'a c/o Consulate of Tonga'),
    array('.today', 'generic', 'Pearl Woods, LLC'),
    array('.tokyo', 'generic', 'GMO Registry, Inc.'),
    array('.tools', 'generic', 'Pioneer North, LLC'),
    array('.top', 'generic', 'Jiangsu Bangning Science & Technology Co.,Ltd.'),
    array('.town', 'generic', 'Koko Moon, LLC'),
    array('.toys', 'generic', 'Pioneer Orchard, LLC'),
    array('.tp', 'country-code', '-'),
    array('.tr', 'country-code', 'Middle East Technical University Department of Computer Engineering'),
    array('.trade', 'generic', 'Elite Registry Limited'),
    array('.training', 'generic', 'Wild Willow, LLC'),
    array('.travel', 'sponsored', 'Tralliance Registry Management Company, LLC.'),
    array('.tt', 'country-code', 'University of the West Indies Faculty of Engineering'),
    array('.tui', 'generic', 'TUI AG'),
    array('.tv', 'country-code', 'Ministry of Finance and Tourism'),
    array('.tw', 'country-code', 'Taiwan Network Information Center (TWNIC)'),
    array('.tz', 'country-code', 'Tanzania Network Information Centre (tzNIC)'),
    array('.ua', 'country-code', 'Hostmaster Ltd.'),
    array('.ug', 'country-code', 'Uganda Online Ltd.'),
    array('.uk', 'country-code', 'Nominet UK'),
    array('.um', 'country-code', 'Not assigned'),
    array('.university', 'generic', 'Little Station, LLC'),
    array('.uno', 'generic', 'Dot Latin LLC'),
    array('.uol', 'generic', 'UBN INTERNET LTDA.'),
    array('.us', 'country-code', 'NeuStar, Inc.'),
    array('.uy', 'country-code', 'SeCIU - Universidad de la Republica'),
    array('.uz', 'country-code', 'Computerization and Information Technologies Developing Center UZINFOCOM'),
    array('.va', 'country-code', 'Holy See Secretariat of State Department of Telecommunications'),
    array('.vacations', 'generic', 'Atomic Tigers, LLC'),
    array('.vc', 'country-code', 'Ministry of Telecommunications, Science, Technology and Industry'),
    array('.ve', 'country-code', 'Comisión Nacional de Telecomunicaciones (CONATEL)'),
    array('.vegas', 'generic', 'Dot Vegas, Inc.'),
    array('.ventures', 'generic', 'Binky Lake, LLC'),
    array('.versicherung', 'generic', 'dotversicherung-registry GmbH'),
    array('.vet', 'generic', 'United TLD Holdco, Ltd'),
    array('.vg', 'country-code', 'Telecommunications Regulatory Commission of the Virgin Islands'),
    array('.vi', 'country-code', 'Virgin Islands Public Telcommunications System c/o COBEX Internet Services'),
    array('.viajes', 'generic', 'Black Madison, LLC'),
    array('.villas', 'generic', 'New Sky, LLC'),
    array('.vision', 'generic', 'Koko Station, LLC'),
    array('.vlaanderen', 'generic', 'DNS.be vzw'),
    array('.vn', 'country-code', 'Ministry of Information and Communications of Socialist Republic of Viet Nam'),
    array('.vodka', 'generic', 'Top Level Domain Holdings Limited'),
    array('.vote', 'generic', 'Monolith Registry LLC'),
    array('.voting', 'generic', 'Valuetainment Corp.'),
    array('.voto', 'generic', 'Monolith Registry LLC'),
    array('.voyage', 'generic', 'Ruby House, LLC'),
    array('.vu', 'country-code', 'Telecom Vanuatu Limited'),
    array('.wales', 'generic', 'Nominet UK'),
    array('.wang', 'generic', 'Zodiac Registry Limited'),
    array('.watch', 'generic', 'Sand Shadow, LLC'),
    array('.webcam', 'generic', 'dot Webcam Limited'),
    array('.website', 'generic', 'DotWebsite Inc.'),
    array('.wed', 'generic', 'Atgron, Inc.'),
    array('.wf', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.whoswho', 'generic', 'Who\'s Who Registry'),
    array('.wien', 'generic', 'punkt.wien GmbH'),
    array('.wiki', 'generic', 'Top Level Design, LLC'),
    array('.williamhill', 'generic', 'William Hill Organization Limited'),
    array('.wme', 'generic', 'William Morris Endeavor Entertainment, LLC'),
    array('.work', 'generic', 'Top Level Domain Holdings Limited'),
    array('.works', 'generic', 'Little Dynamite, LLC'),
    array('.world', 'generic', 'Bitter Fields, LLC'),
    array('.ws', 'country-code', 'Government of Samoa Ministry of Foreign Affairs & Trade'),
    array('.wtc', 'generic', 'World Trade Centers Association, Inc.'),
    array('.wtf', 'generic', 'Hidden Way, LLC'),
    array('.测试', 'test', 'Internet Assigned Numbers Authority'),
    array('.परीक्षा', 'test', 'Internet Assigned Numbers Authority'),
    array('.佛山', 'generic', 'Guangzhou YU Wei Information Technology Co., Ltd.'),
    array('.集团', 'generic', 'Eagle Horizon Limited'),
    array('.在线', 'generic', 'TLD REGISTRY LIMITED'),
    array('.한국', 'country-code', 'KISA (Korea Internet & Security Agency)'),
    array('.ভারত', 'country-code', 'National Internet Exchange of India'),
    array('.موقع', 'generic', 'Suhub Electronic Establishment'),
    array('.বাংলা', 'country-code', 'Not assigned'),
    array('.公益', 'generic', 'China Organizational Name Administration Center'),
    array('.公司', 'generic', 'Computer Network Information Center of Chinese Academy of Sciences （China Internet Network Information Center）'),
    array('.移动', 'generic', 'Afilias Limited'),
    array('.我爱你', 'generic', 'Tycoon Treasure Limited'),
    array('.москва', 'generic', 'Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)'),
    array('.испытание', 'test', 'Internet Assigned Numbers Authority'),
    array('.қаз', 'country-code', 'Association of IT Companies of Kazakhstan'),
    array('.онлайн', 'generic', 'CORE Association'),
    array('.сайт', 'generic', 'CORE Association'),
    array('.срб', 'country-code', 'Serbian National Internet Domain Registry (RNIDS)'),
    array('.бел', 'country-code', 'Not assigned'),
    array('.테스트', 'test', 'Internet Assigned Numbers Authority'),
    array('.орг', 'generic', 'Public Interest Registry'),
    array('.삼성', 'generic', 'SAMSUNG SDS CO., LTD'),
    array('.சிங்கப்பூர்', 'country-code', 'Singapore Network Information Centre (SGNIC) Pte Ltd'),
    array('.商标', 'generic', 'HU YI GLOBAL INFORMATION RESOURCES(HOLDING) COMPANY.HONGKONG LIMITED'),
    array('.商城', 'generic', 'Zodiac Aquarius Limited'),
    array('.дети', 'generic', 'The Foundation for Network Initiatives “The Smart Internet”'),
    array('.мкд', 'country-code', 'Not assigned'),
    array('.טעסט', 'test', 'Internet Assigned Numbers Authority'),
    array('.中文网', 'generic', 'TLD REGISTRY LIMITED'),
    array('.中信', 'generic', 'CITIC Group Corporation'),
    array('.中国', 'country-code', 'China Internet Network Information Center'),
    array('.中國', 'country-code', 'China Internet Network Information Center'),
    array('.భారత్', 'country-code', 'National Internet Exchange of India'),
    array('.ලංකා', 'country-code', 'LK Domain Registry'),
    array('.測試', 'test', 'Internet Assigned Numbers Authority'),
    array('.ભારત', 'country-code', 'National Internet Exchange of India'),
    array('.भारत', 'country-code', 'National Internet Exchange of India'),
    array('.آزمایشی', 'test', 'Internet Assigned Numbers Authority'),
    array('.பரிட்சை', 'test', 'Internet Assigned Numbers Authority'),
    array('.संगठन', 'generic', 'Public Interest Registry'),
    array('.网络', 'generic', 'Computer Network Information Center of Chinese Academy of Sciences （China Internet Network Information Center）'),
    array('.укр', 'country-code', 'Ukrainian Network Information Centre (UANIC), Inc.'),
    array('.香港', 'country-code', 'Hong Kong Internet Registration Corporation Ltd.'),
    array('.δοκιμή', 'test', 'Internet Assigned Numbers Authority'),
    array('.إختبار', 'test', 'Internet Assigned Numbers Authority'),
    array('.台湾', 'country-code', 'Taiwan Network Information Center (TWNIC)'),
    array('.台灣', 'country-code', 'Taiwan Network Information Center (TWNIC)'),
    array('.手机', 'generic', 'Beijing RITT-Net Technology Development Co., Ltd'),
    array('.мон', 'country-code', 'Datacom Co.,Ltd'),
    array('.الجزائر', 'country-code', 'CERIST'),
    array('.عمان', 'country-code', 'Telecommunications Regulatory Authority (TRA)'),
    array('.ایران', 'country-code', 'Institute for Research in Fundamental Sciences (IPM)'),
    array('.امارات', 'country-code', 'Telecommunications Regulatory Authority (TRA)'),
    array('.بازار', 'generic', 'CORE Association'),
    array('.پاکستان', 'country-code', 'Not assigned'),
    array('.الاردن', 'country-code', 'National Information Technology Center (NITC)'),
    array('.بھارت', 'country-code', 'National Internet Exchange of India'),
    array('.المغرب', 'country-code', 'Agence Nationale de Réglementation des Télécommunications (ANRT)'),
    array('.السعودية', 'country-code', 'Communications and Information Technology Commission'),
    array('.سودان', 'country-code', 'Not assigned'),
    array('.عراق', 'country-code', 'Not assigned'),
    array('.مليسيا', 'country-code', 'MYNIC Berhad'),
    array('.شبكة', 'generic', 'International Domain Registry Pty. Ltd.'),
    array('.გე', 'country-code', 'Not assigned'),
    array('.机构', 'generic', 'Public Interest Registry'),
    array('.组织机构', 'generic', 'Public Interest Registry'),
    array('.ไทย', 'country-code', 'Thai Network Information Center Foundation'),
    array('.سورية', 'country-code', 'National Agency for Network Services (NANS)'),
    array('.рус', 'generic', 'Rusnames Limited'),
    array('.рф', 'country-code', 'Coordination Center for TLD RU'),
    array('.تونس', 'country-code', 'Agence Tunisienne d\'Internet'),
    array('.みんな', 'generic', 'Charleston Road Registry Inc.'),
    array('.世界', 'generic', 'Stable Tone Limited'),
    array('.ਭਾਰਤ', 'country-code', 'National Internet Exchange of India'),
    array('.网址', 'generic', 'HU YI GLOBAL INFORMATION RESOURCES (HOLDING) COMPANY. HONGKONG LIMITED'),
    array('.游戏', 'generic', 'Spring Fields, LLC'),
    array('.vermögensberater', 'generic', 'Deutsche Vermögensberatung Aktiengesellschaft DVAG'),
    array('.vermögensberatung', 'generic', 'Deutsche Vermögensberatung Aktiengesellschaft DVAG'),
    array('.企业', 'generic', 'Dash McCook, LLC'),
    array('.مصر', 'country-code', 'National Telecommunication Regulatory Authority - NTRA'),
    array('.قطر', 'country-code', 'Supreme Council for Communications and Information Technology (ictQATAR)'),
    array('.广东', 'generic', 'Guangzhou YU Wei Information Technology Co., Ltd.'),
    array('.இலங்கை', 'country-code', 'LK Domain Registry'),
    array('.இந்தியா', 'country-code', 'National Internet Exchange of India'),
    array('.新加坡', 'country-code', 'Singapore Network Information Centre (SGNIC) Pte Ltd'),
    array('.فلسطين', 'country-code', 'Ministry of Telecom & Information Technology (MTIT)'),
    array('.テスト', 'test', 'Internet Assigned Numbers Authority'),
    array('.政务', 'generic', 'China Organizational Name Administration Center'),
    array('.xxx', 'sponsored', 'ICM Registry LLC'),
    array('.xyz', 'generic', 'XYZ.COM LLC'),
    array('.yachts', 'generic', 'DERYachts, LLC'),
    array('.yandex', 'generic', 'YANDEX, LLC'),
    array('.ye', 'country-code', 'TeleYemen'),
    array('.yokohama', 'generic', 'GMO Registry, Inc.'),
    array('.youtube', 'generic', 'Charleston Road Registry Inc.'),
    array('.yt', 'country-code', 'Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)'),
    array('.za', 'country-code', 'ZA Domain Name Authority'),
    array('.zip', 'generic', 'Charleston Road Registry Inc.'),
    array('.zm', 'country-code', 'Zambia Information and Communications Technology Authority (ZICTA)'),
    array('.zone', 'generic', 'Outer Falls, LLC'),
    array('.zw', 'country-code', 'Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)'),
);

