<?php 
return array (
  'router_name' => '测试',
  'router_mac' => '00:17:a5:e0:b2:a9',
  'qq_verify' => 1,
  'weibo_verify' => 1,
  'weixin_verify' => 1,
  'mobile_verify' => 0,
  'akey_verify' => 1,
  'virtual_verify' => 1,
  'homepage_logo' => '55764785591c0.jpg',
  'homepage_banner' => '5576478995f91.jpg',
  'shop_name' => '集客科技',
  'shop_address' => '',
  'weibo_name' => '集客集客',
  'weixin_name' => '集客科技',
  'weixin_id' => '',
  'online_times' => 0,
  'online_times1' => 0,
  'template' => 1,
  'online_type' => '',
  'rest_online_times' => '',
  'href' => 'website',
  'href_website' => '',
  'ad_times' => '10',
  'qr_code' => '557645f0bd133.jpg',
  'telephone' => '18607162209',
  'auth_status' => 0,
  'one_auth_type' => '',
  'one_auth_href' => '',
  'two_auth_type' => '',
  'two_auth_href' => '',
  'old_user_auth_type' => 0,
  'ad_status' => 1,
  'ad_list' => 
  array (
    0 => 
    array (
      'title' => '',
      'image' => '55764d5458007.jpg',
    ),
  ),
);