<?php
/**
 * @var \Ke\Web\Context          $this
 * @var \Ke\Web\Http             $http
 * @var \Ke\Web\Web              $web
 * @var string                   $content
 * @var \Ke\Utils\DocMen\DocHtml $html
 */

use Ke\Utils\DocMen\DocMen;

/** @var \Ke\Utils\DocMen\DocMen $doc */
$doc = $this->doc;
?>
<div class="ui left close rail">
	<div>
		<div class="ui top attached block header">Namespaces
			<small class="count"><?php print $doc->getAllNamespacesCount(); ?></small>
		</div>
		<div class="ui bottom attached segment">
			<div class="ui list">
				<?php foreach ($doc->getAllNamespaces() as $ns => $hash) { ?>
					<div class="item">
						<i class="folder icon"></i>
						<div class="content">
							<div class="head scope-name"><?php print $html->scopeLink(DocMen::NS, $ns); ?></div>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
