<div class="container index-well">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h2><span class="glyphicon glyphicon-th-large"></span> 常见问题</h2>
			<hr class="solid">
			<h2><?php echo SYS_NAME ?>是一家什么网站？</h2> 
			<p> <?php echo SYS_NAME ?>是一个互联网信息交换平台，面向个人提供安全、便捷、透明的信息解决方案。共享信息资源，扩展交际圈，方便即时、便捷的联系。</p>
			<h2><?php echo SYS_NAME ?>提供什么样的服务？</h2> 
			<p> <?php echo SYS_NAME ?>智能的整合了生活全领域服务信息，通过PC端及移动互联网端的全平台覆盖，为用户提供招聘求职、房屋租售、车辆买卖、二手物品买卖 、宠物票务、教育培训、同城活动及交友等全方位的本地生活及商务服务类信息，帮助用户安全便捷的找到所需生活服务信息，解决生活难题。 </p>
			<h2><?php echo SYS_NAME ?>超级日历是一项什么服务？</h2> 
			<p> <?php echo SYS_NAME ?>超级日历是以日历日期为载体，实时显示活动、事件等及时信息的通用服务。 </p>
		</div>
	</div>
</div>
