<div class="container index-well">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h2><span class="glyphicon glyphicon-th-large"></span> 联系我们</h2>
			<hr class="solid">
			<p> <?php echo SYS_NAME ?>当前的服务已覆盖整个衡阳地区，在湖南衡阳设有办公场所，在湖南衡阳设有专业的服务中心。 </p>
			<h2>湖南总部</h2> 
			<p> 地址：衡阳市珠晖区东风支路100号 </p>
			<p> 邮编：421001 </p>
			<h2>联系电话</h2> 
			<p> 如果您在使用<?php echo SYS_NAME ?>(hiici.com)的过程中有任何疑问请您与<?php echo SYS_NAME ?>联系。 </p>
			<p> 联系电话：137-8642-0875 </p>
			<h2>商务合作</h2> 
			<p> 如果贵公司希望与我们建立商务合作关系，形成优势互补，请将合作意向进行简要描述并发送邮件至： </p>
			<p> postmaster@hiici.com，我们会尽快与您联系。  </p>
			<p> 备注：<?php echo SYS_NAME ?>目前暂时没有线下加盟/线下开店等商务合作模式，谢谢关注。</p>
			<h2>信息同步</h2> 
			<p> 微信公众平台：hiici（扫描右侧二维码关注<?php echo SYS_NAME ?>微信） </p>
			<p> 新浪博客：<a>blog.sina.com.cn/hiici</a> </p>
			<p> 新浪微博：<a>e.weibo.com/hiici</a> </p>
			<p> 腾讯微博：<a>t.qq.com/hiici</a> </p>
		</div>
	</div>
</div>
