<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="forum_city_choice">
				<img class="forum_city_choice_head" src="img/index/forum_city_choice_head.png"/>
				<ul class="list-unstyled">
					<li class="city-list clearfix">
					<b class="u_city">
					<span class="glyphicon glyphicon-map-marker"></span> 进入 <a id="u_city" href="#"></a><?php echo '-'.SYS_NAME ?> -->
					</b>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
					A 
					</span>
					<ul class="list-inline">
						<li><a href="#">阿拉善</a></li>
						<li><a href="#"><b>鞍山</b></a></li>
						<li><a href="#"><b>安庆</b></a></li>
						<li><a href="#"><b>安阳</b></a></li>
						<li><a href="#">阿坝藏族羌族</a></li>
						<li><a href="#">安顺</a></li>
						<li><a href="#">阿里</a></li>
						<li><a href="#"><b>安康</b></a></li>
						<li><a href="#">阿克苏</a></li>
						<li><a href="#">克孜勒苏柯尔克孜</a></li>
						<li><a href="#">阿勒泰</a></li>
						<li><a href="#">澳门</a></li>
						<li><a href="#">安丘</a></li>
						<li><a href="#"><b>安吉</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						B
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>北京</b></a></li>
						<li><a href="#"><b>保定</b></a></li>
						<li><a href="#"><b>包头</b></a></li>
						<li><a href="#">巴彦淖尔</a></li>
						<li><a href="#"><b>本溪</b></a></li>
						<li><a href="#"><b>白山</b></a></li>
						<li><a href="#"><b>白城</b></a></li>
						<li><a href="#"><b>蚌埠</b></a></li>
						<li><a href="#"><b>滨州</b></a></li>
						<li><a href="#"><b>北海</b></a></li>
						<li><a href="#">百色</a></li>
						<li><a href="#"><b>巴中</b></a></li>
						<li><a href="#">毕节</a></li>
						<li><a href="#">保山</a></li>
						<li><a href="#"><b>宝鸡</b></a></li>
						<li><a href="#"><b>白银</b></a></li>
						<li><a href="#"><b>亳州</b></a></li>
						<li><a href="#">博尔塔拉蒙古</a></li>
						<li><a href="#">巴音郭楞蒙古</a></li>
						<li><a href="#">保亭</a></li>
						<li><a href="#">白沙</a></li>
						<li><a href="#"><b>宝丰</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						C
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>承德</b></a></li>
						<li><a href="#"><b>沧州</b></a></li>
						<li><a href="#"><b>长治</b></a></li>
						<li><a href="#"><b>赤峰</b></a></li>
						<li><a href="#"><b>朝阳</b></a></li>
						<li><a href="#"><b>长春</b></a></li>
						<li><a href="#"><b>常州</b></a></li>
						<li><a href="#"><b>滁州</b></a></li>
						<li><a href="#"><b>巢湖</b></a></li>
						<li><a href="#"><b>池州</b></a></li>
						<li><a href="http://cs.hiici.com"><b>长沙</b></a></li>
						<li><a href="#">郴州</a></li>
						<li><a href="#"><b>潮州</b></a></li>
						<li><a href="#"><b>重庆</b></a></li>
						<li><a href="#"><b>成都</b></a></li>
						<li><a href="#">楚雄彝族</a></li>
						<li><a href="#">昌都</a></li>
						<li><a href="#">昌吉回族</a></li>
						<li><a href="#"><b>常德</b></a></li>
						<li><a href="#">崇左</a></li>
						<li><a href="#"><b>慈溪</b></a></li>
						<li><a href="#"><b>常熟</b></a></li>
						<li><a href="#">澄迈</a></li>
						<li><a href="#">昌江</a></li>
						<li><a href="#"><b>长兴</b></a></li>
						<li><a href="#"><b>淳安</b></a></li>
						<li><a href="#"><b>长葛</b></a></li>
						<li><a href="#"><b>长垣</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						D
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>大同</b></a></li>
						<li><a href="#"><b>大连</b></a></li>
						<li><a href="#"><b>丹东</b></a></li>
						<li><a href="#"><b>大庆</b></a></li>
						<li><a href="#">大兴安岭</a></li>
						<li><a href="#"><b>东营</b></a></li>
						<li><a href="#"><b>德州</b></a></li>
						<li><a href="#"><b>东莞</b></a></li>
						<li><a href="#"><b>德阳</b></a></li>
						<li><a href="#"><b>达州</b></a></li>
						<li><a href="#"><b>大理白族</b></a></li>
						<li><a href="#">迪庆藏族</a></li>
						<li><a href="#">定西</a></li>
						<li><a href="#">德宏傣族景颇族</a></li>
						<li><a href="#"><b>儋州</b></a></li>
						<li><a href="#">东方</a></li>
						<li><a href="#">定安</a></li>
						<li><a href="#"><b>登封</b></a></li>
						<li><a href="#"><b>德清</b></a></li>
						<li><a href="#"><b>东阳</b></a></li>
						<li><a href="#"><b>大丰</b></a></li>
						<li><a href="#"><b>敦化</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						E
					</span>
					<ul class="list-inline">
						<li><a href="#">鄂尔多斯</a></li>
						<li><a href="#"><b>峨眉山</b></a></li>
						<li><a href="#">鄂州</a></li>
						<li><a href="#"><b>恩施</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						F
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>抚顺</b></a></li>
						<li><a href="#"><b>阜新</b></a></li>
						<li><a href="#"><b>阜阳</b></a></li>
						<li><a href="#"><b>福州</b></a></li>
						<li><a href="#">抚州</a></li>
						<li><a href="#"><b>佛山</b></a></li>
						<li><a href="#">防城港</a></li>
						<li><a href="#"><b>富阳</b></a></li>
						<li><a href="#"><b>福清</b></a></li>
						<li><a href="#">凤凰</a></li>
						<li><a href="#">丰县</a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						G
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>赣州</b></a></li>
						<li><a href="#"><b>广州</b></a></li>
						<li><a href="#"><b>桂林</b></a></li>
						<li><a href="#">贵港</a></li>
						<li><a href="#"><b>贵阳</b></a></li>
						<li><a href="#">甘南藏族</a></li>
						<li><a href="#">果洛藏族</a></li>
						<li><a href="#">固原</a></li>
						<li><a href="#"><b>广元</b></a></li>
						<li><a href="#">广安</a></li>
						<li><a href="#">甘孜藏族</a></li>
						<li><a href="#"><b>巩义</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						H
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>邯郸</b></a></li>
						<li><a href="#"><b>衡水</b></a></li>
						<li><a href="#"><b>呼和浩特</b></a></li>
						<li><a href="#">呼伦贝尔</a></li>
						<li><a href="#"><b>葫芦岛</b></a></li>
						<li><a href="#"><b>哈尔滨</b></a></li>
						<li><a href="#"><b>鹤岗</b></a></li>
						<li><a href="#"><b>黑河</b></a></li>
						<li><a href="#"><b>淮安</b></a></li>
						<li><a href="#"><b>杭州</b></a></li>
						<li><a href="#"><b>湖州</b></a></li>
						<li><a href="#"><b>合肥</b></a></li>
						<li><a href="#"><b>淮南</b></a></li>
						<li><a href="#"><b>淮北</b></a></li>
						<li><a href="#"><b>鹤壁</b></a></li>
						<li><a href="#"><b>黄石</b></a></li>
						<li><a href="http://hy.hiici.com"><b>衡阳</b></a></li>
						<li><a href="#"><b>怀化</b></a></li>
						<li><a href="#"><b>惠州</b></a></li>
						<li><a href="#"><b>河源</b></a></li>
						<li><a href="#">贺州</a></li>
						<li><a href="#">河池</a></li>
						<li><a href="#"><b>海口</b></a></li>
						<li><a href="#">红河哈尼族彝族</a></li>
						<li><a href="#"><b>汉中</b></a></li>
						<li><a href="#">海东</a></li>
						<li><a href="#">海北藏族</a></li>
						<li><a href="#">黄南藏族</a></li>
						<li><a href="#">海西蒙古族藏族</a></li>
						<li><a href="#">哈密</a></li>
						<li><a href="#"><b>菏泽</b></a></li>
						<li><a href="#"><b>黄山</b></a></li>
						<li><a href="#">海南藏族</a></li>
						<li><a href="#">和田</a></li>
						<li><a href="#"><b>海门</b></a></li>
						<li><a href="#"><b>黄冈</b></a></li>
						<li><a href="#"><b>桦甸</b></a></li>
						<li><a href="#"><b>海安</b></a></li>
						<li><a href="#"><b>海宁</b></a></li>
						<li><a href="#"><b>海阳</b></a></li>
						<li><a href="#"><b>辉县</b></a></li>
						<li><a href="#"><b>珲春</b></a></li>
						<li><a href="#"><b>韩城</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						J
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>晋城</b></a></li>
						<li><a href="#"><b>晋中</b></a></li>
						<li><a href="#"><b>锦州</b></a></li>
						<li><a href="#"><b>吉林</b></a></li>
						<li><a href="#"><b>鸡西</b></a></li>
						<li><a href="#"><b>佳木斯</b></a></li>
						<li><a href="#"><b>嘉兴</b></a></li>
						<li><a href="#"><b>金华</b></a></li>
						<li><a href="#">吉安</a></li>
						<li><a href="#"><b>济南</b></a></li>
						<li><a href="#"><b>济宁</b></a></li>
						<li><a href="#"><b>焦作</b></a></li>
						<li><a href="#">荆门</a></li>
						<li><a href="#"><b>江门</b></a></li>
						<li><a href="#"><b>揭阳</b></a></li>
						<li><a href="#">嘉峪关</a></li>
						<li><a href="#">金昌</a></li>
						<li><a href="#">酒泉</a></li>
						<li><a href="#"><b>景德镇</b></a></li>
						<li><a href="#"><b>九江</b></a></li>
						<li><a href="#"><b>江阴</b></a></li>
						<li><a href="#"><b>济源</b></a></li>
						<li><a href="#"><b>荆州</b></a></li>
						<li><a href="#"><b>晋江</b></a></li>
						<li><a href="#">九寨沟</a></li>
						<li><a href="#"><b>靖江</b></a></li>
						<li><a href="#"><b>金坛</b></a></li>
						<li><a href="#"><b>嘉善</b></a></li>
						<li><a href="#"><b>建德</b></a></li>
						<li><a href="#"><b>界首</b></a></li>
						<li><a href="#"><b>郏县</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						K
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>开封</b></a></li>
						<li><a href="#"><b>昆明</b></a></li>
						<li><a href="#">克拉玛依</a></li>
						<li><a href="#">喀什</a></li>
						<li><a href="#"><b>昆山</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						L
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>廊坊</b></a></li>
						<li><a href="#"><b>临汾</b></a></li>
						<li><a href="#"><b>吕梁</b></a></li>
						<li><a href="#"><b>辽阳</b></a></li>
						<li><a href="#"><b>辽源</b></a></li>
						<li><a href="#"><b>连云港</b></a></li>
						<li><a href="#"><b>丽水</b></a></li>
						<li><a href="#"><b>六安</b></a></li>
						<li><a href="#"><b>龙岩</b></a></li>
						<li><a href="#"><b>莱芜</b></a></li>
						<li><a href="#"><b>临沂</b></a></li>
						<li><a href="#"><b>聊城</b></a></li>
						<li><a href="#"><b>洛阳</b></a></li>
						<li><a href="#"><b>漯河</b></a></li>
						<li><a href="#">娄底</a></li>
						<li><a href="#"><b>柳州</b></a></li>
						<li><a href="#"><b>泸州</b></a></li>
						<li><a href="#">凉山彝族</a></li>
						<li><a href="#">六盘水</a></li>
						<li><a href="#"><b>丽江</b></a></li>
						<li><a href="#">临沧</a></li>
						<li><a href="#">拉萨</a></li>
						<li><a href="#"><b>兰州</b></a></li>
						<li><a href="#">临夏回族</a></li>
						<li><a href="#">来宾</a></li>
						<li><a href="#">陇南</a></li>
						<li><a href="#"><b>乐山</b></a></li>
						<li><a href="#"><b>龙口</b></a></li>
						<li><a href="#">临高</a></li>
						<li><a href="#">龙胜</a></li>
						<li><a href="#"><b>溧阳</b></a></li>
						<li><a href="#">乐东</a></li>
						<li><a href="#"><b>陵水</b></a></li>
						<li><a href="#"><b>临海</b></a></li>
						<li><a href="#"><b>兰溪</b></a></li>
						<li><a href="#">辽宁</a></li>
						<li><a href="#"><b>临安</b></a></li>
						<li><a href="#">临夏</a></li>
						<li><a href="#"><b>林州</b></a></li>
						<li><a href="#"><b>鲁山</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						M
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>牡丹江</b></a></li>
						<li><a href="#"><b>马鞍山</b></a></li>
						<li><a href="#"><b>茂名</b></a></li>
						<li><a href="#"><b>梅州</b></a></li>
						<li><a href="#"><b>绵阳</b></a></li>
						<li><a href="#"><b>眉山</b></a></li>
						<li><a href="#">满洲里</a></li>
						<li><a href="#"><b>明光</b></a></li>
						<li><a href="#"><b>孟津</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						N
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>南京</b></a></li>
						<li><a href="#"><b>南通</b></a></li>
						<li><a href="#"><b>宁波</b></a></li>
						<li><a href="#"><b>南平</b></a></li>
						<li><a href="#"><b>宁德</b></a></li>
						<li><a href="#"><b>南昌</b></a></li>
						<li><a href="#"><b>南阳</b></a></li>
						<li><a href="#"><b>南宁</b></a></li>
						<li><a href="#"><b>南充</b></a></li>
						<li><a href="#">怒江傈僳族</a></li>
						<li><a href="#">那曲</a></li>
						<li><a href="#">林芝</a></li>
						<li><a href="#">内江</a></li>
						<li><a href="#"><b>宁国</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						P
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>盘锦</b></a></li>
						<li><a href="#"><b>莆田</b></a></li>
						<li><a href="#"><b>平顶山</b></a></li>
						<li><a href="#"><b>濮阳</b></a></li>
						<li><a href="#">攀枝花</a></li>
						<li><a href="#">平凉</a></li>
						<li><a href="#"><b>萍乡</b></a></li>
						<li><a href="#"><b>普洱</b></a></li>
						<li><a href="#"><b>平湖</b></a></li>
						<li><a href="#"><b>蓬莱</b></a></li>
						<li><a href="#">沛县</a></li>
						<li><a href="#">邳州</a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						Q
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>秦皇岛</b></a></li>
						<li><a href="#"><b>忻州</b></a></li>
						<li><a href="#"><b>齐齐哈尔</b></a></li>
						<li><a href="#">七台河</a></li>
						<li><a href="#"><b>泉州</b></a></li>
						<li><a href="#"><b>青岛</b></a></li>
						<li><a href="#"><b>清远</b></a></li>
						<li><a href="#">钦州</a></li>
						<li><a href="#">黔西南布依族苗族</a></li>
						<li><a href="#">黔南布依族苗族</a></li>
						<li><a href="#"><b>曲靖</b></a></li>
						<li><a href="#">庆阳</a></li>
						<li><a href="#">黔东南苗族侗族</a></li>
						<li><a href="#"><b>衢州</b></a></li>
						<li><a href="#"><b>琼海</b></a></li>
						<li><a href="#">曲阜</a></li>
						<li><a href="#">琼中</a></li>
						<li><a href="#"><b>启东</b></a></li>
						<li><a href="#"><b>青州</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						R
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>日照</b></a></li>
						<li><a href="#">日喀则</a></li>
						<li><a href="#"><b>瑞安</b></a></li>
						<li><a href="#"><b>如皋</b></a></li>
						<li><a href="#"><b>汝州</b></a></li>
						<li><a href="#"><b>荣成</b></a></li>
						<li><a href="#"><b>乳山</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						S
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>石家庄</b></a></li>
						<li><a href="#"><b>朔州</b></a></li>
						<li><a href="#"><b>沈阳</b></a></li>
						<li><a href="#"><b>四平</b></a></li>
						<li><a href="#"><b>双鸭山</b></a></li>
						<li><a href="#"><b>绥化</b></a></li>
						<li><a href="#"><b>上海</b></a></li>
						<li><a href="#"><b>苏州</b></a></li>
						<li><a href="#"><b>宿迁</b></a></li>
						<li><a href="#"><b>绍兴</b></a></li>
						<li><a href="#"><b>宿州</b></a></li>
						<li><a href="#"><b>三明</b></a></li>
						<li><a href="#"><b>上饶</b></a></li>
						<li><a href="#"><b>三门峡</b></a></li>
						<li><a href="#"><b>商丘</b></a></li>
						<li><a href="#"><b>十堰</b></a></li>
						<li><a href="#">随州</a></li>
						<li><a href="#">邵阳</a></li>
						<li><a href="#"><b>韶关</b></a></li>
						<li><a href="#"><b>深圳</b></a></li>
						<li><a href="#"><b>汕头</b></a></li>
						<li><a href="#"><b>汕尾</b></a></li>
						<li><a href="#"><b>三亚</b></a></li>
						<li><a href="#"><b>遂宁</b></a></li>
						<li><a href="#">山南</a></li>
						<li><a href="#">石嘴山</a></li>
						<li><a href="#"><b>商洛</b></a></li>
						<li><a href="#"><b>松原</b></a></li>
						<li><a href="#">顺德</a></li>
						<li><a href="#"><b>石狮</b></a></li>
						<li><a href="#">石河子</a></li>
						<li><a href="#">三河</a></li>
						<li><a href="#"><b>上虞</b></a></li>
						<li><a href="#"><b>寿光</b></a></li>
						<li><a href="#">睢宁</a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						T
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>天津</b></a></li>
						<li><a href="#"><b>唐山</b></a></li>
						<li><a href="#"><b>太原</b></a></li>
						<li><a href="#"><b>通辽</b></a></li>
						<li><a href="#"><b>铁岭</b></a></li>
						<li><a href="#"><b>通化</b></a></li>
						<li><a href="#"><b>泰州</b></a></li>
						<li><a href="#"><b>台州</b></a></li>
						<li><a href="#"><b>铜陵</b></a></li>
						<li><a href="#"><b>泰安</b></a></li>
						<li><a href="#">铜仁</a></li>
						<li><a href="#"><b>铜川</b></a></li>
						<li><a href="#"><b>天水</b></a></li>
						<li><a href="#">吐鲁番</a></li>
						<li><a href="#">塔城</a></li>
						<li><a href="#">塘沽</a></li>
						<li><a href="#">屯昌</a></li>
						<li><a href="#"><b>桐乡</b></a></li>
						<li><a href="#"><b>桐庐</b></a></li>
						<li><a href="#"><b>太仓</b></a></li>
						<li><a href="#"><b>桐城</b></a></li>
						<li><a href="#"><b>天长</b></a></li>
						<li><a href="#"><b>汤阴</b></a></li>
						<li><a href="#"><b>唐河</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						W
					</span>
					<ul class="list-inline">
						<li><a href="#">乌海</a></li>
						<li><a href="#">乌兰察布</a></li>
						<li><a href="#"><b>无锡</b></a></li>
						<li><a href="#"><b>温州</b></a></li>
						<li><a href="#"><b>芜湖</b></a></li>
						<li><a href="#"><b>潍坊</b></a></li>
						<li><a href="#"><b>威海</b></a></li>
						<li><a href="#"><b>武汉</b></a></li>
						<li><a href="#">梧州</a></li>
						<li><a href="#">文山壮族苗族</a></li>
						<li><a href="#"><b>渭南</b></a></li>
						<li><a href="#"><b>武威</b></a></li>
						<li><a href="#">吴忠</a></li>
						<li><a href="#"><b>乌鲁木齐</b></a></li>
						<li><a href="#">吴江</a></li>
						<li><a href="#">五指山</a></li>
						<li><a href="#">文昌</a></li>
						<li><a href="#">万宁</a></li>
						<li><a href="#">乌镇</a></li>
						<li><a href="#"><b>武夷山</b></a></li>
						<li><a href="#">婺源</a></li>
						<li><a href="#"><b>温岭</b></a></li>
						<li><a href="#"><b>卫辉</b></a></li>
						<li><a href="#"><b>文登</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						X
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>邢台</b></a></li>
						<li><a href="#">兴安</a></li>
						<li><a href="#">锡林郭勒</a></li>
						<li><a href="#"><b>徐州</b></a></li>
						<li><a href="#"><b>宣城</b></a></li>
						<li><a href="#"><b>厦门</b></a></li>
						<li><a href="#">新余</a></li>
						<li><a href="#"><b>新乡</b></a></li>
						<li><a href="#"><b>许昌</b></a></li>
						<li><a href="#"><b>信阳</b></a></li>
						<li><a href="#"><b>孝感</b></a></li>
						<li><a href="#"><b>湘潭</b></a></li>
						<li><a href="#">湘西土家族苗族</a></li>
						<li><a href="#"><b>西双版纳傣族</b></a></li>
						<li><a href="#"><b>西安</b></a></li>
						<li><a href="#"><b>咸阳</b></a></li>
						<li><a href="#"><b>西宁</b></a></li>
						<li><a href="#">香港</a></li>
						<li><a href="#"><b>襄阳</b></a></li>
						<li><a href="#"><b>咸宁</b></a></li>
						<li><a href="#">西昌</a></li>
						<li><a href="#">象山</a></li>
						<li><a href="#"><b>仙桃</b></a></li>
						<li><a href="#"><b>新郑</b></a></li>
						<li><a href="#"><b>新密</b></a></li>
						<li><a href="#"><b>荥阳</b></a></li>
						<li><a href="#"><b>萧山</b></a></li>
						<li><a href="#">襄樊</a></li>
						<li><a href="#"><b>襄城</b></a></li>
						<li><a href="#"><b>西峡</b></a></li>
						<li><a href="#"><b>淅川</b></a></li>
						<li><a href="#"><b>兴平</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						Y
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>阳泉</b></a></li>
						<li><a href="#"><b>运城</b></a></li>
						<li><a href="#"><b>营口</b></a></li>
						<li><a href="#"><b>延边朝鲜族</b></a></li>
						<li><a href="#"><b>伊春</b></a></li>
						<li><a href="#"><b>盐城</b></a></li>
						<li><a href="#"><b>扬州</b></a></li>
						<li><a href="#">鹰潭</a></li>
						<li><a href="#">宜春</a></li>
						<li><a href="#"><b>烟台</b></a></li>
						<li><a href="#"><b>宜昌</b></a></li>
						<li><a href="#"><b>岳阳</b></a></li>
						<li><a href="#"><b>益阳</b></a></li>
						<li><a href="#">永州</a></li>
						<li><a href="#"><b>阳江</b></a></li>
						<li><a href="#"><b>云浮</b></a></li>
						<li><a href="#"><b>玉林</b></a></li>
						<li><a href="#"><b>宜宾</b></a></li>
						<li><a href="#"><b>玉溪</b></a></li>
						<li><a href="#"><b>延安</b></a></li>
						<li><a href="#"><b>榆林</b></a></li>
						<li><a href="#">玉树藏族</a></li>
						<li><a href="#"><b>银川</b></a></li>
						<li><a href="#">伊犁哈萨克</a></li>
						<li><a href="#">雅安</a></li>
						<li><a href="#"><b>义乌</b></a></li>
						<li><a href="#"><b>延吉</b></a></li>
						<li><a href="#"><b>兖州</b></a></li>
						<li><a href="#"><b>仪征</b></a></li>
						<li><a href="#"><b>宜兴</b></a></li>
						<li><a href="#"><b>乐清</b></a></li>
						<li><a href="#"><b>余姚</b></a></li>
						<li><a href="#"><b>永康</b></a></li>
						<li><a href="#"><b>余杭</b></a></li>
						<li><a href="#"><b>阳朔</b></a></li>
						<li><a href="#"><b>偃师</b></a></li>
						<li><a href="#"><b>伊川</b></a></li>
						<li><a href="#"><b>宜阳</b></a></li>
						<li><a href="#"><b>鄢陵</b></a></li>
					</ul>
					</li>
					<li class="city-list clearfix">
					<span class="letter">
						Z
					</span>
					<ul class="list-inline">
						<li><a href="#"><b>张家口</b></a></li>
						<li><a href="#"><b>镇江</b></a></li>
						<li><a href="#"><b>舟山</b></a></li>
						<li><a href="#"><b>漳州</b></a></li>
						<li><a href="#"><b>淄博</b></a></li>
						<li><a href="#"><b>枣庄</b></a></li>
						<li><a href="#"><b>郑州</b></a></li>
						<li><a href="#"><b>周口</b></a></li>
						<li><a href="#"><b>驻马店</b></a></li>
						<li><a href="#"><b>株洲</b></a></li>
						<li><a href="#"><b>珠海</b></a></li>
						<li><a href="#"><b>湛江</b></a></li>
						<li><a href="#"><b>肇庆</b></a></li>
						<li><a href="#"><b>中山</b></a></li>
						<li><a href="#"><b>自贡</b></a></li>
						<li><a href="#"><b>遵义</b></a></li>
						<li><a href="#">昭通</a></li>
						<li><a href="#">张掖</a></li>
						<li><a href="#"><b>张家界</b></a></li>
						<li><a href="#">中卫</a></li>
						<li><a href="#">资阳</a></li>
						<li><a href="#">涿州</a></li>
						<li><a href="#"><b>诸暨</b></a></li>
						<li><a href="#"><b>张家港</b></a></li>
						<li><a href="#"><b>章丘</b></a></li>
						<li><a href="#"><b>招远</b></a></li>
						<li><a href="#"><b>中牟</b></a></li>
						<li><a href="#"><b>镇平</b></a></li>
					</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<script src="http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js"></script>
<script type="text/javascript">

$(document).ready(function(){
	$('a').each(function(){
		if (null != $(this).html().match(remote_ip_info.city)) {
			$('a#u_city').html($(this).html());
			$('a#u_city').attr('href', $(this).attr('href'));
		}
	});
	if ('hiici.com' == location.hostname) location = $('a#u_city').attr('href'); 
	$('div.forum_city_choice').find('a[href=#]').css('color','#999');
});

</script>
