<style type="text/css">
	.floor-1 {
		padding:100px 0;
		height:700px;
		background-color:#d2e39f;
	}
	.ui-img {
		-webkit-box-shadow: 0 1px 1px rgba(0,0,0,.07);
		box-shadow: 0 0px 19px rgba(0,0,0,.47);
	}
	.floor-2 {
		padding:100px 0;
		height:600px;
		background-color:#fdfbc0;
	}
	.floor-3 {
		padding:100px 0;
		height:600px;
		background-color:#fff;
	}
	.floor-4 {
		padding:70px 0;
		height:650px;
		background-color:#a7d7f1;
	}
	.floor-5 {
		padding:100px 0;
		height:600px;
		background-color:#d2e39f;
	}
	.floor-6 {
		padding:100px 0;
		height:600px;
		background-color:#fbde80;
	}
	.floor-7 {
		padding:100px 0;
		height:600px;
	}
</style>
<div class="floor-1">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<img class="ui-img" src="img/index/open_source/20140810135809.jpg">
			</div>
			<div class="col-md-5" style="padding-top:30px">
				<h3><b> HIICI多功能建站系统 </b></h3>
				<h4> <a href="http://www.hiici.com">衡阳搜索HIICI</a>，社交型商城系统。</h4>
				<h4> 简单，高效。 <a target="_blank" href="http://shang.qq.com/wpa/qunwpa?idkey=f52c11973b2fff0ad93139f5d21f0a34e52400ccd98a5f3eed049513047e3dfc"><img border="0" src="http://pub.idqqimg.com/wpa/images/group.png" alt="hiici站长群" title="hiici站长群"></a></h4>
				<p><img src="http://qr.liantu.com/api.php?bg=ffffff&fg=111111&el=l&w=200&m=5&text=<?php echo 'http://'.$_SERVER['HTTP_HOST'] ?>"/></p>
				<a class="btn btn-danger btn-lg" href="http://git.oschina.net/hiici/hiici" style="margin-top:20px"> 下 载 源 码 </a>
			</div>
		</div>
	</div>
</div>
<div class="floor-2">
	<div class="container">
		<div class="row">
			<div class="col-md-5" style="padding-top:50px">
				<h3><b> 项目列表 </b></h3>
				<h4> 多种筛选模式，类别筛选、期限筛选、状态筛选。 </h4>
				<h4> 自动生成标签。 </h4>
			</div>
			<div class="col-md-7">
				<img class="ui-img" src="img/index/open_source/20140810133955.jpg">
			</div>
		</div>
	</div>
</div>
<div class="floor-3">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<img class="ui-img" src="img/index/open_source/20140810134350.jpg">
			</div>
			<div class="col-md-5" style="padding-top:50px">
				<h3><b> 项目详情 </b></h3>
				<h4> 项目信息、主体信息、风险控制、相关资料、投标情况。 </h4>
				<h4> 管理员统一管理。 </h4>
			</div>
		</div>
	</div>
</div>
<div class="floor-4">
	<div class="container">
		<div class="row">
			<div class="col-md-5" style="padding-top:50px">
				<h3><b> 社区系统 </b></h3>
				<h4> 无限量自由板块创建，不同名则可创建。 </h4>
				<h4> 板块创建者拥有唯一管理权。 </h4>
				<h4> 首页显示最新最热。 </h4>
			</div>
			<div class="col-md-7">
				<img class="ui-img" src="img/index/open_source/20140810150838.jpg">
			</div>
		</div>
	</div>
</div>
<div class="floor-5">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<img class="ui-img" src="img/index/open_source/20140810134207.jpg">
			</div>
			<div class="col-md-5" style="padding-top:50px">
				<h3><b> 空间系统 </b></h3>
				<h4> 访问量统计，说说功能，日志功能，关注功能，私信功能。 </h4>
				<h4> AJAX无刷新加载。 </h4>
				<h4> 二维码入口。 </h4>
			</div>
		</div>
	</div>
</div>
<div class="floor-6">
	<div class="container">
		<div class="row">
			<div class="col-md-6" style="padding-top:50px">
				<h3><b> 手机访问 </b></h3>
				<h4> bootstrap自适应手机、平板、桌面。 </h4>
				<h4> 移动访问无压力。 </h4>
			</div>
			<div class="col-md-6">
				<img class="ui-img" src="img/index/open_source/20140810134440.jpg">
			</div>
		</div>
	</div>
</div>
<div class="floor-7">
	<div class="container">
		<div class="row">
			<center>
				<p><img src="http://qr.liantu.com/api.php?bg=ffffff&fg=111111&el=l&w=200&m=5&text=<?php echo 'http://'.$_SERVER['HTTP_HOST'] ?>"/></p>
				<h3><b> 更多功能在HIICI多功能建站系统 </b></h3>
				<a class="btn btn-danger btn-lg" href="http://git.oschina.net/hiici/hiici" style="margin-top:20px"> 下 载 源 码 </a>
			</center>
		</div>
	</div>
</div>
