<?php
/*
 * 数据来源：
 * http://www.geonames.org/export/
 * http://www.ip2location.com/free/country-multilingual
 */

/*
Antarctica / 南极洲 / no Capital_latlng /
Bonaire, Saint Eustatius and Saba  / 荷兰加勒比区 / no Capital_latlng /
Bouvet Island / 布韦岛 / no Capital_latlng /
Curacao / 库拉索岛 / no Capital_latlng /
Heard Island and McDonald Islands / 赫德岛和麦克唐纳群岛 / no Capital_latlng /
Isle of Man / 马恩岛 / no Capital_latlng /
British Indian Ocean Territory / 英属印度洋领地 / no Capital_latlng /
Nauru / 瑙鲁 / no Capital_latlng /
Tokelau / 托克劳群岛 / no Capital_latlng /
United States Minor Outlying Islands / 美国本土外小岛屿 / no Capital_latlng /
Serbia and Montenegro /  / no Capital_latlng /
 */

$country=array (
  0 => 
  array (
    'iso' => 'AD',
    'iso3' => 'AND',
    'iso_num' => '020',
    'country' => 'Andorra',
    'capital' => 'Andorra la Vella',
    'continent' => 'EU',
    'country_zh_cn' => '安道尔',
    'latitude' => '42.50779',
    'longitude' => '1.52109',
    'capital_latlng' => 1,
  ),
  1 => 
  array (
    'iso' => 'AE',
    'iso3' => 'ARE',
    'iso_num' => '784',
    'country' => 'United Arab Emirates',
    'capital' => 'Abu Dhabi',
    'continent' => 'AS',
    'country_zh_cn' => '阿联酋',
    'latitude' => '24.46667',
    'longitude' => '54.36667',
    'capital_latlng' => 1,
  ),
  2 => 
  array (
    'iso' => 'AF',
    'iso3' => 'AFG',
    'iso_num' => '004',
    'country' => 'Afghanistan',
    'capital' => 'Kabul',
    'continent' => 'AS',
    'country_zh_cn' => '阿富汗',
    'latitude' => '34.52813',
    'longitude' => '69.17233',
    'capital_latlng' => 1,
  ),
  3 => 
  array (
    'iso' => 'AG',
    'iso3' => 'ATG',
    'iso_num' => '028',
    'country' => 'Antigua and Barbuda',
    'capital' => 'St. John\'s',
    'continent' => 'NA',
    'country_zh_cn' => '安提瓜和巴布达',
    'latitude' => '17.11717',
    'longitude' => '-61.84573',
    'capital_latlng' => 1,
  ),
  4 => 
  array (
    'iso' => 'AI',
    'iso3' => 'AIA',
    'iso_num' => '660',
    'country' => 'Anguilla',
    'capital' => 'The Valley',
    'continent' => 'NA',
    'country_zh_cn' => '安圭拉',
    'latitude' => '18.21704',
    'longitude' => '-63.05783',
    'capital_latlng' => 1,
  ),
  5 => 
  array (
    'iso' => 'AL',
    'iso3' => 'ALB',
    'iso_num' => '008',
    'country' => 'Albania',
    'capital' => 'Tirana',
    'continent' => 'EU',
    'country_zh_cn' => '阿尔巴尼亚',
    'latitude' => '41.3275',
    'longitude' => '19.81889',
    'capital_latlng' => 1,
  ),
  6 => 
  array (
    'iso' => 'AM',
    'iso3' => 'ARM',
    'iso_num' => '051',
    'country' => 'Armenia',
    'capital' => 'Yerevan',
    'continent' => 'AS',
    'country_zh_cn' => '亚美尼亚',
    'latitude' => '40.18111',
    'longitude' => '44.51361',
    'capital_latlng' => 1,
  ),
  7 => 
  array (
    'iso' => 'AO',
    'iso3' => 'AGO',
    'iso_num' => '024',
    'country' => 'Angola',
    'capital' => 'Luanda',
    'continent' => 'AF',
    'country_zh_cn' => '安哥拉',
    'latitude' => '-8.83682',
    'longitude' => '13.23432',
    'capital_latlng' => 1,
  ),
  8 => 
  array (
    'iso' => 'AQ',
    'iso3' => 'ATA',
    'iso_num' => '010',
    'country' => 'Antarctica',
    'capital' => '',
    'continent' => 'AN',
    'country_zh_cn' => '南极洲',
  ),
  9 => 
  array (
    'iso' => 'AR',
    'iso3' => 'ARG',
    'iso_num' => '032',
    'country' => 'Argentina',
    'capital' => 'Buenos Aires',
    'continent' => 'SA',
    'country_zh_cn' => '阿根廷',
    'latitude' => '-34.61315',
    'longitude' => '-58.37723',
    'capital_latlng' => 1,
  ),
  10 => 
  array (
    'iso' => 'AS',
    'iso3' => 'ASM',
    'iso_num' => '016',
    'country' => 'American Samoa',
    'capital' => 'Pago Pago',
    'continent' => 'OC',
    'country_zh_cn' => '美属萨摩亚',
    'latitude' => '-14.27806',
    'longitude' => '-170.7025',
    'capital_latlng' => 1,
  ),
  11 => 
  array (
    'iso' => 'AT',
    'iso3' => 'AUT',
    'iso_num' => '040',
    'country' => 'Austria',
    'capital' => 'Vienna',
    'continent' => 'EU',
    'country_zh_cn' => '奥地利',
    'latitude' => '48.20849',
    'longitude' => '16.37208',
    'capital_latlng' => 1,
  ),
  12 => 
  array (
    'iso' => 'AU',
    'iso3' => 'AUS',
    'iso_num' => '036',
    'country' => 'Australia',
    'capital' => 'Canberra',
    'continent' => 'OC',
    'country_zh_cn' => '澳大利亚',
    'latitude' => '-35.28346',
    'longitude' => '149.12807',
    'capital_latlng' => 1,
  ),
  13 => 
  array (
    'iso' => 'AW',
    'iso3' => 'ABW',
    'iso_num' => '533',
    'country' => 'Aruba',
    'capital' => 'Oranjestad',
    'continent' => 'NA',
    'country_zh_cn' => '阿鲁巴',
    'latitude' => '12.52398',
    'longitude' => '-70.02703',
    'capital_latlng' => 1,
  ),
  14 => 
  array (
    'iso' => 'AX',
    'iso3' => 'ALA',
    'iso_num' => '248',
    'country' => 'Aland Islands',
    'capital' => 'Mariehamn',
    'continent' => 'EU',
    'country_zh_cn' => '奥兰群岛',
    'latitude' => '60.09726',
    'longitude' => '19.93481',
    'capital_latlng' => 1,
  ),
  15 => 
  array (
    'iso' => 'AZ',
    'iso3' => 'AZE',
    'iso_num' => '031',
    'country' => 'Azerbaijan',
    'capital' => 'Baku',
    'continent' => 'AS',
    'country_zh_cn' => '阿塞拜疆',
    'latitude' => '40.37767',
    'longitude' => '49.89201',
    'capital_latlng' => 1,
  ),
  16 => 
  array (
    'iso' => 'BA',
    'iso3' => 'BIH',
    'iso_num' => '070',
    'country' => 'Bosnia and Herzegovina',
    'capital' => 'Sarajevo',
    'continent' => 'EU',
    'country_zh_cn' => '波黑',
    'latitude' => '43.84864',
    'longitude' => '18.35644',
    'capital_latlng' => 1,
  ),
  17 => 
  array (
    'iso' => 'BB',
    'iso3' => 'BRB',
    'iso_num' => '052',
    'country' => 'Barbados',
    'capital' => 'Bridgetown',
    'continent' => 'NA',
    'country_zh_cn' => '巴巴多斯',
    'latitude' => '13.1',
    'longitude' => '-59.61667',
    'capital_latlng' => 1,
  ),
  18 => 
  array (
    'iso' => 'BD',
    'iso3' => 'BGD',
    'iso_num' => '050',
    'country' => 'Bangladesh',
    'capital' => 'Dhaka',
    'continent' => 'AS',
    'country_zh_cn' => '孟加拉',
    'latitude' => '23.7104',
    'longitude' => '90.40744',
    'capital_latlng' => 1,
  ),
  19 => 
  array (
    'iso' => 'BE',
    'iso3' => 'BEL',
    'iso_num' => '056',
    'country' => 'Belgium',
    'capital' => 'Brussels',
    'continent' => 'EU',
    'country_zh_cn' => '比利时',
    'latitude' => '50.85045',
    'longitude' => '4.34878',
    'capital_latlng' => 1,
  ),
  20 => 
  array (
    'iso' => 'BF',
    'iso3' => 'BFA',
    'iso_num' => '854',
    'country' => 'Burkina Faso',
    'capital' => 'Ouagadougou',
    'continent' => 'AF',
    'country_zh_cn' => '布基纳法索',
    'latitude' => '12.36566',
    'longitude' => '-1.53388',
    'capital_latlng' => 1,
  ),
  21 => 
  array (
    'iso' => 'BG',
    'iso3' => 'BGR',
    'iso_num' => '100',
    'country' => 'Bulgaria',
    'capital' => 'Sofia',
    'continent' => 'EU',
    'country_zh_cn' => '保加利亚',
    'latitude' => '42.69751',
    'longitude' => '23.32415',
    'capital_latlng' => 1,
  ),
  22 => 
  array (
    'iso' => 'BH',
    'iso3' => 'BHR',
    'iso_num' => '048',
    'country' => 'Bahrain',
    'capital' => 'Manama',
    'continent' => 'AS',
    'country_zh_cn' => '巴林',
    'latitude' => '26.21536',
    'longitude' => '50.5832',
    'capital_latlng' => 1,
  ),
  23 => 
  array (
    'iso' => 'BI',
    'iso3' => 'BDI',
    'iso_num' => '108',
    'country' => 'Burundi',
    'capital' => 'Bujumbura',
    'continent' => 'AF',
    'country_zh_cn' => '布隆迪',
    'latitude' => '-3.3822',
    'longitude' => '29.3644',
    'capital_latlng' => 1,
  ),
  24 => 
  array (
    'iso' => 'BJ',
    'iso3' => 'BEN',
    'iso_num' => '204',
    'country' => 'Benin',
    'capital' => 'Porto-Novo',
    'continent' => 'AF',
    'country_zh_cn' => '贝宁',
    'latitude' => '6.49646',
    'longitude' => '2.60359',
    'capital_latlng' => 1,
  ),
  25 => 
  array (
    'iso' => 'BL',
    'iso3' => 'BLM',
    'iso_num' => '652',
    'country' => 'Saint Barthelemy',
    'capital' => 'Gustavia',
    'continent' => 'NA',
    'country_zh_cn' => '圣巴泰勒米岛',
    'latitude' => '17.89618',
    'longitude' => '-62.84978',
    'capital_latlng' => 1,
  ),
  26 => 
  array (
    'iso' => 'BM',
    'iso3' => 'BMU',
    'iso_num' => '060',
    'country' => 'Bermuda',
    'capital' => 'Hamilton',
    'continent' => 'NA',
    'country_zh_cn' => '百慕大',
    'latitude' => '32.2949',
    'longitude' => '-64.78303',
    'capital_latlng' => 1,
  ),
  27 => 
  array (
    'iso' => 'BN',
    'iso3' => 'BRN',
    'iso_num' => '096',
    'country' => 'Brunei',
    'capital' => 'Bandar Seri Begawan',
    'continent' => 'AS',
    'country_zh_cn' => '文莱',
    'latitude' => '4.94029',
    'longitude' => '114.94806',
    'capital_latlng' => 1,
  ),
  28 => 
  array (
    'iso' => 'BO',
    'iso3' => 'BOL',
    'iso_num' => '068',
    'country' => 'Bolivia',
    'capital' => 'Sucre',
    'continent' => 'SA',
    'country_zh_cn' => '玻利维亚',
    'latitude' => '-19.03332',
    'longitude' => '-65.26274',
    'capital_latlng' => 1,
  ),
  29 => 
  array (
    'iso' => 'BQ',
    'iso3' => 'BES',
    'iso_num' => '535',
    'country' => 'Bonaire, Saint Eustatius and Saba ',
    'capital' => '',
    'continent' => 'NA',
    'country_zh_cn' => '荷兰加勒比区',
  ),
  30 => 
  array (
    'iso' => 'BR',
    'iso3' => 'BRA',
    'iso_num' => '076',
    'country' => 'Brazil',
    'capital' => 'Brasilia',
    'continent' => 'SA',
    'country_zh_cn' => '巴西',
    'latitude' => '-15.77972',
    'longitude' => '-47.92972',
    'capital_latlng' => 1,
  ),
  31 => 
  array (
    'iso' => 'BS',
    'iso3' => 'BHS',
    'iso_num' => '044',
    'country' => 'Bahamas',
    'capital' => 'Nassau',
    'continent' => 'NA',
    'country_zh_cn' => '巴哈马',
    'latitude' => '25.05823',
    'longitude' => '-77.34306',
    'capital_latlng' => 1,
  ),
  32 => 
  array (
    'iso' => 'BT',
    'iso3' => 'BTN',
    'iso_num' => '064',
    'country' => 'Bhutan',
    'capital' => 'Thimphu',
    'continent' => 'AS',
    'country_zh_cn' => '不丹',
    'latitude' => '27.46609',
    'longitude' => '89.64191',
    'capital_latlng' => 1,
  ),
  33 => 
  array (
    'iso' => 'BV',
    'iso3' => 'BVT',
    'iso_num' => '074',
    'country' => 'Bouvet Island',
    'capital' => '',
    'continent' => 'AN',
    'country_zh_cn' => '布韦岛',
  ),
  34 => 
  array (
    'iso' => 'BW',
    'iso3' => 'BWA',
    'iso_num' => '072',
    'country' => 'Botswana',
    'capital' => 'Gaborone',
    'continent' => 'AF',
    'country_zh_cn' => '博茨瓦纳',
    'latitude' => '-24.65451',
    'longitude' => '25.90859',
    'capital_latlng' => 1,
  ),
  35 => 
  array (
    'iso' => 'BY',
    'iso3' => 'BLR',
    'iso_num' => '112',
    'country' => 'Belarus',
    'capital' => 'Minsk',
    'continent' => 'EU',
    'country_zh_cn' => '白俄罗斯',
    'latitude' => '53.9',
    'longitude' => '27.56667',
    'capital_latlng' => 1,
  ),
  36 => 
  array (
    'iso' => 'BZ',
    'iso3' => 'BLZ',
    'iso_num' => '084',
    'country' => 'Belize',
    'capital' => 'Belmopan',
    'continent' => 'NA',
    'country_zh_cn' => '伯利兹',
    'latitude' => '17.25',
    'longitude' => '-88.76667',
    'capital_latlng' => 1,
  ),
  37 => 
  array (
    'iso' => 'CA',
    'iso3' => 'CAN',
    'iso_num' => '124',
    'country' => 'Canada',
    'capital' => 'Ottawa',
    'continent' => 'NA',
    'country_zh_cn' => '加拿大',
    'latitude' => '45.41117',
    'longitude' => '-75.69812',
    'capital_latlng' => 1,
  ),
  38 => 
  array (
    'iso' => 'CC',
    'iso3' => 'CCK',
    'iso_num' => '166',
    'country' => 'Cocos Islands',
    'capital' => 'West Island',
    'continent' => 'AS',
    'country_zh_cn' => '科科斯群岛',
    'latitude' => '-12.15681',
    'longitude' => '96.82251',
    'capital_latlng' => 1,
  ),
  39 => 
  array (
    'iso' => 'CD',
    'iso3' => 'COD',
    'iso_num' => '180',
    'country' => 'Democratic Republic of the Congo',
    'capital' => 'Kinshasa',
    'continent' => 'AF',
    'country_zh_cn' => '刚果民主共和国',
    'latitude' => '-4.32758',
    'longitude' => '15.31357',
    'capital_latlng' => 1,
  ),
  40 => 
  array (
    'iso' => 'CF',
    'iso3' => 'CAF',
    'iso_num' => '140',
    'country' => 'Central African Republic',
    'capital' => 'Bangui',
    'continent' => 'AF',
    'country_zh_cn' => '中非',
    'latitude' => '4.36122',
    'longitude' => '18.55496',
    'capital_latlng' => 1,
  ),
  41 => 
  array (
    'iso' => 'CG',
    'iso3' => 'COG',
    'iso_num' => '178',
    'country' => 'Republic of the Congo',
    'capital' => 'Brazzaville',
    'continent' => 'AF',
    'country_zh_cn' => '刚果共和国',
    'latitude' => '-4.26613',
    'longitude' => '15.28318',
    'capital_latlng' => 1,
  ),
  42 => 
  array (
    'iso' => 'CH',
    'iso3' => 'CHE',
    'iso_num' => '756',
    'country' => 'Switzerland',
    'capital' => 'Berne',
    'continent' => 'EU',
    'country_zh_cn' => '瑞士',
    'latitude' => '46.94809',
    'longitude' => '7.44744',
    'capital_latlng' => 1,
  ),
  43 => 
  array (
    'iso' => 'CI',
    'iso3' => 'CIV',
    'iso_num' => '384',
    'country' => 'Ivory Coast',
    'capital' => 'Yamoussoukro',
    'continent' => 'AF',
    'country_zh_cn' => '科特迪瓦',
    'latitude' => '6.82055',
    'longitude' => '-5.27674',
    'capital_latlng' => 1,
  ),
  44 => 
  array (
    'iso' => 'CK',
    'iso3' => 'COK',
    'iso_num' => '184',
    'country' => 'Cook Islands',
    'capital' => 'Avarua',
    'continent' => 'OC',
    'country_zh_cn' => '库克群岛',
    'latitude' => '-21.20778',
    'longitude' => '-159.775',
    'capital_latlng' => 1,
  ),
  45 => 
  array (
    'iso' => 'CL',
    'iso3' => 'CHL',
    'iso_num' => '152',
    'country' => 'Chile',
    'capital' => 'Santiago',
    'continent' => 'SA',
    'country_zh_cn' => '智利',
    'latitude' => '-29.19167',
    'longitude' => '-54.86722',
    'capital_latlng' => 1,
  ),
  46 => 
  array (
    'iso' => 'CM',
    'iso3' => 'CMR',
    'iso_num' => '120',
    'country' => 'Cameroon',
    'capital' => 'Yaounde',
    'continent' => 'AF',
    'country_zh_cn' => '喀麦隆',
    'latitude' => '3.86667',
    'longitude' => '11.51667',
    'capital_latlng' => 1,
  ),
  47 => 
  array (
    'iso' => 'CN',
    'iso3' => 'CHN',
    'iso_num' => '156',
    'country' => 'China',
    'capital' => 'Beijing',
    'continent' => 'AS',
    'country_zh_cn' => '中国',
    'latitude' => '39.9075',
    'longitude' => '116.39723',
    'capital_latlng' => 1,
  ),
  48 => 
  array (
    'iso' => 'CO',
    'iso3' => 'COL',
    'iso_num' => '170',
    'country' => 'Colombia',
    'capital' => 'Bogota',
    'continent' => 'SA',
    'country_zh_cn' => '哥伦比亚',
    'latitude' => '4.60971',
    'longitude' => '-74.08175',
    'capital_latlng' => 1,
  ),
  49 => 
  array (
    'iso' => 'CR',
    'iso3' => 'CRI',
    'iso_num' => '188',
    'country' => 'Costa Rica',
    'capital' => 'San Jose',
    'continent' => 'NA',
    'country_zh_cn' => '哥斯达黎加',
    'latitude' => '10.95173',
    'longitude' => '-85.1361',
    'capital_latlng' => 1,
  ),
  50 => 
  array (
    'iso' => 'CU',
    'iso3' => 'CUB',
    'iso_num' => '192',
    'country' => 'Cuba',
    'capital' => 'Havana',
    'continent' => 'NA',
    'country_zh_cn' => '古巴',
    'latitude' => '23.13302',
    'longitude' => '-82.38304',
    'capital_latlng' => 1,
  ),
  51 => 
  array (
    'iso' => 'CV',
    'iso3' => 'CPV',
    'iso_num' => '132',
    'country' => 'Cape Verde',
    'capital' => 'Praia',
    'continent' => 'AF',
    'country_zh_cn' => '佛得角',
    'latitude' => '14.93152',
    'longitude' => '-23.51254',
    'capital_latlng' => 1,
  ),
  52 => 
  array (
    'iso' => 'CW',
    'iso3' => 'CUW',
    'iso_num' => '531',
    'country' => 'Curacao',
    'capital' => ' Willemstad',
    'continent' => 'NA',
    'country_zh_cn' => '库拉索岛',
  ),
  53 => 
  array (
    'iso' => 'CX',
    'iso3' => 'CXR',
    'iso_num' => '162',
    'country' => 'Christmas Island',
    'capital' => 'Flying Fish Cove',
    'continent' => 'AS',
    'country_zh_cn' => '圣诞岛',
    'latitude' => '-10.42172',
    'longitude' => '105.67912',
    'capital_latlng' => 1,
  ),
  54 => 
  array (
    'iso' => 'CY',
    'iso3' => 'CYP',
    'iso_num' => '196',
    'country' => 'Cyprus',
    'capital' => 'Nicosia',
    'continent' => 'EU',
    'country_zh_cn' => '塞浦路斯',
    'latitude' => '35.17531',
    'longitude' => '33.3642',
    'capital_latlng' => 1,
  ),
  55 => 
  array (
    'iso' => 'CZ',
    'iso3' => 'CZE',
    'iso_num' => '203',
    'country' => 'Czech Republic',
    'capital' => 'Prague',
    'continent' => 'EU',
    'country_zh_cn' => '捷克',
    'latitude' => '50.08804',
    'longitude' => '14.42076',
    'capital_latlng' => 1,
  ),
  56 => 
  array (
    'iso' => 'DE',
    'iso3' => 'DEU',
    'iso_num' => '276',
    'country' => 'Germany',
    'capital' => 'Berlin',
    'continent' => 'EU',
    'country_zh_cn' => '德国',
    'latitude' => '52.52437',
    'longitude' => '13.41053',
    'capital_latlng' => 1,
  ),
  57 => 
  array (
    'iso' => 'DJ',
    'iso3' => 'DJI',
    'iso_num' => '262',
    'country' => 'Djibouti',
    'capital' => 'Djibouti',
    'continent' => 'AF',
    'country_zh_cn' => '吉布提',
    'latitude' => '11.58901',
    'longitude' => '43.14503',
    'capital_latlng' => 1,
  ),
  58 => 
  array (
    'iso' => 'DK',
    'iso3' => 'DNK',
    'iso_num' => '208',
    'country' => 'Denmark',
    'capital' => 'Copenhagen',
    'continent' => 'EU',
    'country_zh_cn' => '丹麦',
    'latitude' => '55.67594',
    'longitude' => '12.56553',
    'capital_latlng' => 1,
  ),
  59 => 
  array (
    'iso' => 'DM',
    'iso3' => 'DMA',
    'iso_num' => '212',
    'country' => 'Dominica',
    'capital' => 'Roseau',
    'continent' => 'NA',
    'country_zh_cn' => '多米尼克',
    'latitude' => '15.30174',
    'longitude' => '-61.38808',
    'capital_latlng' => 1,
  ),
  60 => 
  array (
    'iso' => 'DO',
    'iso3' => 'DOM',
    'iso_num' => '214',
    'country' => 'Dominican Republic',
    'capital' => 'Santo Domingo',
    'continent' => 'NA',
    'country_zh_cn' => '多米尼加',
    'latitude' => '22.58667',
    'longitude' => '-80.24361',
    'capital_latlng' => 1,
  ),
  61 => 
  array (
    'iso' => 'DZ',
    'iso3' => 'DZA',
    'iso_num' => '012',
    'country' => 'Algeria',
    'capital' => 'Algiers',
    'continent' => 'AF',
    'country_zh_cn' => '阿尔及利亚',
    'latitude' => '36.7525',
    'longitude' => '3.04197',
    'capital_latlng' => 1,
  ),
  62 => 
  array (
    'iso' => 'EC',
    'iso3' => 'ECU',
    'iso_num' => '218',
    'country' => 'Ecuador',
    'capital' => 'Quito',
    'continent' => 'SA',
    'country_zh_cn' => '厄瓜多尔',
    'latitude' => '-0.22985',
    'longitude' => '-78.52495',
    'capital_latlng' => 1,
  ),
  63 => 
  array (
    'iso' => 'EE',
    'iso3' => 'EST',
    'iso_num' => '233',
    'country' => 'Estonia',
    'capital' => 'Tallinn',
    'continent' => 'EU',
    'country_zh_cn' => '爱沙尼亚',
    'latitude' => '59.43696',
    'longitude' => '24.75353',
    'capital_latlng' => 1,
  ),
  64 => 
  array (
    'iso' => 'EG',
    'iso3' => 'EGY',
    'iso_num' => '818',
    'country' => 'Egypt',
    'capital' => 'Cairo',
    'continent' => 'AF',
    'country_zh_cn' => '埃及',
    'latitude' => '30.06263',
    'longitude' => '31.24967',
    'capital_latlng' => 1,
  ),
  65 => 
  array (
    'iso' => 'EH',
    'iso3' => 'ESH',
    'iso_num' => '732',
    'country' => 'Western Sahara',
    'capital' => 'El-Aaiun',
    'continent' => 'AF',
    'country_zh_cn' => '西撒哈拉',
    'latitude' => '27.1418',
    'longitude' => '-13.18797',
    'capital_latlng' => 1,
  ),
  66 => 
  array (
    'iso' => 'ER',
    'iso3' => 'ERI',
    'iso_num' => '232',
    'country' => 'Eritrea',
    'capital' => 'Asmara',
    'continent' => 'AF',
    'country_zh_cn' => '厄立特里亚',
    'latitude' => '26.73841',
    'longitude' => '-11.67194',
    'capital_latlng' => 1,
  ),
  67 => 
  array (
    'iso' => 'ES',
    'iso3' => 'ESP',
    'iso_num' => '724',
    'country' => 'Spain',
    'capital' => 'Madrid',
    'continent' => 'EU',
    'country_zh_cn' => '西班牙',
    'latitude' => '4.73245',
    'longitude' => '-74.26419',
    'capital_latlng' => 1,
  ),
  68 => 
  array (
    'iso' => 'ET',
    'iso3' => 'ETH',
    'iso_num' => '231',
    'country' => 'Ethiopia',
    'capital' => 'Addis Ababa',
    'continent' => 'AF',
    'country_zh_cn' => '埃塞俄比亚',
    'latitude' => '9.02497',
    'longitude' => '38.74689',
    'capital_latlng' => 1,
  ),
  69 => 
  array (
    'iso' => 'FI',
    'iso3' => 'FIN',
    'iso_num' => '246',
    'country' => 'Finland',
    'capital' => 'Helsinki',
    'continent' => 'EU',
    'country_zh_cn' => '芬兰',
    'latitude' => '60.16952',
    'longitude' => '24.93545',
    'capital_latlng' => 1,
  ),
  70 => 
  array (
    'iso' => 'FJ',
    'iso3' => 'FJI',
    'iso_num' => '242',
    'country' => 'Fiji',
    'capital' => 'Suva',
    'continent' => 'OC',
    'country_zh_cn' => '斐济',
    'latitude' => '-18.14161',
    'longitude' => '178.44149',
    'capital_latlng' => 1,
  ),
  71 => 
  array (
    'iso' => 'FK',
    'iso3' => 'FLK',
    'iso_num' => '238',
    'country' => 'Falkland Islands',
    'capital' => 'Stanley',
    'continent' => 'SA',
    'country_zh_cn' => '福克兰群岛',
    'latitude' => '-51.7',
    'longitude' => '-57.85',
    'capital_latlng' => 1,
  ),
  72 => 
  array (
    'iso' => 'FM',
    'iso3' => 'FSM',
    'iso_num' => '583',
    'country' => 'Micronesia',
    'capital' => 'Palikir',
    'continent' => 'OC',
    'country_zh_cn' => '密克罗尼西亚联邦',
    'latitude' => '6.92477',
    'longitude' => '158.16109',
    'capital_latlng' => 1,
  ),
  73 => 
  array (
    'iso' => 'FO',
    'iso3' => 'FRO',
    'iso_num' => '234',
    'country' => 'Faroe Islands',
    'capital' => 'Torshavn',
    'continent' => 'EU',
    'country_zh_cn' => '法罗群岛',
    'latitude' => '62.00973',
    'longitude' => '-6.77164',
    'capital_latlng' => 1,
  ),
  74 => 
  array (
    'iso' => 'FR',
    'iso3' => 'FRA',
    'iso_num' => '250',
    'country' => 'France',
    'capital' => 'Paris',
    'continent' => 'EU',
    'country_zh_cn' => '法国',
    'latitude' => '48.85341',
    'longitude' => '2.3488',
    'capital_latlng' => 1,
  ),
  75 => 
  array (
    'iso' => 'GA',
    'iso3' => 'GAB',
    'iso_num' => '266',
    'country' => 'Gabon',
    'capital' => 'Libreville',
    'continent' => 'AF',
    'country_zh_cn' => '加蓬',
    'latitude' => '49.76667',
    'longitude' => '4.71667',
    'capital_latlng' => 1,
  ),
  76 => 
  array (
    'iso' => 'GB',
    'iso3' => 'GBR',
    'iso_num' => '826',
    'country' => 'United Kingdom',
    'capital' => 'London',
    'continent' => 'EU',
    'country_zh_cn' => '英国',
    'latitude' => '42.98339',
    'longitude' => '-81.23304',
    'capital_latlng' => 1,
  ),
  77 => 
  array (
    'iso' => 'GD',
    'iso3' => 'GRD',
    'iso_num' => '308',
    'country' => 'Grenada',
    'capital' => 'St. George\'s',
    'continent' => 'NA',
    'country_zh_cn' => '格林纳达',
    'latitude' => '12.05644',
    'longitude' => '-61.74849',
    'capital_latlng' => 1,
  ),
  78 => 
  array (
    'iso' => 'GE',
    'iso3' => 'GEO',
    'iso_num' => '268',
    'country' => 'Georgia',
    'capital' => 'Tbilisi',
    'continent' => 'AS',
    'country_zh_cn' => '格鲁吉亚',
    'latitude' => '41.69411',
    'longitude' => '44.83368',
    'capital_latlng' => 1,
  ),
  79 => 
  array (
    'iso' => 'GF',
    'iso3' => 'GUF',
    'iso_num' => '254',
    'country' => 'French Guiana',
    'capital' => 'Cayenne',
    'continent' => 'SA',
    'country_zh_cn' => '法属圭亚那',
    'latitude' => '4.93333',
    'longitude' => '-52.33333',
    'capital_latlng' => 1,
  ),
  80 => 
  array (
    'iso' => 'GG',
    'iso3' => 'GGY',
    'iso_num' => '831',
    'country' => 'Guernsey',
    'capital' => 'St Peter Port',
    'continent' => 'EU',
    'country_zh_cn' => '根西岛',
    'latitude' => '49.45981',
    'longitude' => '-2.53527',
    'capital_latlng' => 1,
  ),
  81 => 
  array (
    'iso' => 'GH',
    'iso3' => 'GHA',
    'iso_num' => '288',
    'country' => 'Ghana',
    'capital' => 'Accra',
    'continent' => 'AF',
    'country_zh_cn' => '加纳',
    'latitude' => '5.55602',
    'longitude' => '-0.1969',
    'capital_latlng' => 1,
  ),
  82 => 
  array (
    'iso' => 'GI',
    'iso3' => 'GIB',
    'iso_num' => '292',
    'country' => 'Gibraltar',
    'capital' => 'Gibraltar',
    'continent' => 'EU',
    'country_zh_cn' => '直布罗陀',
    'latitude' => '36.14474',
    'longitude' => '-5.35257',
    'capital_latlng' => 1,
  ),
  83 => 
  array (
    'iso' => 'GL',
    'iso3' => 'GRL',
    'iso_num' => '304',
    'country' => 'Greenland',
    'capital' => 'Nuuk',
    'continent' => 'NA',
    'country_zh_cn' => '格陵兰',
    'latitude' => '64.18347',
    'longitude' => '-51.72157',
    'capital_latlng' => 1,
  ),
  84 => 
  array (
    'iso' => 'GM',
    'iso3' => 'GMB',
    'iso_num' => '270',
    'country' => 'Gambia',
    'capital' => 'Banjul',
    'continent' => 'AF',
    'country_zh_cn' => '冈比亚',
    'latitude' => '13.45274',
    'longitude' => '-16.57803',
    'capital_latlng' => 1,
  ),
  85 => 
  array (
    'iso' => 'GN',
    'iso3' => 'GIN',
    'iso_num' => '324',
    'country' => 'Guinea',
    'capital' => 'Conakry',
    'continent' => 'AF',
    'country_zh_cn' => '几内亚',
    'latitude' => '9.53795',
    'longitude' => '-13.67729',
    'capital_latlng' => 1,
  ),
  86 => 
  array (
    'iso' => 'GP',
    'iso3' => 'GLP',
    'iso_num' => '312',
    'country' => 'Guadeloupe',
    'capital' => 'Basse-Terre',
    'continent' => 'NA',
    'country_zh_cn' => '瓜德罗普',
    'latitude' => '15.99854',
    'longitude' => '-61.72548',
    'capital_latlng' => 1,
  ),
  87 => 
  array (
    'iso' => 'GQ',
    'iso3' => 'GNQ',
    'iso_num' => '226',
    'country' => 'Equatorial Guinea',
    'capital' => 'Malabo',
    'continent' => 'AF',
    'country_zh_cn' => '赤道几内亚',
    'latitude' => '3.75',
    'longitude' => '8.78333',
    'capital_latlng' => 1,
  ),
  88 => 
  array (
    'iso' => 'GR',
    'iso3' => 'GRC',
    'iso_num' => '300',
    'country' => 'Greece',
    'capital' => 'Athens',
    'continent' => 'EU',
    'country_zh_cn' => '希腊',
    'latitude' => '37.97945',
    'longitude' => '23.71622',
    'capital_latlng' => 1,
  ),
  89 => 
  array (
    'iso' => 'GS',
    'iso3' => 'SGS',
    'iso_num' => '239',
    'country' => 'South Georgia and the South Sandwich Islands',
    'capital' => 'Grytviken',
    'continent' => 'AN',
    'country_zh_cn' => '南乔治亚岛与南桑威奇群岛',
    'latitude' => '-54.28111',
    'longitude' => '-36.5092',
    'capital_latlng' => 1,
  ),
  90 => 
  array (
    'iso' => 'GT',
    'iso3' => 'GTM',
    'iso_num' => '320',
    'country' => 'Guatemala',
    'capital' => 'Guatemala City',
    'continent' => 'NA',
    'country_zh_cn' => '危地马拉',
    'latitude' => '14.64072',
    'longitude' => '-90.51327',
    'capital_latlng' => 1,
  ),
  91 => 
  array (
    'iso' => 'GU',
    'iso3' => 'GUM',
    'iso_num' => '316',
    'country' => 'Guam',
    'capital' => 'Hagatna',
    'continent' => 'OC',
    'country_zh_cn' => '关岛',
    'latitude' => '13.47567',
    'longitude' => '144.74886',
    'capital_latlng' => 1,
  ),
  92 => 
  array (
    'iso' => 'GW',
    'iso3' => 'GNB',
    'iso_num' => '624',
    'country' => 'Guinea-Bissau',
    'capital' => 'Bissau',
    'continent' => 'AF',
    'country_zh_cn' => '几内亚比绍',
    'latitude' => '11.86357',
    'longitude' => '-15.59767',
    'capital_latlng' => 1,
  ),
  93 => 
  array (
    'iso' => 'GY',
    'iso3' => 'GUY',
    'iso_num' => '328',
    'country' => 'Guyana',
    'capital' => 'Georgetown',
    'continent' => 'SA',
    'country_zh_cn' => '圭亚那',
    'latitude' => '6.80448',
    'longitude' => '-58.15527',
    'capital_latlng' => 1,
  ),
  94 => 
  array (
    'iso' => 'HK',
    'iso3' => 'HKG',
    'iso_num' => '344',
    'country' => 'Hong Kong',
    'capital' => 'Hong Kong',
    'continent' => 'AS',
    'country_zh_cn' => '香港',
    'latitude' => '22.28552',
    'longitude' => '114.15769',
    'capital_latlng' => 1,
  ),
  95 => 
  array (
    'iso' => 'HM',
    'iso3' => 'HMD',
    'iso_num' => '334',
    'country' => 'Heard Island and McDonald Islands',
    'capital' => '',
    'continent' => 'AN',
    'country_zh_cn' => '赫德岛和麦克唐纳群岛',
  ),
  96 => 
  array (
    'iso' => 'HN',
    'iso3' => 'HND',
    'iso_num' => '340',
    'country' => 'Honduras',
    'capital' => 'Tegucigalpa',
    'continent' => 'NA',
    'country_zh_cn' => '洪都拉斯',
    'latitude' => '14.0818',
    'longitude' => '-87.20681',
    'capital_latlng' => 1,
  ),
  97 => 
  array (
    'iso' => 'HR',
    'iso3' => 'HRV',
    'iso_num' => '191',
    'country' => 'Croatia',
    'capital' => 'Zagreb',
    'continent' => 'EU',
    'country_zh_cn' => '克罗地亚',
    'latitude' => '45.81444',
    'longitude' => '15.97798',
    'capital_latlng' => 1,
  ),
  98 => 
  array (
    'iso' => 'HT',
    'iso3' => 'HTI',
    'iso_num' => '332',
    'country' => 'Haiti',
    'capital' => 'Port-au-Prince',
    'continent' => 'NA',
    'country_zh_cn' => '海地',
    'latitude' => '18.53917',
    'longitude' => '-72.335',
    'capital_latlng' => 1,
  ),
  99 => 
  array (
    'iso' => 'HU',
    'iso3' => 'HUN',
    'iso_num' => '348',
    'country' => 'Hungary',
    'capital' => 'Budapest',
    'continent' => 'EU',
    'country_zh_cn' => '匈牙利',
    'latitude' => '47.49801',
    'longitude' => '19.03991',
    'capital_latlng' => 1,
  ),
  100 => 
  array (
    'iso' => 'ID',
    'iso3' => 'IDN',
    'iso_num' => '360',
    'country' => 'Indonesia',
    'capital' => 'Jakarta',
    'continent' => 'AS',
    'country_zh_cn' => '印尼',
    'latitude' => '-6.21462',
    'longitude' => '106.84513',
    'capital_latlng' => 1,
  ),
  101 => 
  array (
    'iso' => 'IE',
    'iso3' => 'IRL',
    'iso_num' => '372',
    'country' => 'Ireland',
    'capital' => 'Dublin',
    'continent' => 'EU',
    'country_zh_cn' => '爱尔兰',
    'latitude' => '53.33306',
    'longitude' => '-6.24889',
    'capital_latlng' => 1,
  ),
  102 => 
  array (
    'iso' => 'IL',
    'iso3' => 'ISR',
    'iso_num' => '376',
    'country' => 'Israel',
    'capital' => 'Jerusalem',
    'continent' => 'AS',
    'country_zh_cn' => '以色列',
    'latitude' => '31.76904',
    'longitude' => '35.21633',
    'capital_latlng' => 1,
  ),
  103 => 
  array (
    'iso' => 'IM',
    'iso3' => 'IMN',
    'iso_num' => '833',
    'country' => 'Isle of Man',
    'capital' => 'Douglas, Isle of Man',
    'continent' => 'EU',
    'country_zh_cn' => '马恩岛',
  ),
  104 => 
  array (
    'iso' => 'IN',
    'iso3' => 'IND',
    'iso_num' => '356',
    'country' => 'India',
    'capital' => 'New Delhi',
    'continent' => 'AS',
    'country_zh_cn' => '印度',
    'latitude' => '28.63576',
    'longitude' => '77.22445',
    'capital_latlng' => 1,
  ),
  105 => 
  array (
    'iso' => 'IO',
    'iso3' => 'IOT',
    'iso_num' => '086',
    'country' => 'British Indian Ocean Territory',
    'capital' => 'Diego Garcia',
    'continent' => 'AS',
    'country_zh_cn' => '英属印度洋领地',
  ),
  106 => 
  array (
    'iso' => 'IQ',
    'iso3' => 'IRQ',
    'iso_num' => '368',
    'country' => 'Iraq',
    'capital' => 'Baghdad',
    'continent' => 'AS',
    'country_zh_cn' => '伊拉克',
    'latitude' => '33.34058',
    'longitude' => '44.40088',
    'capital_latlng' => 1,
  ),
  107 => 
  array (
    'iso' => 'IR',
    'iso3' => 'IRN',
    'iso_num' => '364',
    'country' => 'Iran',
    'capital' => 'Tehran',
    'continent' => 'AS',
    'country_zh_cn' => '伊朗',
    'latitude' => '35.69439',
    'longitude' => '51.42151',
    'capital_latlng' => 1,
  ),
  108 => 
  array (
    'iso' => 'IS',
    'iso3' => 'ISL',
    'iso_num' => '352',
    'country' => 'Iceland',
    'capital' => 'Reykjavik',
    'continent' => 'EU',
    'country_zh_cn' => '冰岛',
    'latitude' => '64.13548',
    'longitude' => '-21.89541',
    'capital_latlng' => 1,
  ),
  109 => 
  array (
    'iso' => 'IT',
    'iso3' => 'ITA',
    'iso_num' => '380',
    'country' => 'Italy',
    'capital' => 'Rome',
    'continent' => 'EU',
    'country_zh_cn' => '意大利',
    'latitude' => '41.89193',
    'longitude' => '12.51133',
    'capital_latlng' => 1,
  ),
  110 => 
  array (
    'iso' => 'JE',
    'iso3' => 'JEY',
    'iso_num' => '832',
    'country' => 'Jersey',
    'capital' => 'Saint Helier',
    'continent' => 'EU',
    'country_zh_cn' => '泽西岛',
    'latitude' => '49.18804',
    'longitude' => '-2.10491',
    'capital_latlng' => 1,
  ),
  111 => 
  array (
    'iso' => 'JM',
    'iso3' => 'JAM',
    'iso_num' => '388',
    'country' => 'Jamaica',
    'capital' => 'Kingston',
    'continent' => 'NA',
    'country_zh_cn' => '牙买加',
    'latitude' => '44.22976',
    'longitude' => '-76.48098',
    'capital_latlng' => 1,
  ),
  112 => 
  array (
    'iso' => 'JO',
    'iso3' => 'JOR',
    'iso_num' => '400',
    'country' => 'Jordan',
    'capital' => 'Amman',
    'continent' => 'AS',
    'country_zh_cn' => '约旦',
    'latitude' => '31.95522',
    'longitude' => '35.94503',
    'capital_latlng' => 1,
  ),
  113 => 
  array (
    'iso' => 'JP',
    'iso3' => 'JPN',
    'iso_num' => '392',
    'country' => 'Japan',
    'capital' => 'Tokyo',
    'continent' => 'AS',
    'country_zh_cn' => '日本',
    'latitude' => '35.6895',
    'longitude' => '139.69171',
    'capital_latlng' => 1,
  ),
  114 => 
  array (
    'iso' => 'KE',
    'iso3' => 'KEN',
    'iso_num' => '404',
    'country' => 'Kenya',
    'capital' => 'Nairobi',
    'continent' => 'AF',
    'country_zh_cn' => '肯尼亚',
    'latitude' => '-1.28333',
    'longitude' => '36.81667',
    'capital_latlng' => 1,
  ),
  115 => 
  array (
    'iso' => 'KG',
    'iso3' => 'KGZ',
    'iso_num' => '417',
    'country' => 'Kyrgyzstan',
    'capital' => 'Bishkek',
    'continent' => 'AS',
    'country_zh_cn' => '吉尔吉斯斯坦',
    'latitude' => '42.87',
    'longitude' => '74.59',
    'capital_latlng' => 1,
  ),
  116 => 
  array (
    'iso' => 'KH',
    'iso3' => 'KHM',
    'iso_num' => '116',
    'country' => 'Cambodia',
    'capital' => 'Phnom Penh',
    'continent' => 'AS',
    'country_zh_cn' => '柬埔寨',
    'latitude' => '11.56245',
    'longitude' => '104.91601',
    'capital_latlng' => 1,
  ),
  117 => 
  array (
    'iso' => 'KI',
    'iso3' => 'KIR',
    'iso_num' => '296',
    'country' => 'Kiribati',
    'capital' => 'Tarawa',
    'continent' => 'OC',
    'country_zh_cn' => '基里巴斯',
    'latitude' => '1.3278',
    'longitude' => '172.97696',
    'capital_latlng' => 1,
  ),
  118 => 
  array (
    'iso' => 'KM',
    'iso3' => 'COM',
    'iso_num' => '174',
    'country' => 'Comoros',
    'capital' => 'Moroni',
    'continent' => 'AF',
    'country_zh_cn' => '科摩罗',
    'latitude' => '-11.70216',
    'longitude' => '43.25506',
    'capital_latlng' => 1,
  ),
  119 => 
  array (
    'iso' => 'KN',
    'iso3' => 'KNA',
    'iso_num' => '659',
    'country' => 'Saint Kitts and Nevis',
    'capital' => 'Basseterre',
    'continent' => 'NA',
    'country_zh_cn' => '圣基茨和尼维斯',
    'latitude' => '17.29484',
    'longitude' => '-62.7261',
    'capital_latlng' => 1,
  ),
  120 => 
  array (
    'iso' => 'KP',
    'iso3' => 'PRK',
    'iso_num' => '408',
    'country' => 'North Korea',
    'capital' => 'Pyongyang',
    'continent' => 'AS',
    'country_zh_cn' => '朝鲜',
    'latitude' => '39.03385',
    'longitude' => '125.75432',
    'capital_latlng' => 1,
  ),
  121 => 
  array (
    'iso' => 'KR',
    'iso3' => 'KOR',
    'iso_num' => '410',
    'country' => 'South Korea',
    'capital' => 'Seoul',
    'continent' => 'AS',
    'country_zh_cn' => '韩国',
    'latitude' => '37.566',
    'longitude' => '126.9784',
    'capital_latlng' => 1,
  ),
  122 => 
  array (
    'iso' => 'XK',
    'iso3' => 'XKX',
    'iso_num' => '0',
    'country' => 'Kosovo',
    'capital' => 'Pristina',
    'continent' => 'EU',
    'country_zh_cn' => '科索沃',
    'latitude' => '42.67272',
    'longitude' => '21.16688',
    'capital_latlng' => 1,
  ),
  123 => 
  array (
    'iso' => 'KW',
    'iso3' => 'KWT',
    'iso_num' => '414',
    'country' => 'Kuwait',
    'capital' => 'Kuwait City',
    'continent' => 'AS',
    'country_zh_cn' => '科威特',
    'latitude' => '29.36972',
    'longitude' => '47.97833',
    'capital_latlng' => 1,
  ),
  124 => 
  array (
    'iso' => 'KY',
    'iso3' => 'CYM',
    'iso_num' => '136',
    'country' => 'Cayman Islands',
    'capital' => 'George Town',
    'continent' => 'NA',
    'country_zh_cn' => '开曼群岛',
    'latitude' => '19.2866',
    'longitude' => '-81.37436',
    'capital_latlng' => 1,
  ),
  125 => 
  array (
    'iso' => 'KZ',
    'iso3' => 'KAZ',
    'iso_num' => '398',
    'country' => 'Kazakhstan',
    'capital' => 'Astana',
    'continent' => 'AS',
    'country_zh_cn' => '哈萨克斯坦',
    'latitude' => '51.1801',
    'longitude' => '71.44598',
    'capital_latlng' => 1,
  ),
  126 => 
  array (
    'iso' => 'LA',
    'iso3' => 'LAO',
    'iso_num' => '418',
    'country' => 'Laos',
    'capital' => 'Vientiane',
    'continent' => 'AS',
    'country_zh_cn' => '老挝',
    'latitude' => '17.96667',
    'longitude' => '102.6',
    'capital_latlng' => 1,
  ),
  127 => 
  array (
    'iso' => 'LB',
    'iso3' => 'LBN',
    'iso_num' => '422',
    'country' => 'Lebanon',
    'capital' => 'Beirut',
    'continent' => 'AS',
    'country_zh_cn' => '黎巴嫩',
    'latitude' => '33.88894',
    'longitude' => '35.49442',
    'capital_latlng' => 1,
  ),
  128 => 
  array (
    'iso' => 'LC',
    'iso3' => 'LCA',
    'iso_num' => '662',
    'country' => 'Saint Lucia',
    'capital' => 'Castries',
    'continent' => 'NA',
    'country_zh_cn' => '圣卢西亚',
    'latitude' => '13.9957',
    'longitude' => '-61.00614',
    'capital_latlng' => 1,
  ),
  129 => 
  array (
    'iso' => 'LI',
    'iso3' => 'LIE',
    'iso_num' => '438',
    'country' => 'Liechtenstein',
    'capital' => 'Vaduz',
    'continent' => 'EU',
    'country_zh_cn' => '列支敦士登',
    'latitude' => '47.14151',
    'longitude' => '9.52154',
    'capital_latlng' => 1,
  ),
  130 => 
  array (
    'iso' => 'LK',
    'iso3' => 'LKA',
    'iso_num' => '144',
    'country' => 'Sri Lanka',
    'capital' => 'Colombo',
    'continent' => 'AS',
    'country_zh_cn' => '斯里兰卡',
    'latitude' => '-25.29167',
    'longitude' => '-49.22417',
    'capital_latlng' => 1,
  ),
  131 => 
  array (
    'iso' => 'LR',
    'iso3' => 'LBR',
    'iso_num' => '430',
    'country' => 'Liberia',
    'capital' => 'Monrovia',
    'continent' => 'AF',
    'country_zh_cn' => '利比里亚',
    'latitude' => '6.30054',
    'longitude' => '-10.7969',
    'capital_latlng' => 1,
  ),
  132 => 
  array (
    'iso' => 'LS',
    'iso3' => 'LSO',
    'iso_num' => '426',
    'country' => 'Lesotho',
    'capital' => 'Maseru',
    'continent' => 'AF',
    'country_zh_cn' => '莱索托',
    'latitude' => '-29.31667',
    'longitude' => '27.48333',
    'capital_latlng' => 1,
  ),
  133 => 
  array (
    'iso' => 'LT',
    'iso3' => 'LTU',
    'iso_num' => '440',
    'country' => 'Lithuania',
    'capital' => 'Vilnius',
    'continent' => 'EU',
    'country_zh_cn' => '立陶宛',
    'latitude' => '54.68916',
    'longitude' => '25.2798',
    'capital_latlng' => 1,
  ),
  134 => 
  array (
    'iso' => 'LU',
    'iso3' => 'LUX',
    'iso_num' => '442',
    'country' => 'Luxembourg',
    'capital' => 'Luxembourg',
    'continent' => 'EU',
    'country_zh_cn' => '卢森堡',
    'latitude' => '49.61167',
    'longitude' => '6.13',
    'capital_latlng' => 1,
  ),
  135 => 
  array (
    'iso' => 'LV',
    'iso3' => 'LVA',
    'iso_num' => '428',
    'country' => 'Latvia',
    'capital' => 'Riga',
    'continent' => 'EU',
    'country_zh_cn' => '拉脱维亚',
    'latitude' => '56.946',
    'longitude' => '24.10589',
    'capital_latlng' => 1,
  ),
  136 => 
  array (
    'iso' => 'LY',
    'iso3' => 'LBY',
    'iso_num' => '434',
    'country' => 'Libya',
    'capital' => 'Tripolis',
    'continent' => 'AF',
    'country_zh_cn' => '利比亚',
    'latitude' => '37.50889',
    'longitude' => '22.37944',
    'capital_latlng' => 1,
  ),
  137 => 
  array (
    'iso' => 'MA',
    'iso3' => 'MAR',
    'iso_num' => '504',
    'country' => 'Morocco',
    'capital' => 'Rabat',
    'continent' => 'AF',
    'country_zh_cn' => '摩洛哥',
    'latitude' => '34.01325',
    'longitude' => '-6.83255',
    'capital_latlng' => 1,
  ),
  138 => 
  array (
    'iso' => 'MC',
    'iso3' => 'MCO',
    'iso_num' => '492',
    'country' => 'Monaco',
    'capital' => 'Monaco',
    'continent' => 'EU',
    'country_zh_cn' => '摩纳哥',
    'latitude' => '43.73333',
    'longitude' => '7.41667',
    'capital_latlng' => 1,
  ),
  139 => 
  array (
    'iso' => 'MD',
    'iso3' => 'MDA',
    'iso_num' => '498',
    'country' => 'Moldova',
    'capital' => 'Chisinau',
    'continent' => 'EU',
    'country_zh_cn' => '摩尔多瓦',
    'latitude' => '47.00556',
    'longitude' => '28.8575',
    'capital_latlng' => 1,
  ),
  140 => 
  array (
    'iso' => 'ME',
    'iso3' => 'MNE',
    'iso_num' => '499',
    'country' => 'Montenegro',
    'capital' => 'Podgorica',
    'continent' => 'EU',
    'country_zh_cn' => '黑山',
    'latitude' => '42.44111',
    'longitude' => '19.26361',
    'capital_latlng' => 1,
  ),
  141 => 
  array (
    'iso' => 'MF',
    'iso3' => 'MAF',
    'iso_num' => '663',
    'country' => 'Saint Martin',
    'capital' => 'Marigot',
    'continent' => 'NA',
    'country_zh_cn' => '法属圣马丁',
    'latitude' => '18.06667',
    'longitude' => '-63.08333',
    'capital_latlng' => 1,
  ),
  142 => 
  array (
    'iso' => 'MG',
    'iso3' => 'MDG',
    'iso_num' => '450',
    'country' => 'Madagascar',
    'capital' => 'Antananarivo',
    'continent' => 'AF',
    'country_zh_cn' => '马达加斯加',
    'latitude' => '-18.91368',
    'longitude' => '47.53613',
    'capital_latlng' => 1,
  ),
  143 => 
  array (
    'iso' => 'MH',
    'iso3' => 'MHL',
    'iso_num' => '584',
    'country' => 'Marshall Islands',
    'capital' => 'Majuro',
    'continent' => 'OC',
    'country_zh_cn' => '马绍尔群岛',
    'latitude' => '7.08971',
    'longitude' => '171.38027',
    'capital_latlng' => 1,
  ),
  144 => 
  array (
    'iso' => 'MK',
    'iso3' => 'MKD',
    'iso_num' => '807',
    'country' => 'Macedonia',
    'capital' => 'Skopje',
    'continent' => 'EU',
    'country_zh_cn' => '马其顿',
    'latitude' => '41.99646',
    'longitude' => '21.43141',
    'capital_latlng' => 1,
  ),
  145 => 
  array (
    'iso' => 'ML',
    'iso3' => 'MLI',
    'iso_num' => '466',
    'country' => 'Mali',
    'capital' => 'Bamako',
    'continent' => 'AF',
    'country_zh_cn' => '马里',
    'latitude' => '12.65',
    'longitude' => '-8',
    'capital_latlng' => 1,
  ),
  146 => 
  array (
    'iso' => 'MM',
    'iso3' => 'MMR',
    'iso_num' => '104',
    'country' => 'Myanmar',
    'capital' => 'Nay Pyi Taw',
    'continent' => 'AS',
    'country_zh_cn' => '缅甸',
    'latitude' => '19.745',
    'longitude' => '96.12972',
    'capital_latlng' => 1,
  ),
  147 => 
  array (
    'iso' => 'MN',
    'iso3' => 'MNG',
    'iso_num' => '496',
    'country' => 'Mongolia',
    'capital' => 'Ulan Bator',
    'continent' => 'AS',
    'country_zh_cn' => '蒙古',
    'latitude' => '47.90771',
    'longitude' => '106.88324',
    'capital_latlng' => 1,
  ),
  148 => 
  array (
    'iso' => 'MO',
    'iso3' => 'MAC',
    'iso_num' => '446',
    'country' => 'Macao',
    'capital' => 'Macao',
    'continent' => 'AS',
    'country_zh_cn' => '澳门',
    'latitude' => '-5.115',
    'longitude' => '-36.63444',
    'capital_latlng' => 1,
  ),
  149 => 
  array (
    'iso' => 'MP',
    'iso3' => 'MNP',
    'iso_num' => '580',
    'country' => 'Northern Mariana Islands',
    'capital' => 'Saipan',
    'continent' => 'OC',
    'country_zh_cn' => '北马里亚纳群岛',
    'latitude' => '15.21233',
    'longitude' => '145.7545',
    'capital_latlng' => 1,
  ),
  150 => 
  array (
    'iso' => 'MQ',
    'iso3' => 'MTQ',
    'iso_num' => '474',
    'country' => 'Martinique',
    'capital' => 'Fort-de-France',
    'continent' => 'NA',
    'country_zh_cn' => '马提尼克',
    'latitude' => '14.60892',
    'longitude' => '-61.07334',
    'capital_latlng' => 1,
  ),
  151 => 
  array (
    'iso' => 'MR',
    'iso3' => 'MRT',
    'iso_num' => '478',
    'country' => 'Mauritania',
    'capital' => 'Nouakchott',
    'continent' => 'AF',
    'country_zh_cn' => '毛里塔尼亚',
    'latitude' => '18.08581',
    'longitude' => '-15.9785',
    'capital_latlng' => 1,
  ),
  152 => 
  array (
    'iso' => 'MS',
    'iso3' => 'MSR',
    'iso_num' => '500',
    'country' => 'Montserrat',
    'capital' => 'Plymouth',
    'continent' => 'NA',
    'country_zh_cn' => '蒙塞拉特岛',
    'latitude' => '50.37153',
    'longitude' => '-4.14305',
    'capital_latlng' => 1,
  ),
  153 => 
  array (
    'iso' => 'MT',
    'iso3' => 'MLT',
    'iso_num' => '470',
    'country' => 'Malta',
    'capital' => 'Valletta',
    'continent' => 'EU',
    'country_zh_cn' => '马耳他',
    'latitude' => '35.89972',
    'longitude' => '14.51472',
    'capital_latlng' => 1,
  ),
  154 => 
  array (
    'iso' => 'MU',
    'iso3' => 'MUS',
    'iso_num' => '480',
    'country' => 'Mauritius',
    'capital' => 'Port Louis',
    'continent' => 'AF',
    'country_zh_cn' => '毛里求斯',
    'latitude' => '-20.16194',
    'longitude' => '57.49889',
    'capital_latlng' => 1,
  ),
  155 => 
  array (
    'iso' => 'MV',
    'iso3' => 'MDV',
    'iso_num' => '462',
    'country' => 'Maldives',
    'capital' => 'Male',
    'continent' => 'AS',
    'country_zh_cn' => '马尔代夫',
    'latitude' => '4.1748',
    'longitude' => '73.50888',
    'capital_latlng' => 1,
  ),
  156 => 
  array (
    'iso' => 'MW',
    'iso3' => 'MWI',
    'iso_num' => '454',
    'country' => 'Malawi',
    'capital' => 'Lilongwe',
    'continent' => 'AF',
    'country_zh_cn' => '马拉维',
    'latitude' => '-13.96692',
    'longitude' => '33.78725',
    'capital_latlng' => 1,
  ),
  157 => 
  array (
    'iso' => 'MX',
    'iso3' => 'MEX',
    'iso_num' => '484',
    'country' => 'Mexico',
    'capital' => 'Mexico City',
    'continent' => 'NA',
    'country_zh_cn' => '墨西哥',
    'latitude' => '19.42847',
    'longitude' => '-99.12766',
    'capital_latlng' => 1,
  ),
  158 => 
  array (
    'iso' => 'MY',
    'iso3' => 'MYS',
    'iso_num' => '458',
    'country' => 'Malaysia',
    'capital' => 'Kuala Lumpur',
    'continent' => 'AS',
    'country_zh_cn' => '马来西亚',
    'latitude' => '3.1412',
    'longitude' => '101.68653',
    'capital_latlng' => 1,
  ),
  159 => 
  array (
    'iso' => 'MZ',
    'iso3' => 'MOZ',
    'iso_num' => '508',
    'country' => 'Mozambique',
    'capital' => 'Maputo',
    'continent' => 'AF',
    'country_zh_cn' => '莫桑比克',
    'latitude' => '-25.96553',
    'longitude' => '32.58322',
    'capital_latlng' => 1,
  ),
  160 => 
  array (
    'iso' => 'NA',
    'iso3' => 'NAM',
    'iso_num' => '516',
    'country' => 'Namibia',
    'capital' => 'Windhoek',
    'continent' => 'AF',
    'country_zh_cn' => '纳米比亚',
    'latitude' => '-22.55941',
    'longitude' => '17.08323',
    'capital_latlng' => 1,
  ),
  161 => 
  array (
    'iso' => 'NC',
    'iso3' => 'NCL',
    'iso_num' => '540',
    'country' => 'New Caledonia',
    'capital' => 'Noumea',
    'continent' => 'OC',
    'country_zh_cn' => '新喀里多尼亚',
    'latitude' => '-22.27631',
    'longitude' => '166.4572',
    'capital_latlng' => 1,
  ),
  162 => 
  array (
    'iso' => 'NE',
    'iso3' => 'NER',
    'iso_num' => '562',
    'country' => 'Niger',
    'capital' => 'Niamey',
    'continent' => 'AF',
    'country_zh_cn' => '尼日尔',
    'latitude' => '13.51366',
    'longitude' => '2.1098',
    'capital_latlng' => 1,
  ),
  163 => 
  array (
    'iso' => 'NF',
    'iso3' => 'NFK',
    'iso_num' => '574',
    'country' => 'Norfolk Island',
    'capital' => 'Kingston',
    'continent' => 'OC',
    'country_zh_cn' => '诺福克岛',
    'latitude' => '17.99702',
    'longitude' => '-76.79358',
    'capital_latlng' => 1,
  ),
  164 => 
  array (
    'iso' => 'NG',
    'iso3' => 'NGA',
    'iso_num' => '566',
    'country' => 'Nigeria',
    'capital' => 'Abuja',
    'continent' => 'AF',
    'country_zh_cn' => '尼日利亚',
    'latitude' => '9.18059',
    'longitude' => '7.17939',
    'capital_latlng' => 1,
  ),
  165 => 
  array (
    'iso' => 'NI',
    'iso3' => 'NIC',
    'iso_num' => '558',
    'country' => 'Nicaragua',
    'capital' => 'Managua',
    'continent' => 'NA',
    'country_zh_cn' => '尼加拉瓜',
    'latitude' => '12.13282',
    'longitude' => '-86.2504',
    'capital_latlng' => 1,
  ),
  166 => 
  array (
    'iso' => 'NL',
    'iso3' => 'NLD',
    'iso_num' => '528',
    'country' => 'Netherlands',
    'capital' => 'Amsterdam',
    'continent' => 'EU',
    'country_zh_cn' => '荷兰',
    'latitude' => '52.37403',
    'longitude' => '4.88969',
    'capital_latlng' => 1,
  ),
  167 => 
  array (
    'iso' => 'NO',
    'iso3' => 'NOR',
    'iso_num' => '578',
    'country' => 'Norway',
    'capital' => 'Oslo',
    'continent' => 'EU',
    'country_zh_cn' => '挪威',
    'latitude' => '59.91273',
    'longitude' => '10.74609',
    'capital_latlng' => 1,
  ),
  168 => 
  array (
    'iso' => 'NP',
    'iso3' => 'NPL',
    'iso_num' => '524',
    'country' => 'Nepal',
    'capital' => 'Kathmandu',
    'continent' => 'AS',
    'country_zh_cn' => '尼泊尔',
    'latitude' => '27.70169',
    'longitude' => '85.3206',
    'capital_latlng' => 1,
  ),
  169 => 
  array (
    'iso' => 'NR',
    'iso3' => 'NRU',
    'iso_num' => '520',
    'country' => 'Nauru',
    'capital' => 'Yaren',
    'continent' => 'OC',
    'country_zh_cn' => '瑙鲁',
  ),
  170 => 
  array (
    'iso' => 'NU',
    'iso3' => 'NIU',
    'iso_num' => '570',
    'country' => 'Niue',
    'capital' => 'Alofi',
    'continent' => 'OC',
    'country_zh_cn' => '纽埃',
    'latitude' => '-19.05952',
    'longitude' => '-169.91867',
    'capital_latlng' => 1,
  ),
  171 => 
  array (
    'iso' => 'NZ',
    'iso3' => 'NZL',
    'iso_num' => '554',
    'country' => 'New Zealand',
    'capital' => 'Wellington',
    'continent' => 'OC',
    'country_zh_cn' => '新西兰',
    'latitude' => '52.7',
    'longitude' => '-2.51667',
    'capital_latlng' => 1,
  ),
  172 => 
  array (
    'iso' => 'OM',
    'iso3' => 'OMN',
    'iso_num' => '512',
    'country' => 'Oman',
    'capital' => 'Muscat',
    'continent' => 'AS',
    'country_zh_cn' => '阿曼',
    'latitude' => '23.61387',
    'longitude' => '58.5922',
    'capital_latlng' => 1,
  ),
  173 => 
  array (
    'iso' => 'PA',
    'iso3' => 'PAN',
    'iso_num' => '591',
    'country' => 'Panama',
    'capital' => 'Panama City',
    'continent' => 'NA',
    'country_zh_cn' => '巴拿马',
    'latitude' => '8.9936',
    'longitude' => '-79.51973',
    'capital_latlng' => 1,
  ),
  174 => 
  array (
    'iso' => 'PE',
    'iso3' => 'PER',
    'iso_num' => '604',
    'country' => 'Peru',
    'capital' => 'Lima',
    'continent' => 'SA',
    'country_zh_cn' => '秘鲁',
    'latitude' => '-12.04318',
    'longitude' => '-77.02824',
    'capital_latlng' => 1,
  ),
  175 => 
  array (
    'iso' => 'PF',
    'iso3' => 'PYF',
    'iso_num' => '258',
    'country' => 'French Polynesia',
    'capital' => 'Papeete',
    'continent' => 'OC',
    'country_zh_cn' => '法属波利尼西亚',
    'latitude' => '-17.53733',
    'longitude' => '-149.5665',
    'capital_latlng' => 1,
  ),
  176 => 
  array (
    'iso' => 'PG',
    'iso3' => 'PNG',
    'iso_num' => '598',
    'country' => 'Papua New Guinea',
    'capital' => 'Port Moresby',
    'continent' => 'OC',
    'country_zh_cn' => '巴布亚新几内亚',
    'latitude' => '-9.44314',
    'longitude' => '147.17972',
    'capital_latlng' => 1,
  ),
  177 => 
  array (
    'iso' => 'PH',
    'iso3' => 'PHL',
    'iso_num' => '608',
    'country' => 'Philippines',
    'capital' => 'Manila',
    'continent' => 'AS',
    'country_zh_cn' => '菲律宾',
    'latitude' => '14.6042',
    'longitude' => '120.9822',
    'capital_latlng' => 1,
  ),
  178 => 
  array (
    'iso' => 'PK',
    'iso3' => 'PAK',
    'iso_num' => '586',
    'country' => 'Pakistan',
    'capital' => 'Islamabad',
    'continent' => 'AS',
    'country_zh_cn' => '巴基斯坦',
    'latitude' => '22.3384',
    'longitude' => '91.83168',
    'capital_latlng' => 1,
  ),
  179 => 
  array (
    'iso' => 'PL',
    'iso3' => 'POL',
    'iso_num' => '616',
    'country' => 'Poland',
    'capital' => 'Warsaw',
    'continent' => 'EU',
    'country_zh_cn' => '波兰',
    'latitude' => '52.22977',
    'longitude' => '21.01178',
    'capital_latlng' => 1,
  ),
  180 => 
  array (
    'iso' => 'PM',
    'iso3' => 'SPM',
    'iso_num' => '666',
    'country' => 'Saint Pierre and Miquelon',
    'capital' => 'Saint-Pierre',
    'continent' => 'NA',
    'country_zh_cn' => '圣皮埃尔和密克隆群岛',
    'latitude' => '47.38623',
    'longitude' => '0.74849',
    'capital_latlng' => 1,
  ),
  181 => 
  array (
    'iso' => 'PN',
    'iso3' => 'PCN',
    'iso_num' => '612',
    'country' => 'Pitcairn',
    'capital' => 'Adamstown',
    'continent' => 'OC',
    'country_zh_cn' => '皮特凯恩群岛',
    'latitude' => '-25.06597',
    'longitude' => '-130.10147',
    'capital_latlng' => 1,
  ),
  182 => 
  array (
    'iso' => 'PR',
    'iso3' => 'PRI',
    'iso_num' => '630',
    'country' => 'Puerto Rico',
    'capital' => 'San Juan',
    'continent' => 'NA',
    'country_zh_cn' => '波多黎各',
    'latitude' => '-31.5375',
    'longitude' => '-68.53639',
    'capital_latlng' => 1,
  ),
  183 => 
  array (
    'iso' => 'PS',
    'iso3' => 'PSE',
    'iso_num' => '275',
    'country' => 'Palestinian Territory',
    'capital' => 'East Jerusalem',
    'continent' => 'AS',
    'country_zh_cn' => '巴勒斯坦',
    'latitude' => '31.78336',
    'longitude' => '35.23388',
    'capital_latlng' => 1,
  ),
  184 => 
  array (
    'iso' => 'PT',
    'iso3' => 'PRT',
    'iso_num' => '620',
    'country' => 'Portugal',
    'capital' => 'Lisbon',
    'continent' => 'EU',
    'country_zh_cn' => '葡萄牙',
    'latitude' => '38.71667',
    'longitude' => '-9.13333',
    'capital_latlng' => 1,
  ),
  185 => 
  array (
    'iso' => 'PW',
    'iso3' => 'PLW',
    'iso_num' => '585',
    'country' => 'Palau',
    'capital' => 'Melekeok',
    'continent' => 'OC',
    'country_zh_cn' => '帕劳',
    'latitude' => '7.50043',
    'longitude' => '134.62355',
    'capital_latlng' => 1,
  ),
  186 => 
  array (
    'iso' => 'PY',
    'iso3' => 'PRY',
    'iso_num' => '600',
    'country' => 'Paraguay',
    'capital' => 'Asuncion',
    'continent' => 'SA',
    'country_zh_cn' => '巴拉圭',
    'latitude' => '14.33083',
    'longitude' => '-89.71083',
    'capital_latlng' => 1,
  ),
  187 => 
  array (
    'iso' => 'QA',
    'iso3' => 'QAT',
    'iso_num' => '634',
    'country' => 'Qatar',
    'capital' => 'Doha',
    'continent' => 'AS',
    'country_zh_cn' => '卡塔尔',
    'latitude' => '25.27932',
    'longitude' => '51.52245',
    'capital_latlng' => 1,
  ),
  188 => 
  array (
    'iso' => 'RE',
    'iso3' => 'REU',
    'iso_num' => '638',
    'country' => 'Reunion',
    'capital' => 'Saint-Denis',
    'continent' => 'AF',
    'country_zh_cn' => '留尼汪',
    'latitude' => '48.93333',
    'longitude' => '2.36667',
    'capital_latlng' => 1,
  ),
  189 => 
  array (
    'iso' => 'RO',
    'iso3' => 'ROU',
    'iso_num' => '642',
    'country' => 'Romania',
    'capital' => 'Bucharest',
    'continent' => 'EU',
    'country_zh_cn' => '罗马尼亚',
    'latitude' => '44.43225',
    'longitude' => '26.10626',
    'capital_latlng' => 1,
  ),
  190 => 
  array (
    'iso' => 'RS',
    'iso3' => 'SRB',
    'iso_num' => '688',
    'country' => 'Serbia',
    'capital' => 'Belgrade',
    'continent' => 'EU',
    'country_zh_cn' => '塞尔维亚',
    'latitude' => '44.80401',
    'longitude' => '20.46513',
    'capital_latlng' => 1,
  ),
  191 => 
  array (
    'iso' => 'RU',
    'iso3' => 'RUS',
    'iso_num' => '643',
    'country' => 'Russia',
    'capital' => 'Moscow',
    'continent' => 'EU',
    'country_zh_cn' => '俄罗斯',
    'latitude' => '55.75222',
    'longitude' => '37.61556',
    'capital_latlng' => 1,
  ),
  192 => 
  array (
    'iso' => 'RW',
    'iso3' => 'RWA',
    'iso_num' => '646',
    'country' => 'Rwanda',
    'capital' => 'Kigali',
    'continent' => 'AF',
    'country_zh_cn' => '卢旺达',
    'latitude' => '-1.94995',
    'longitude' => '30.05885',
    'capital_latlng' => 1,
  ),
  193 => 
  array (
    'iso' => 'SA',
    'iso3' => 'SAU',
    'iso_num' => '682',
    'country' => 'Saudi Arabia',
    'capital' => 'Riyadh',
    'continent' => 'AS',
    'country_zh_cn' => '沙特阿拉伯',
    'latitude' => '24.68773',
    'longitude' => '46.72185',
    'capital_latlng' => 1,
  ),
  194 => 
  array (
    'iso' => 'SB',
    'iso3' => 'SLB',
    'iso_num' => '090',
    'country' => 'Solomon Islands',
    'capital' => 'Honiara',
    'continent' => 'OC',
    'country_zh_cn' => '所罗门群岛',
    'latitude' => '-9.43333',
    'longitude' => '159.95',
    'capital_latlng' => 1,
  ),
  195 => 
  array (
    'iso' => 'SC',
    'iso3' => 'SYC',
    'iso_num' => '690',
    'country' => 'Seychelles',
    'capital' => 'Victoria',
    'continent' => 'AF',
    'country_zh_cn' => '塞舌尔',
    'latitude' => '-32.61841',
    'longitude' => '-60.15478',
    'capital_latlng' => 1,
  ),
  196 => 
  array (
    'iso' => 'SD',
    'iso3' => 'SDN',
    'iso_num' => '729',
    'country' => 'Sudan',
    'capital' => 'Khartoum',
    'continent' => 'AF',
    'country_zh_cn' => '苏丹',
    'latitude' => '15.55177',
    'longitude' => '32.53241',
    'capital_latlng' => 1,
  ),
  197 => 
  array (
    'iso' => 'SS',
    'iso3' => 'SSD',
    'iso_num' => '728',
    'country' => 'South Sudan',
    'capital' => 'Juba',
    'continent' => 'AF',
    'country_zh_cn' => '南苏丹',
    'latitude' => '4.85165',
    'longitude' => '31.58247',
    'capital_latlng' => 1,
  ),
  198 => 
  array (
    'iso' => 'SE',
    'iso3' => 'SWE',
    'iso_num' => '752',
    'country' => 'Sweden',
    'capital' => 'Stockholm',
    'continent' => 'EU',
    'country_zh_cn' => '瑞典',
    'latitude' => '59.33258',
    'longitude' => '18.0649',
    'capital_latlng' => 1,
  ),
  199 => 
  array (
    'iso' => 'SG',
    'iso3' => 'SGP',
    'iso_num' => '702',
    'country' => 'Singapore',
    'capital' => 'Singapur',
    'continent' => 'AS',
    'country_zh_cn' => '新加坡',
    'latitude' => '17.46982',
    'longitude' => '78.12574',
    'capital_latlng' => 1,
  ),
  200 => 
  array (
    'iso' => 'SH',
    'iso3' => 'SHN',
    'iso_num' => '654',
    'country' => 'Saint Helena',
    'capital' => 'Jamestown',
    'continent' => 'AF',
    'country_zh_cn' => '圣赫勒拿岛',
    'latitude' => '-15.93872',
    'longitude' => '-5.71675',
    'capital_latlng' => 1,
  ),
  201 => 
  array (
    'iso' => 'SI',
    'iso3' => 'SVN',
    'iso_num' => '705',
    'country' => 'Slovenia',
    'capital' => 'Ljubljana',
    'continent' => 'EU',
    'country_zh_cn' => '斯洛文尼亚',
    'latitude' => '46.05108',
    'longitude' => '14.50513',
    'capital_latlng' => 1,
  ),
  202 => 
  array (
    'iso' => 'SJ',
    'iso3' => 'SJM',
    'iso_num' => '744',
    'country' => 'Svalbard and Jan Mayen',
    'capital' => 'Longyearbyen',
    'continent' => 'EU',
    'country_zh_cn' => '斯瓦尔巴群岛和扬马延岛',
    'latitude' => '78.22334',
    'longitude' => '15.64689',
    'capital_latlng' => 1,
  ),
  203 => 
  array (
    'iso' => 'SK',
    'iso3' => 'SVK',
    'iso_num' => '703',
    'country' => 'Slovakia',
    'capital' => 'Bratislava',
    'continent' => 'EU',
    'country_zh_cn' => '斯洛伐克',
    'latitude' => '48.14816',
    'longitude' => '17.10674',
    'capital_latlng' => 1,
  ),
  204 => 
  array (
    'iso' => 'SL',
    'iso3' => 'SLE',
    'iso_num' => '694',
    'country' => 'Sierra Leone',
    'capital' => 'Freetown',
    'continent' => 'AF',
    'country_zh_cn' => '塞拉利昂',
    'latitude' => '8.484',
    'longitude' => '-13.22994',
    'capital_latlng' => 1,
  ),
  205 => 
  array (
    'iso' => 'SM',
    'iso3' => 'SMR',
    'iso_num' => '674',
    'country' => 'San Marino',
    'capital' => 'San Marino',
    'continent' => 'EU',
    'country_zh_cn' => '圣马力诺',
    'latitude' => '43.93667',
    'longitude' => '12.44639',
    'capital_latlng' => 1,
  ),
  206 => 
  array (
    'iso' => 'SN',
    'iso3' => 'SEN',
    'iso_num' => '686',
    'country' => 'Senegal',
    'capital' => 'Dakar',
    'continent' => 'AF',
    'country_zh_cn' => '塞内加尔',
    'latitude' => '14.6937',
    'longitude' => '-17.44406',
    'capital_latlng' => 1,
  ),
  207 => 
  array (
    'iso' => 'SO',
    'iso3' => 'SOM',
    'iso_num' => '706',
    'country' => 'Somalia',
    'capital' => 'Mogadishu',
    'continent' => 'AF',
    'country_zh_cn' => '索马里',
    'latitude' => '2.03711',
    'longitude' => '45.34375',
    'capital_latlng' => 1,
  ),
  208 => 
  array (
    'iso' => 'SR',
    'iso3' => 'SUR',
    'iso_num' => '740',
    'country' => 'Suriname',
    'capital' => 'Paramaribo',
    'continent' => 'SA',
    'country_zh_cn' => '苏里南',
    'latitude' => '5.86638',
    'longitude' => '-55.16682',
    'capital_latlng' => 1,
  ),
  209 => 
  array (
    'iso' => 'ST',
    'iso3' => 'STP',
    'iso_num' => '678',
    'country' => 'Sao Tome and Principe',
    'capital' => 'Sao Tome',
    'continent' => 'AF',
    'country_zh_cn' => '圣多美和普林西比',
    'latitude' => '0.33654',
    'longitude' => '6.72732',
    'capital_latlng' => 1,
  ),
  210 => 
  array (
    'iso' => 'SV',
    'iso3' => 'SLV',
    'iso_num' => '222',
    'country' => 'El Salvador',
    'capital' => 'San Salvador',
    'continent' => 'NA',
    'country_zh_cn' => '萨尔瓦多',
    'latitude' => '-6.26703',
    'longitude' => '14.2401',
    'capital_latlng' => 1,
  ),
  211 => 
  array (
    'iso' => 'SX',
    'iso3' => 'SXM',
    'iso_num' => '534',
    'country' => 'Sint Maarten',
    'capital' => 'Philipsburg',
    'continent' => 'NA',
    'country_zh_cn' => '圣马丁岛',
    'latitude' => '18.026',
    'longitude' => '-63.04582',
    'capital_latlng' => 1,
  ),
  212 => 
  array (
    'iso' => 'SY',
    'iso3' => 'SYR',
    'iso_num' => '760',
    'country' => 'Syria',
    'capital' => 'Damascus',
    'continent' => 'AS',
    'country_zh_cn' => '叙利亚',
    'latitude' => '33.5102',
    'longitude' => '36.29128',
    'capital_latlng' => 1,
  ),
  213 => 
  array (
    'iso' => 'SZ',
    'iso3' => 'SWZ',
    'iso_num' => '748',
    'country' => 'Swaziland',
    'capital' => 'Mbabane',
    'continent' => 'AF',
    'country_zh_cn' => '斯威士兰',
    'latitude' => '-26.31667',
    'longitude' => '31.13333',
    'capital_latlng' => 1,
  ),
  214 => 
  array (
    'iso' => 'TC',
    'iso3' => 'TCA',
    'iso_num' => '796',
    'country' => 'Turks and Caicos Islands',
    'capital' => 'Cockburn Town',
    'continent' => 'NA',
    'country_zh_cn' => '特克斯和凯科斯群岛',
    'latitude' => '21.46122',
    'longitude' => '-71.14188',
    'capital_latlng' => 1,
  ),
  215 => 
  array (
    'iso' => 'TD',
    'iso3' => 'TCD',
    'iso_num' => '148',
    'country' => 'Chad',
    'capital' => 'N\'Djamena',
    'continent' => 'AF',
    'country_zh_cn' => '乍得',
    'latitude' => '12.10672',
    'longitude' => '15.0444',
    'capital_latlng' => 1,
  ),
  216 => 
  array (
    'iso' => 'TF',
    'iso3' => 'ATF',
    'iso_num' => '260',
    'country' => 'French Southern Territories',
    'capital' => 'Port-aux-Francais',
    'continent' => 'AN',
    'country_zh_cn' => '法属南部领地',
    'latitude' => '-49.35',
    'longitude' => '70.21667',
    'capital_latlng' => 1,
  ),
  217 => 
  array (
    'iso' => 'TG',
    'iso3' => 'TGO',
    'iso_num' => '768',
    'country' => 'Togo',
    'capital' => 'Lome',
    'continent' => 'AF',
    'country_zh_cn' => '多哥',
    'latitude' => '6.13748',
    'longitude' => '1.21227',
    'capital_latlng' => 1,
  ),
  218 => 
  array (
    'iso' => 'TH',
    'iso3' => 'THA',
    'iso_num' => '764',
    'country' => 'Thailand',
    'capital' => 'Bangkok',
    'continent' => 'AS',
    'country_zh_cn' => '泰国',
    'latitude' => '13.75398',
    'longitude' => '100.50144',
    'capital_latlng' => 1,
  ),
  219 => 
  array (
    'iso' => 'TJ',
    'iso3' => 'TJK',
    'iso_num' => '762',
    'country' => 'Tajikistan',
    'capital' => 'Dushanbe',
    'continent' => 'AS',
    'country_zh_cn' => '塔吉克斯坦',
    'latitude' => '38.53575',
    'longitude' => '68.77905',
    'capital_latlng' => 1,
  ),
  220 => 
  array (
    'iso' => 'TK',
    'iso3' => 'TKL',
    'iso_num' => '772',
    'country' => 'Tokelau',
    'capital' => '',
    'continent' => 'OC',
    'country_zh_cn' => '托克劳群岛',
  ),
  221 => 
  array (
    'iso' => 'TL',
    'iso3' => 'TLS',
    'iso_num' => '626',
    'country' => 'East Timor',
    'capital' => 'Dili',
    'continent' => 'OC',
    'country_zh_cn' => '东帝汶',
    'latitude' => '28.65195',
    'longitude' => '77.23149',
    'capital_latlng' => 1,
  ),
  222 => 
  array (
    'iso' => 'TM',
    'iso3' => 'TKM',
    'iso_num' => '795',
    'country' => 'Turkmenistan',
    'capital' => 'Ashgabat',
    'continent' => 'AS',
    'country_zh_cn' => '土库曼斯坦',
    'latitude' => '37.95',
    'longitude' => '58.38333',
    'capital_latlng' => 1,
  ),
  223 => 
  array (
    'iso' => 'TN',
    'iso3' => 'TUN',
    'iso_num' => '788',
    'country' => 'Tunisia',
    'capital' => 'Tunis',
    'continent' => 'AF',
    'country_zh_cn' => '突尼斯',
    'latitude' => '36.81897',
    'longitude' => '10.16579',
    'capital_latlng' => 1,
  ),
  224 => 
  array (
    'iso' => 'TO',
    'iso3' => 'TON',
    'iso_num' => '776',
    'country' => 'Tonga',
    'capital' => 'Nuku\'alofa',
    'continent' => 'OC',
    'country_zh_cn' => '汤加',
    'latitude' => '-21.13938',
    'longitude' => '-175.2018',
    'capital_latlng' => 1,
  ),
  225 => 
  array (
    'iso' => 'TR',
    'iso3' => 'TUR',
    'iso_num' => '792',
    'country' => 'Turkey',
    'capital' => 'Ankara',
    'continent' => 'AS',
    'country_zh_cn' => '土耳其',
    'latitude' => '39.91987',
    'longitude' => '32.85427',
    'capital_latlng' => 1,
  ),
  226 => 
  array (
    'iso' => 'TT',
    'iso3' => 'TTO',
    'iso_num' => '780',
    'country' => 'Trinidad and Tobago',
    'capital' => 'Port of Spain',
    'continent' => 'NA',
    'country_zh_cn' => '特立尼达和多巴哥',
    'latitude' => '10.66668',
    'longitude' => '-61.51889',
    'capital_latlng' => 1,
  ),
  227 => 
  array (
    'iso' => 'TV',
    'iso3' => 'TUV',
    'iso_num' => '798',
    'country' => 'Tuvalu',
    'capital' => 'Funafuti',
    'continent' => 'OC',
    'country_zh_cn' => '图瓦卢',
    'latitude' => '-8.52425',
    'longitude' => '179.19417',
    'capital_latlng' => 1,
  ),
  228 => 
  array (
    'iso' => 'TW',
    'iso3' => 'TWN',
    'iso_num' => '158',
    'country' => 'Taiwan',
    'capital' => 'Taipei',
    'continent' => 'AS',
    'country_zh_cn' => '台湾',
    'latitude' => '25.04776',
    'longitude' => '121.53185',
    'capital_latlng' => 1,
  ),
  229 => 
  array (
    'iso' => 'TZ',
    'iso3' => 'TZA',
    'iso_num' => '834',
    'country' => 'Tanzania',
    'capital' => 'Dodoma',
    'continent' => 'AF',
    'country_zh_cn' => '坦桑尼亚',
    'latitude' => '-6.17221',
    'longitude' => '35.73947',
    'capital_latlng' => 1,
  ),
  230 => 
  array (
    'iso' => 'UA',
    'iso3' => 'UKR',
    'iso_num' => '804',
    'country' => 'Ukraine',
    'capital' => 'Kiev',
    'continent' => 'EU',
    'country_zh_cn' => '乌克兰',
    'latitude' => '50.45466',
    'longitude' => '30.5238',
    'capital_latlng' => 1,
  ),
  231 => 
  array (
    'iso' => 'UG',
    'iso3' => 'UGA',
    'iso_num' => '800',
    'country' => 'Uganda',
    'capital' => 'Kampala',
    'continent' => 'AF',
    'country_zh_cn' => '乌干达',
    'latitude' => '0.31628',
    'longitude' => '32.58219',
    'capital_latlng' => 1,
  ),
  232 => 
  array (
    'iso' => 'UM',
    'iso3' => 'UMI',
    'iso_num' => '581',
    'country' => 'United States Minor Outlying Islands',
    'capital' => '',
    'continent' => 'OC',
    'country_zh_cn' => '美国本土外小岛屿',
  ),
  233 => 
  array (
    'iso' => 'US',
    'iso3' => 'USA',
    'iso_num' => '840',
    'country' => 'United States',
    'capital' => 'Washington, D.C.',
    'continent' => 'NA',
    'country_zh_cn' => '美国',
    'latitude' => '38.89511',
    'longitude' => '-77.03637',
    'capital_latlng' => 1,
  ),
  234 => 
  array (
    'iso' => 'UY',
    'iso3' => 'URY',
    'iso_num' => '858',
    'country' => 'Uruguay',
    'capital' => 'Montevideo',
    'continent' => 'SA',
    'country_zh_cn' => '乌拉圭',
    'latitude' => '-34.90328',
    'longitude' => '-56.18816',
    'capital_latlng' => 1,
  ),
  235 => 
  array (
    'iso' => 'UZ',
    'iso3' => 'UZB',
    'iso_num' => '860',
    'country' => 'Uzbekistan',
    'capital' => 'Tashkent',
    'continent' => 'AS',
    'country_zh_cn' => '乌兹别克斯坦',
    'latitude' => '41.26465',
    'longitude' => '69.21627',
    'capital_latlng' => 1,
  ),
  236 => 
  array (
    'iso' => 'VA',
    'iso3' => 'VAT',
    'iso_num' => '336',
    'country' => 'Vatican',
    'capital' => 'Vatican City',
    'continent' => 'EU',
    'country_zh_cn' => '梵蒂冈',
    'latitude' => '41.90236',
    'longitude' => '12.45332',
    'capital_latlng' => 1,
  ),
  237 => 
  array (
    'iso' => 'VC',
    'iso3' => 'VCT',
    'iso_num' => '670',
    'country' => 'Saint Vincent and the Grenadines',
    'capital' => 'Kingstown',
    'continent' => 'NA',
    'country_zh_cn' => '圣文森特和格林纳丁斯',
    'latitude' => '53.29395',
    'longitude' => '-6.13586',
    'capital_latlng' => 1,
  ),
  238 => 
  array (
    'iso' => 'VE',
    'iso3' => 'VEN',
    'iso_num' => '862',
    'country' => 'Venezuela',
    'capital' => 'Caracas',
    'continent' => 'SA',
    'country_zh_cn' => '委内瑞拉',
    'latitude' => '-0.59792',
    'longitude' => '-80.42367',
    'capital_latlng' => 1,
  ),
  239 => 
  array (
    'iso' => 'VG',
    'iso3' => 'VGB',
    'iso_num' => '092',
    'country' => 'British Virgin Islands',
    'capital' => 'Road Town',
    'continent' => 'NA',
    'country_zh_cn' => '英属维尔京群岛',
    'latitude' => '18.42693',
    'longitude' => '-64.62079',
    'capital_latlng' => 1,
  ),
  240 => 
  array (
    'iso' => 'VI',
    'iso3' => 'VIR',
    'iso_num' => '850',
    'country' => 'U.S. Virgin Islands',
    'capital' => 'Charlotte Amalie',
    'continent' => 'NA',
    'country_zh_cn' => '美属维尔京群岛',
    'latitude' => '18.3419',
    'longitude' => '-64.9307',
    'capital_latlng' => 1,
  ),
  241 => 
  array (
    'iso' => 'VN',
    'iso3' => 'VNM',
    'iso_num' => '704',
    'country' => 'Vietnam',
    'capital' => 'Hanoi',
    'continent' => 'AS',
    'country_zh_cn' => '越南',
    'latitude' => '21.0245',
    'longitude' => '105.84117',
    'capital_latlng' => 1,
  ),
  242 => 
  array (
    'iso' => 'VU',
    'iso3' => 'VUT',
    'iso_num' => '548',
    'country' => 'Vanuatu',
    'capital' => 'Port Vila',
    'continent' => 'OC',
    'country_zh_cn' => '瓦努阿图',
    'latitude' => '-17.73381',
    'longitude' => '168.32188',
    'capital_latlng' => 1,
  ),
  243 => 
  array (
    'iso' => 'WF',
    'iso3' => 'WLF',
    'iso_num' => '876',
    'country' => 'Wallis and Futuna',
    'capital' => 'Mata Utu',
    'continent' => 'OC',
    'country_zh_cn' => '瓦利斯和富圖納群島',
    'latitude' => '-13.28163',
    'longitude' => '-176.17453',
    'capital_latlng' => 1,
  ),
  244 => 
  array (
    'iso' => 'WS',
    'iso3' => 'WSM',
    'iso_num' => '882',
    'country' => 'Samoa',
    'capital' => 'Apia',
    'continent' => 'OC',
    'country_zh_cn' => '萨摩亚',
    'latitude' => '-13.83333',
    'longitude' => '-171.76666',
    'capital_latlng' => 1,
  ),
  245 => 
  array (
    'iso' => 'YE',
    'iso3' => 'YEM',
    'iso_num' => '887',
    'country' => 'Yemen',
    'capital' => 'Sanaa',
    'continent' => 'AS',
    'country_zh_cn' => '也门',
    'latitude' => '15.35472',
    'longitude' => '44.20667',
    'capital_latlng' => 1,
  ),
  246 => 
  array (
    'iso' => 'YT',
    'iso3' => 'MYT',
    'iso_num' => '175',
    'country' => 'Mayotte',
    'capital' => 'Mamoudzou',
    'continent' => 'AF',
    'country_zh_cn' => '马约特',
    'latitude' => '-12.78234',
    'longitude' => '45.22878',
    'capital_latlng' => 1,
  ),
  247 => 
  array (
    'iso' => 'ZA',
    'iso3' => 'ZAF',
    'iso_num' => '710',
    'country' => 'South Africa',
    'capital' => 'Pretoria',
    'continent' => 'AF',
    'country_zh_cn' => '南非',
    'latitude' => '-25.74486',
    'longitude' => '28.18783',
    'capital_latlng' => 1,
  ),
  248 => 
  array (
    'iso' => 'ZM',
    'iso3' => 'ZMB',
    'iso_num' => '894',
    'country' => 'Zambia',
    'capital' => 'Lusaka',
    'continent' => 'AF',
    'country_zh_cn' => '赞比亚',
    'latitude' => '-15.40669',
    'longitude' => '28.28713',
    'capital_latlng' => 1,
  ),
  249 => 
  array (
    'iso' => 'ZW',
    'iso3' => 'ZWE',
    'iso_num' => '716',
    'country' => 'Zimbabwe',
    'capital' => 'Harare',
    'continent' => 'AF',
    'country_zh_cn' => '津巴布韦',
    'latitude' => '-17.82772',
    'longitude' => '31.05337',
    'capital_latlng' => 1,
  ),
  250 => 
  array (
    'iso' => 'CS',
    'iso3' => 'SCG',
    'iso_num' => '891',
    'country' => 'Serbia and Montenegro',
    'capital' => 'Belgrade',
    'continent' => 'EU',
    'country_zh_cn' => '',
  ),
  251 => 
  array (
    'iso' => 'AN',
    'iso3' => 'ANT',
    'iso_num' => '530',
    'country' => 'Netherlands Antilles',
    'capital' => 'Willemstad',
    'continent' => 'NA',
    'country_zh_cn' => '',
    'latitude' => '12.1084',
    'longitude' => '-68.93354',
    'capital_latlng' => 1,
  ),
);
return $country;