<?php
use \sy\base\Router;
?>
<!DOCTYPE html>
<html>
<head>
	<title>链接 - SYBlog</title>
	<?php $this->display('common/header'); ?>
</head>
<body>
	<?php $this->display('common/navbar'); ?>
	<div class="page-content">
		<h2 class="title">链接</h2>
		<table class="striped">
			<thead><tr><th>标题</th><th class="action">操作</th></tr></thead>
			<tbody id="list"></tbody>
		</table>
		<ul id="page" class="pagination"></ul>
	</div>
	<div class="fixed-action-btn">
		<button id="link_add" class="waves-effect waves-circle waves-light btn-floating btn-large red"><i class="mdi-add"></i></button>
	</div>
	<div id="link_form" class="modal">
		<div class="modal-content">
			<h4 id="link_form_title"></h4>
			<input type="hidden" id="link_id"/>
			<div class="row">
				<div class="input-field col s12">
					<input id="title" type="text"/>
					<label for="title">标题</label>
				</div>
				<div class="input-field col s12">
					<input id="rel" type="text"/>
					<label for="rel">标签</label>
				</div>
				<div class="input-field col s12">
					<input id="url" type="text"/>
					<label for="url">URL</label>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<a id="link_submit" class="modal-action modal-close waves-effect btn-flat">保存</a>
			<a class="modal-action modal-close waves-effect btn-flat">取消</a>
		</div>
	</div>
	<script>
	window.sy = {
		"url": {
			"list": "<?=Router::createUrl('admin/link/list', 'json')?>",
			"ajaxAdd": "<?=Router::createUrl('admin/link/add', 'json')?>",
			"ajaxEdit": "<?=Router::createUrl('admin/link/edit', 'json')?>",
			"ajaxDel": "<?=Router::createUrl('admin/link/del', 'json')?>",
		},
		"page": "Link"
	};
	</script>
	<?php $this->display('common/footer'); ?>
</body>
</html>