(function(n){"object"==typeof exports&&"object"==typeof module?n(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],n):n(CodeMirror)})(function(n){n.defineMode("rust",function(){function p(a,b){w=a;return b}function n(a,b){var e=a.next();if('"'==e)return b.tokenize=W,b.tokenize(a,b);if("'"==e){w="atom";if(a.eat("\\"))return a.skipTo("'")?(a.next(),"string"):"error";a.next();return a.eat("'")?"string":"error"}if("/"==e){if(a.eat("/"))return a.skipToEnd(),
"comment";if(a.eat("*"))return b.tokenize=F(1),b.tokenize(a,b)}if("#"==e){if(a.eat("["))return w="open-attr",null;a.eatWhile(/\w/);return p("macro","meta")}if(":"==e&&a.match(":<"))return p("op",null);if(e.match(/\d/)||"."==e&&a.eat(/\d/))return e=!1,a.match(/^x[\da-f]+/i)||a.match(/^b[01]+/)||(a.eatWhile(/\d/),a.eat(".")&&(e=!0,a.eatWhile(/\d/)),a.match(/^e[+\-]?\d+/i)&&(e=!0)),e?a.match(/^f(?:32|64)/):a.match(/^[ui](?:8|16|32|64)/),p("atom","number");if(e.match(/[()\[\]{}:;,]/))return p(e,null);
if("-"==e&&a.eat(">"))return p("->",null);if(e.match(L))return a.eatWhile(L),p("op",null);a.eatWhile(/\w/);c=a.current();return a.match(/^::\w/)?(a.backUp(1),p("prefix","variable-2")):b.keywords.propertyIsEnumerable(c)?p(b.keywords[c],c.match(/true|false/)?"atom":"keyword"):p("name","variable")}function W(a,b){for(var e,c=!1;e=a.next();){if('"'==e&&!c)return b.tokenize=n,p("atom","string");c=!c&&"\\"==e}return p("op","string")}function F(a){return function(b,e){for(var c=null,d;d=b.next();){if("/"==
d&&"*"==c)if(1==a){e.tokenize=n;break}else return e.tokenize=F(a-1),e.tokenize(b,e);if("*"==d&&"/"==c)return e.tokenize=F(a+1),e.tokenize(b,e);c=d}return"comment"}}function f(){for(var a=arguments.length-1;0<=a;a--)d.cc.push(arguments[a])}function b(){f.apply(null,arguments);return!0}function h(a,b){var e=function(){var e=d.state;e.lexical={indented:e.indented,column:d.stream.column(),type:a,prev:e.lexical,info:b}};e.lex=!0;return e}function g(){var a=d.state;a.lexical.prev&&(")"==a.lexical.type&&
(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function t(){d.state.keywords=X}function u(){d.state.keywords=M}function v(a,c){function e(d){return","==d?b(a,e):d==c?b():b(e)}return function(d){return d==c?b():f(a,e)}}function x(a,c){return b(h("stat",c),a,g,m)}function m(a){return"}"==a?b():"let"==a?x(B,"let"):"fn"==a?x(r):"type"==a?b(h("stat"),C,G,g,m):"enum"==a?x(D):"mod"==a?x(N):"iface"==a?x(H):"impl"==a?x(E):"open-attr"==a?b(h("]"),v(k,"]"),g):"ignore"==a||a.match(/[\]\);,]/)?b(m):
f(h("stat"),k,g,G,m)}function G(a){return";"==a?b():f()}function k(a){return"atom"==a||"name"==a?b(I):"{"==a?b(h("}"),Y,g):a.match(/[\[\(]/)?z(a,k):a.match(/[\]\)\};,]/)?f():"if-style"==a?b(k,k):"else-style"==a||"op"==a?b(k):"for"==a?b(y,O,Z,k,k):"alt"==a?b(k,aa):"fn"==a?b(r):"macro"==a?b(ba):b()}function I(a){return"."==c?b(ca):"::<"==c?b(q,I):"op"==a||":"==c?b(k):"("==a||"["==a?z(a,k):f()}function ca(){return c.match(/^\w+$/)?(d.marked="variable",b(I)):f(k)}function Y(a){if("op"==a){if("|"==c)return b(J,
g,h("}","block"),m);if("||"==c)return b(g,h("}","block"),m)}return"mutable"==c||c.match(/^\w+$/)&&":"==d.stream.peek()&&!d.stream.match("::",!1)?f(P(k)):f(m)}function P(a){function f(e){return"mutable"==c||"with"==c?(d.marked="keyword",b(f)):c.match(/^\w*$/)?(d.marked="variable",b(f)):":"==e?b(a,f):"}"==e?b():b(f)}return f}function J(a){return"name"==a?(d.marked="def",b(J)):"op"==a&&"|"==c?b():b(J)}function B(a){return a.match(/[\]\)\};]/)?b():"="==c?b(k,Q):","==a?b(B):f(y,O,B)}function Q(a){return a.match(/[\]\)\};,]/)?
f(B):f(k,Q)}function O(a){return":"==a?b(t,l,u):f()}function Z(a){return"name"==a&&"in"==c?(d.marked="keyword",b()):f()}function r(a){return"@"==c||"~"==c?(d.marked="keyword",b(r)):"name"==a?(d.marked="def",b(r)):"<"==c?b(q,r):"{"==a?f(k):"("==a?b(h(")"),v(R,")"),g,r):"->"==a?b(t,l,u,r):";"==a?b():b(r)}function C(a){return"name"==a?(d.marked="def",b(C)):"<"==c?b(q,C):"="==c?b(t,l,u):b(C)}function D(a){return"name"==a?(d.marked="def",b(D)):"<"==c?b(q,D):"="==c?b(t,l,u,G):"{"==a?b(h("}"),t,K,u,g):b(D)}
function K(a){if("}"==a)return b();if("("==a)return b(h(")"),v(l,")"),g,K);c.match(/^\w+$/)&&(d.marked="def");return b(K)}function N(a){return"name"==a?(d.marked="def",b(N)):"{"==a?b(h("}"),m,g):f()}function H(a){return"name"==a?(d.marked="def",b(H)):"<"==c?b(q,H):"{"==a?b(h("}"),m,g):f()}function E(a){return"<"==c?b(q,E):"of"==c||"for"==c?(d.marked="keyword",b(l,E)):"name"==a?(d.marked="def",b(E)):"{"==a?b(h("}"),m,g):f()}function q(){return">"==c?b():","==c?b(q):":"==c?b(l,q):f(l,q)}function R(a){return"name"==
a?(d.marked="def",b(R)):":"==a?b(t,l,u):f()}function l(a){return"name"==a?(d.marked="variable-3",b(S)):"mutable"==c?(d.marked="keyword",b(l)):"atom"==a?b(S):"op"==a||"obj"==a?b(l):"fn"==a?b(T):"{"==a?b(h("{"),P(l),g):z(a,l)}function S(){return"<"==c?b(q):f()}function T(a){return"("==a?b(h("("),v(l,")"),g,T):"->"==a?b(l):f()}function y(a){return"name"==a?(d.marked="def",b(U)):"atom"==a?b(U):"op"==a?b(y):a.match(/[\]\)\};,]/)?f():z(a,y)}function U(a){return"op"==a&&"."==c?b():"to"==c?(d.marked="keyword",
b(y)):f()}function aa(a){return"{"==a?b(h("}","alt"),A,g):f()}function A(a){return"}"==a?b():"|"==a?b(A):"when"==c?(d.marked="keyword",b(k,V)):a.match(/[\]\);,]/)?b(A):f(y,V)}function V(a){return"{"==a?b(h("}","alt"),m,g,A):f(A)}function ba(a){return a.match(/[\[\(\{]/)?z(a,k):f()}function z(a,c){return"["==a?b(h("]"),v(c,"]"),g):"("==a?b(h(")"),v(c,")"),g):"{"==a?b(h("}"),v(c,"}"),g):b()}var M={"if":"if-style","while":"if-style",loop:"else-style","else":"else-style","do":"else-style",ret:"else-style",
fail:"else-style","break":"atom",cont:"atom","const":"let",resource:"fn",let:"let",fn:"fn","for":"for",alt:"alt",iface:"iface",impl:"impl",type:"type","enum":"enum",mod:"mod",as:"op","true":"atom","false":"atom",assert:"op",check:"op",claim:"op","native":"ignore",unsafe:"ignore","import":"else-style","export":"else-style",copy:"op",log:"op",log_err:"op",use:"op",bind:"op",self:"atom",struct:"enum"},X=function(){for(var a={fn:"fn",block:"fn",obj:"obj"},b="bool uint int i8 i16 i32 i64 u8 u16 u32 u64 float f32 f64 str char".split(" "),
c=0,d=b.length;c<d;++c)a[b[c]]="atom";return a}(),L=/[+\-*&%=<>!?|\.@]/,w,c,d={state:null,stream:null,marked:null,cc:null};g.lex=t.lex=u.lex=!0;return{startState:function(){return{tokenize:n,cc:[],lexical:{indented:-4,column:0,type:"top",align:!1},keywords:M,indented:0}},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation());if(a.eatSpace())return null;w=c=null;var e=b.tokenize(a,b);if("comment"==e)return e;b.lexical.hasOwnProperty("align")||
(b.lexical.align=!0);if("prefix"==w)return e;c||(c=a.current());a:{var f=b.cc;d.state=b;d.stream=a;d.marked=null;for(d.cc=f;;)if((f.length?f.pop():m)(w)){for(;f.length&&f[f.length-1].lex;)f.pop()();e=d.marked||e;break a}}return e},indent:function(a,b){if(a.tokenize!=n)return 0;var c=b&&b.charAt(0),d=a.lexical,f=d.type,c=c==f;return"stat"==f?d.indented+4:d.align?d.column+(c?0:1):d.indented+(c?0:"alt"==d.info?2:4)},electricChars:"{}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//",fold:"brace"}});
n.defineMIME("text/x-rustsrc","rust")});