<div class="content-wrapper">

    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('customer', ['action'=> 'add']);?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <?=$this->translate('添加客户')?></a>
            <?=$this->HelpUrl('customerList')?>
        </h1>

    </section>

    <section class="content">
        <?=$this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr class="erp-bg-thead">
                                    <th width="2%"><input type="checkbox" class="minimal select-all-checkbox"></th>
                                    <th>ID</th>
                                    <th><?=$this->translate('客户名称')?></th>
                                    <th><?=$this->translate('客户编码')?></th>
                                    <th><?=$this->translate('客户分类')?></th>
                                    <th width="8%"><?=$this->translate('排序')?></th>
                                    <th width="18%"><?=$this->translate('操作')?></th>
                                </tr>
                                <?php
                                $sForm = $this->searchForm;
                                $sForm->prepare();
                                ?>
                                <?= $this->form()->openTag($sForm); ?>
                                <tr>
                                    <td></td>
                                    <td>
                                        <p>
                                            <?= $this->formElement($sForm->get('start_id')); ?>
                                        </p>
                                        <div>
                                            <?= $this->formElement($sForm->get('end_id')); ?>
                                        </div>
                                        <?=$this->formElementErrors($sForm->get('start_id'), ['class'=>'error-message']);?>
                                        <?=$this->formElementErrors($sForm->get('end_id'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?= $this->formElement($sForm->get('customer_name')); ?>
                                        <?=$this->formElementErrors($sForm->get('customer_name'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?= $this->formElement($sForm->get('customer_code')); ?>
                                        <?=$this->formElementErrors($sForm->get('customer_code'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?= $this->formElement($sForm->get('customer_category_id')); ?>
                                        <?=$this->formElementErrors($sForm->get('customer_category_id'), ['class'=>'error-message']);?>
                                    </td>
                                    <td></td>
                                    <td>
                                        <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i></button>
                                        <?php if(!empty(array_filter($sForm->getData()))) { ?>
                                            <a href="<?=$this->url('customer');?>" class="btn btn-default btn-sm"><i class="fa fa-reply"></i></a>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?= $this->form()->closeTag(); ?>
                                </thead>

                                <form method="post" action="<?=$this->url('customer', ['action' => 'updateAll']);?>" name="edit-all-form" id="edit-all-form">
                                <?php if($this->customerList) foreach ($this->customerList as $customer) { ?>
                                    <tr>
                                        <td><input  name="select_id[]" value="<?=$customer->getCustomerId()?>" type="checkbox" class="minimal"></td>
                                        <td><?= $customer->getCustomerId()?></td>
                                        <td><?= $this->escapeHtml($customer->getCustomerName())?></td>
                                        <td><?= $this->escapeHtml($customer->getCustomerCode())?></td>
                                        <td><?= $this->escapeHtml($customer->getCustomerCategory()->getCustomerCategoryName())?></td>
                                        <td><input type="text" name="customer_sort[<?=$customer->getCustomerId()?>]" value="<?= $customer->getCustomerSort()?>" class="form-control input-sm"></td>
                                        <td>
                                            <a href="<?= $this->url('customer',
                                                ['action'=>'edit', 'id'=>$customer->getCustomerId()]); ?>"
                                               class="btn btn-xs btn-success"><i class="fa fa-pencil"></i> <?=$this->translate('编辑')?>
                                            </a>

                                            <a href="javascript:;" onclick="deleteConfirm('<?php echo $this->translate('您确实要删除该客户吗？'); ?>', '<?= $this->url('customer', ['action'=>'delete', 'id'=>$customer->getCustomerId()], ['query' => ['qToken' => $this->adminHelper()->getCsrfValue()]]); ?>');" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash"></i> <?=$this->translate('删除')?>
                                            </a>

                                        </td>
                                    </tr>
                                <?php } ?>
                                <tfoot>
                                    <tr>
                                        <td colspan="7">
                                            <input type="checkbox" class="minimal select-all-checkbox"> <?=$this->translate('全选')?>
                                            <select name="editAllState">
                                                <option value=""><?=$this->translate('选择状态')?></option>
                                                <option value="sort"><?=$this->translate('更新排序')?></option>
                                            </select>
                                            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('更新')?></button>

                                            <?= $this->paginationControl($this->customerList,
                                                'Sliding',
                                                'layout/page',
                                                ['route' => 'supplier']); ?>
                                        </td>
                                    </tr>
                                </tfoot>
                                </form>
                            </table>
                    </div>

                </div>

            </div>
        </div>

    </section>
</div>