<?php
$settings = array(
	'formId' => 'userEditor',
	'form' => array(
		'action' => '',
		'method' => 'post',
		'class' => array(),
		'accept-charset' => 'utf-8',
		'role' => 'form',
		'id' => 'userEditor',
	),
	'sex' => array(
		'label' => '性别',
		'userOptions' => array(),
		'error' => '',
		'description' => '用户名',
		'field' => 'list',
		'widget' => 'Select',
		'options' => array(
			1 => '男',
			2 => '女',
			3 => '保密',
		),
		'validate' => array(),
		'attributes' => array(),
		'required' => true,
	),
	'description' => array(
		'label' => '描述',
		'userOptions' => array(),
		'error' => '',
		'description' => '用户描述',
		'field' => 'textLong',
		'widget' => 'Textarea',
		'validate' => array(),
		'attributes' => array(),
		'required' => true,
	),
	'site_name' => array(
		'label' => '站点名称',
		'description' => '站点名称',
		'field' => 'string',
		'error' => '',
		'widget' => 'Text',
		'required' => true,
		'validate' => array(),
		'attributes' => array(
			'class' => 'width-100',
		),
	),
	'site' => array(
		'label' => '站点地址',
		'description' => '站点地址',
		'field' => 'string',
		'error' => '',
		'widget' => 'Text',
		'required' => 'yes',
		'validate' => array(),
		'attributes' => array(
			'class' => 'width-100',
		),
	),
	'address' => array(
		'label' => '所在地',
		'error' => '',
		'description' => '所在地',
		'field' => 'string',
		'widget' => 'Text',
		'options' => array(),
		'validate' => array(),
		'attributes' => array(),
	),
	'settings' => array(
		'save' => array(
			'\Modules\User\Library\Common',
			'editor',
		),
	),
);
