<?php
use \sy\base\i18n;
use \sy\base\Router;
use \blog\libs\Html;
?>
<!DOCTYPE html>
<html>
<head>
	<title>SYBlog</title>
	<?php $this->display('common/header'); ?>
</head>
<body>
	<?php $this->display('common/navbar'); ?>
	<div class="page-content home">
		<h2><?=i18n::get('next')?></h2>
		<a href="<?=Router::createUrl('admin/article/write')?>" class="waves-effect waves-light btn-large"><?=i18n::get('write_article')?></a>
		<a href="<?=Router::createUrl('admin/article/list')?>" class="waves-effect waves-light btn-large">文章列表</a>
		<a href="<?=Router::createUrl('admin/meta/list')?>" class="waves-effect waves-light btn-large">标签管理</a>
		<a href="<?=Router::createUrl('admin/link/list')?>" class="waves-effect waves-light btn-large">链接管理</a>
		<a href="<?=Router::createUrl('admin/option/basic')?>" class="waves-effect waves-light btn-large">选项</a>
		<h2><?=i18n::get('or')?></h2>
		<a href="<?=Router::createUrl(['index/go/help', 'q' => 'how_to_use'])?>" class="waves-effect waves-light btn-large">使用帮助</a>
		<a href="https://w.sylibs.com/go/blog/issue.html" class="waves-effect waves-light btn-large">建议和反馈</a>
	</div>
	<script>window.sy={"page":"home"};</script>
	<?php $this->display('common/footer'); ?>
</body>
</html>