<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dicts"
 *
 * Auto generated by Extension Builder 2019-09-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '数据字典',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Shichang Yang',
    'author_email' => 'yangshichang@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
