<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "teamlist"
 *
 * Auto generated by Extension Builder 2019-07-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '团队列表',
    'description' => '团队列表插件',
    'category' => 'plugin',
    'author' => 'Yangshichang',
    'author_email' => 'Yangshichang@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
