<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>

<iframe src="http://hiblog.azurewebsites.net/server/community/index" scrolling="no" style="width:100%; height:800px; border:0; padding:0; margin:0; scoller:none"></iframe>

<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/basic.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage', ['nav'=>'community']) ?>