<?php $t_url = s_url('?c=forum&a=topic_show&topic_id='.$topic_l['id']) ?>
<div class="col-md-4 col-sm-6">
	<div class="forum-topic">
		<a target="_blank" href="<?php echo $t_url ?>"> 
			<div class="topic-icon<?php if (2 == $topic_l['start_t'] && time() > $topic_l['start_t_s']) echo ' desaturate' ?>" style="background-image:url('<?php echo $topic_l['icon_url'] ?>')"></div>
		</a>
		<div class="subject">
			<p class="title">
			<?php if (1 == $topic_l['digest']) { ?><span class="glyphicon glyphicon-fire"></span> <?php } ?>
			<a target="_blank" href="<?php echo $t_url ?>"><?php echo $topic_l['title'] ?></a> 
			<?php echo (time()-24*3600 < $topic_l['l_r_at']) ? '<span class="label label-default">热</span>' : null ?>
			<?php echo (time()-24*3600 < $topic_l['c_at']) ? '<span class="label label-success">新</span>' : null ?>
			<?php echo (date('Ymd', time()) == $topic_l['today']) ? '<b class="label label-warning">'.$topic_l['today_up_c'].'</b>' : null ?>
			<?php if (0 < $topic_l['pay']) { ?>
			<span class="label label-danger">$ <?php echo intval($topic_l['pay']) ?></span>
			<?php } ?>
			</p>
			<p class="price">
			<a class="btn btn-success pull-right order-c-s hidden-xs" target="_blank" href="<?php echo $t_url ?>"> 看详情 </a>
			<b><?php if (0 != $topic_l['price']) { ?><?php if (0 != $topic_l['price_org']) { ?>
			<s>¥</s><?php if (10000 > $topic_l['price']) echo $topic_l['price']/1; else echo ($topic_l['price']/10000).' 万'; ?><?php } else { ?>
			<?php echo number_format($topic_l['price'], 1) ?> 折<?php } ?><?php } ?></b> 
			<?php if (0 != $topic_l['price_org'] && $topic_l['price'] != $topic_l['price_org']) { ?>
			<small><s>¥</s><?php if (10000 > $topic_l['price_org']) echo $topic_l['price_org']/1; else echo ($topic_l['price_org']/10000).' 万'; ?></small><?php } ?>
			</p>
			<div class="num hidden-xs">
				<span>评价<em><?php echo $topic_l['reply_c'] ?></em></span>
				<span>查看<em><?php echo $topic_l['view_c'] ?></em></span>
			</div>
		</div>
	</div>
</div>
