<?php 

$price = @doubleval($_POST['price']);
$price_org = @doubleval($_POST['price_org']);
$phone = @filter_var($_POST['phone'], FILTER_SANITIZE_STRING);

?>
<div class="form-group">
	<label class="col-md-2 control-label">现价</label>  
	<div class="col-md-9">
		<input name="price" type="text" placeholder="0.00" class="form-control input-md" value="<?php echo $price ?>" onblur="$('input[name=orders_p]').val($(this).val())">
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">原价</label>  
	<div class="col-md-9">
		<input name="price_org" type="text" placeholder="0.00" class="form-control input-md" value="<?php echo $price_org ?>">
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">电话</label>  
	<div class="col-md-9">
		<input name="phone" type="text" placeholder="电话" class="form-control input-md" required="" value="<?php echo $phone ?>">
	</div>
</div>
