<?php 

$topic_ext = dt_query_one("SELECT * FROM forum_topic_ext_1 WHERE id = $topic_id");
if (!$topic_ext) die('获取forum_topic_ext数据失败！');

?>
<div class="form-group">
	<label class="col-md-2 control-label">现价</label>  
	<div class="col-md-9">
		<input name="price" type="text" placeholder="0.00" class="form-control input-md" value="<?php echo $topic_ext['price'] ?>" onblur="$('input[name=orders_p]').val($(this).val())">
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">原价</label>  
	<div class="col-md-9">
		<input name="price_org" type="text" placeholder="0.00" class="form-control input-md" value="<?php echo $topic_ext['price_org'] ?>">
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">电话</label>  
	<div class="col-md-9">
		<input name="phone" type="text" placeholder="电话" class="form-control input-md" required="" value="<?php echo $topic_ext['phone'] ?>">
	</div>
</div>
