<link rel="stylesheet" href="forum/forum_ext/ext_1/topic_list.css">
<div class="container">
	<div class="forum-topic-list-ext-1">
		<div class="row clearfix">
			<div class="col-md-12 column">
				<hr class="solid">
				<ul id="order_filter" class="nav nav-pills nav-pills-sm pull-right">
					<li><a href="javascript:do_order_filter(0)">时间</a></li>
					<li class="hidden-xs"><a href="javascript:do_order_filter(1)">热度</a></li>                       
					<li><a href="javascript:do_order_filter(2)">订单</a></li>                       
				</ul>
				<ul id="digest_filter" class="nav nav-pills nav-pills-sm">
					<li><a href="javascript:do_digest_filter(0)">全部</a></li>
					<li><a href="javascript:do_digest_filter(1)">推荐</a></li>                       
					<li class="hidden-lg"><a href="javascript:do_digest_filter(2)">附近</a></li>                       
				</ul>
			</div>
			<?php if (1 == $page) { ?>
			<?php while($topic_l = mysql_fetch_array($topic_tops)) { ?>
			<?php require('topic_list_item.phtml') ?>	
			<?php } ?>
			<?php } ?>
			<?php while($topic_l = mysql_fetch_array($topics)) { ?>
			<?php require('topic_list_item.phtml') ?>	
			<?php } ?>
		</div>
	</div>
</div>
