<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "invoice"
 *
 * Auto generated by Extension Builder 2019-09-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '发票管理',
    'description' => '发票申请',
    'category' => 'plugin',
    'author' => 'Shichang Yang',
    'author_email' => 'yangshichang@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
