<div class="content-wrapper">
    <?php
    $form = $this->form;
    $form->prepare();

    $form->get('brandName')->setAttributes([
        'placeholder' => $this->translate('品牌名称')
    ]);

    $form->get('brandCode')->setAttributes([
        'placeholder' => $this->translate('品牌编码')
    ]);

    $form->get('brandSort')->setAttributes([
        'placeholder' => $this->translate('排序')
    ]);

    ?>
    <?= $this->form()->openTag($form); ?>
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('brand');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?=$this->translate('返回品牌列表')?></a>
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('保存品牌')?></button>
            <?=(isset($brand) ? $this->HelpUrl('brandEdit') : $this->HelpUrl('brandAdd'))?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=((isset($brand) && $brand->getBrandId()) ? $this->translate('编辑品牌') : $this->translate('添加品牌'))?></h3>
                    </div>

                    <div class="box-body">
                        <?=$this->formElementErrors($form->get('dberp_csrf'), ['class'=>'error-message']); ?>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('品牌编码')?></label>
                            <div class="col-sm-6">
                                <?= $this->formElement($form->get('brandCode')); ?>
                                <?= $this->formElementErrors($form->get('brandCode'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('品牌名称')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-6">
                                <?= $this->formElement($form->get('brandName')); ?>
                                <?= $this->formElementErrors($form->get('brandName'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('排序')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-3">
                                <?= $this->formElement($form->get('brandSort')); ?>
                                <?= $this->formElementErrors($form->get('brandSort'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                    </div>

                    <div>
                        <div class="box-footer">
                            <?=$this->formElement($form->get('dberp_csrf')); ?>
                            <button type="submit" class="btn btn-primary col-md-offset-2"><i class="fa fa-check"></i> <?=$this->translate('保存品牌')?></button>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </section>
    <?= $this->form()->closeTag(); ?>

</div>
<script>
    $(document).ready(function() {
        $("#<?=$form->getName()?>").validate({
            rules: {
                brandName: {
                    required: true
                },
                brand_sort: {
                    required: true,
                    number: true,
                    min: 1
                }
            },
            messages: {
                brandName: {
                    required: "<?=$this->translate('品牌名称不能为空！')?>"
                },
                brandSort: {
                    required: "<?=$this->translate('排序不能为空！')?>",
                    number: "<?=$this->translate('排序必须为数字！')?>",
                    min: "<?=$this->translate('排序最小为1！')?>"
                }
            }
        });
    });
</script>
