<div class="content-wrapper">

    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('brand', ['action'=> 'add']);?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <?=$this->translate('添加品牌')?></a>
            <?=$this->HelpUrl('brandList')?>
        </h1>

    </section>

    <section class="content">
        <?=$this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <form method="post" action="<?=$this->url('brand', ['action' => 'updateAll']);?>" name="edit-all-form" id="edit-all-form">
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <thead>
                            <tr class="erp-bg-thead">
                                <th width="2%"><input type="checkbox" class="minimal select-all-checkbox"></th>
                                <th>ID</th>
                                <th><?=$this->translate('品牌名称')?></th>
                                <th><?=$this->translate('品牌编码')?></th>
                                <th width="8%"><?=$this->translate('排序')?></th>
                                <th width="18%"><?=$this->translate('操作')?></th>
                            </tr>
                            </thead>

                            <?php if($this->brandList) foreach ($this->brandList as $brand) { ?>
                                <tr>
                                    <td><input  name="select_id[]" value="<?=$brand->getBrandId()?>" type="checkbox" class="minimal"></td>
                                    <td><?= $brand->getBrandId()?></td>
                                    <td><?= $this->escapeHtml($brand->getBrandName())?></td>
                                    <td><?= $this->escapeHtml($brand->getBrandCode())?></td>
                                    <td><input type="text" name="brand_sort[<?=$brand->getBrandId()?>]" value="<?= $brand->getBrandSort()?>" class="form-control input-sm"></td>
                                    <td>
                                        <a href="<?= $this->url('brand',
                                            ['action'=>'edit', 'id'=>$brand->getBrandId()]); ?>"
                                           class="btn btn-xs btn-success"><i class="fa fa-pencil"></i> <?=$this->translate('编辑')?>
                                        </a>

                                        <a href="javascript:;" onclick="deleteConfirm('<?php echo $this->translate('您确实要删除该商品品牌吗？'); ?>', '<?= $this->url('brand', ['action'=>'delete', 'id'=>$brand->getBrandId()], ['query' => ['qToken' => $this->adminHelper()->getCsrfValue()]]); ?>');" class="btn btn-xs btn-danger">
                                            <i class="fa fa-trash"></i> <?=$this->translate('删除')?>
                                        </a>

                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        <input type="checkbox" class="minimal select-all-checkbox"> <?=$this->translate('全选')?>
                        <select name="editAllState">
                            <option value=""><?=$this->translate('选择状态')?></option>
                            <option value="sort"><?=$this->translate('更新排序')?></option>
                        </select>
                        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('更新')?></button>
                    </div>
                    </form>
                </div>

            </div>
        </div>

    </section>
</div>