<?php

/**
 *　前端考勤api
 * Date: 16-9-29
 * Time: 下午10:48
 * author :李华 yehong0000@163.com
 */
class ApiController extends system\controllers\Api {
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 考勤资源
     */
    public function worksAction() {
        $fun = sprintf('%sWork', $this->getRequest()->getMethod());
        $this->getResponse()->setBody($this->packing(0, 'success', call_user_func(
            [
                'app\work\Factory',
                $fun
            ],
            self::getParams()
        ), null, null));
    }
    /**
     * 考勤资源以天计
     */
    public function clocksAction() {
        $fun = sprintf('%sClock', $this->getRequest()->getMethod());
        $this->getResponse()->setBody($this->packing(0, 'success', call_user_func(
            [
                'app\work\Factory',
                $fun
            ],
            self::getParams()
        ), null, null));
    }

    /**
     * 打卡详细
     */
    public function workListsAction(){
        $fun = sprintf('%sWorkLists', $this->getRequest()->getMethod());
        $this->getResponse()->setBody($this->packing(0, 'success', call_user_func(
            [
                'app\work\Factory',
                $fun
            ],
            self::getParams()
        ), null, null));
    }
}