<?php return array (
  'site_name' => 'قەيسەر بىلوگى',
  'site_title' => 'كومپيوتېر ساھەسىدىكى يېڭىلىقلار ۋە بىلىملەر جەمگاھى',
  'site_keywords' => 'قەيسەر،بىلوگ،qeyser',
  'site_description' => 'كومپيوتېر ساھەسىدىكى يېڭىلىقلار ۋە بىلىملەر جەمگاھى',
  'site_closed' => '1',
  'default_template' => 'default',
  'index_page' => '3',
  'cate_page' => '5',
  'email' => 'your@domain.com',
  'mail_service' => '0',
  'mail_host' => 'smtp.domain.com',
  'mail_port' => '25',
  'mail_ssl' => '0',
  'mail_username' => 'قەيسەر مۇتەللىپ',
  'mail_password' => '123456',
  'blog_version' => 'v1.6  20170724',
  'icp' => 'QQ群: 6364475',
  'tel' => '0998-7845106',
  'qq' => '125790757',
)?>