<div class="content-wrapper">

    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('accounts-receivable');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?=$this->translate('返回应收账款列表')?></a>
            <?=$this->HelpUrl('accountsReceivableShow')?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=$this->translate('应付账款详情');?></h3>
                    </div>

                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('销售单号')?>：</b><?=$this->escapeHtml($this->orderInfo->getSalesOrderSn());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('订单状态')?>：</b><?=$this->salesHelper()->salesOrderState($this->orderInfo->getSalesOrderState(), 2);?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('付款方式')?>：</b><?=$this->salesHelper()->orderReceivables($this->orderInfo->getReceivablesCode());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('客户')?>：</b><?=$this->escapeHtml($this->orderInfo->getOneCustomer()->getCustomerName());?>
                                </div>
                            </div>
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('客户联系人')?>：</b><?=$this->escapeHtml($this->orderInfo->getCustomerContacts());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('客户手机')?>：</b><?=$this->escapeHtml($this->orderInfo->getCustomerPhone());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('客户座机')?>：</b><?=$this->escapeHtml($this->orderInfo->getCustomerTelephone());?>
                                </div>
                            </div>
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('收货地址')?>：</b><?=$this->escapeHtml($this->orderInfo->getCustomerAddress());?>
                                </div>
                            </div>
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('备注')?>：</b><?=$this->escapeHtml($this->orderInfo->getSalesOrderInfo());?>
                                </div>
                            </div>
                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?=$this->translate('销售商品')?></h4>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="15%"><?=$this->translate('商品编号')?></th>
                                    <th width="20%"><?=$this->translate('商品名称')?></th>
                                    <th><?=$this->translate('商品规格')?></th>
                                    <th><?=$this->translate('单位')?></th>
                                    <th><?=$this->translate('销售单价')?></th>
                                    <th><?=$this->translate('销售数量')?></th>
                                    <th width="10%"><?=$this->translate('销售总价')?></th>
                                </tr>
                                </thead>


                                <?php
                                foreach ($this->orderGoods as $goodsValue) {
                                    ?>
                                    <tr>
                                        <td><?=$this->escapeHtml($goodsValue->getGoodsNumber());?></td>
                                        <td><?=$this->escapeHtml($goodsValue->getGoodsName());?></td>
                                        <td><?=$this->escapeHtml($goodsValue->getGoodsSpec());?></td>
                                        <td><?=$this->escapeHtml($goodsValue->getGoodsUnit());?></td>
                                        <td><?=$this->erpCurrencyFormat($goodsValue->getSalesGoodsPrice());?></td>
                                        <td><?=$this->escapeHtml($goodsValue->getSalesGoodsSellNum());?></td>
                                        <td><?=$this->erpCurrencyFormat($goodsValue->getSalesGoodsAmount());?></td>
                                    </tr>
                                <?php } ?>

                                <tfoot>
                                <tr>
                                    <td colspan="5"></td>
                                    <td colspan="2" class="text-right"><b><?=$this->translate('销售金额合计')?>：</b><span id="order-amount"><?=(isset($orderInfo) ? $this->erpCurrencyFormat($orderInfo->getSalesOrderAmount()) : 0)?></span></td>
                                </tr>
                                <tr>
                                    <td colspan="5"></td>
                                    <td colspan="2" class="text-right"><b class="text-green"><?=$this->translate('已收金额合计')?>：</b><?=$this->erpCurrencyFormat($this->receivableInfo->getFinishAmount())?></td>
                                </tr>
                                </tfoot>

                            </table>
                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?=$this->translate('收款记录')?></h4>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="10%"><?=$this->translate('收款时间')?></th>
                                    <th width="10%"><?=$this->translate('收款金额')?></th>
                                    <th width="15%"><?=$this->translate('收款人')?></th>
                                    <th width="10%"><?=$this->translate('收款凭证')?></th>
                                    <th width="30%"><?=$this->translate('收款备注')?></th>
                                    <th width="10%"><?=$this->translate('操作人')?></th>
                                    <th width="15%"><?=$this->translate('操作时间')?></th>
                                </tr>
                                </thead>

                                <?php if($this->receivableLogList) foreach ($this->receivableLogList as $log) { ?>
                                    <tr>
                                        <td><?=date("Y-m-d", $log->getReceivableLogTime())?></td>
                                        <td><?=$this->erpCurrencyFormat($log->getReceivableLogAmount())?></td>
                                        <td><?=$this->escapeHtml($log->getReceivableLogUser())?></td>
                                        <td>
                                            <?php if($log->getReceivableFile()) { ?>
                                                <a href="<?=$this->basePath($log->getReceivableFile())?>" title="<?=$this->translate('点击查看')?>" target="_blank"><i class="fa fa-picture-o"></i></a>
                                            <?php } else echo $this->translate('无') ?>
                                        </td>
                                        <td><?=$this->escapeHtml($log->getReceivableInfo())?></td>
                                        <td><?=$this->escapeHtml($log->getOneAdmin()->getAdminName())?></td>
                                        <td><?=date("Y-m-d H:i:s", $log->getReceivableAddTime())?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>

                    </div>

                </div>


            </div>
        </div>

    </section>

</div>