<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> <?php if($auth_group['id']){?>编辑<?php }else{?>新增<?php }?>用户组
				</div>
				
			</div>
			<div class="portlet-body form">
				<form role="form" action="<?php echo $this->url->get("AuthManager/writeGroup")?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
                <input type="hidden" name="id" value="<?php echo $auth_group['id']?>" />
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">用户组</label>
							<div class="col-md-9">
								<input type="text" name="title" value="<?php echo $auth_group['title']?>" placeholder="用户组名称" class="form-control">
							</div>
						</div>						
						<div class="form-group">
							<label class="col-md-3 control-label">描述</label>
							<div class="col-md-9">
								<textarea rows="3" name="description" class="form-control"><?php echo $auth_group['description']?></textarea>
							</div>
						</div>
						
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>