<?php
namespace CigoAdminLib\Lib;

class CigoGlobal{
    const S_FLAG_SYSTEM_CONFIG_DATA = 'SYSTEM_CONFIG_DATA';//系统配置

    const C_FLAG_PRIVATE_KEY_BEGIN = 'PRIVATE_KEY_BEGIN';
    const C_FLAG_PRIVATE_KEY_END = 'PRIVATE_KEY_END';
    const C_FLAG_PUBLIC_KEY_BEGIN = 'PUBLIC_KEY_BEGIN';
    const C_FLAG_PUBLIC_KEY_END = 'PUBLIC_KEY_END';
    const C_FLAG_AES_METHODS = 'AES_METHODS';
    const C_FLAG_AES_KEY_LEN = 'AES_KEY_LEN';
    const C_FLAG_TOKEN_LEN = 'TOKEN_LEN';
    const C_FLAG_TOKEN_TIMEOUT = 'TOKEN_TIMEOUT';
    const C_FLAG_REQUEST_ALLOWABLE_TIME_INTERVAL = 'REQUEST_ALLOWABLE_TIME_INTERVAL';
}

