#!/bin/sh

set -e

chmod +x {lessfly_userappdir}/bin/lesscreator

install -m 0755 -d {lessfly_userdir}/conf/lesscreator
install -m 0644 -p {lessfly_userappdir}/misc/etc/creator.json {lessfly_userdir}/conf/lesscreator/creator.json

lessfly-env-filter {lessfly_userdir}/conf/lesscreator/creator.json


