<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\common\controller;

use app\admin\model\Admin;
use app\admin\model\Menu;

/**
 * 后台基类-控制器
 * @author 牧羊人
 * @since 2020/7/9
 * Class Backend
 * @package app\common\controller
 */
class Backend extends BaseController
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;
    // 登录ID
    protected $adminId;
    // 登录信息
    protected $adminInfo;
    // 权限
    protected $permission;
    // 请求参数
    protected $param;

    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/9
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 初始化配置
        $this->initConfig();

        // 登录校验
        $this->checkLogin();

        // 权限校验
        $this->checkAuth();
    }

    /**
     * 初始化配置
     * @author 牧羊人
     * @since 2020/7/9
     */
    private function initConfig()
    {
        // 获取系统配置信息
        $this->assign('siteName', SITE_NAME);
        $this->assign('nickName', NICK_NAME);
        $this->assign('version', VERSION);

        // 请求参数
        $this->param = $this->request->param();

        // 分页基础默认值
        defined('PERPAGE') or define('PERPAGE', isset($this->param['limit']) ? $this->param['limit'] : 20);
        defined('PAGE') or define('PAGE', isset($this->param['page']) ? $this->param['page'] : 1);
    }

    /**
     * 校验登录
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @since 2020/7/9
     * @author 牧羊人
     */
    private function checkLogin()
    {
        $noLoginActs = ['Login'];
        if (session('adminId') == null && !in_array($this->request->controller(), $noLoginActs)) {
            $this->redirect('/login/index');
            exit;
        }

        // 登录用户ID
        $adminId = session('adminId');
        $this->adminId = $adminId;

        // 登录用户信息
        $admin_model = new Admin();
        $adminInfo = $admin_model->getInfo($adminId);
        $this->adminInfo = $adminInfo;

        // 数据渲染
        $this->assign("adminId", $this->adminId);
        $this->assign('adminInfo', $this->adminInfo);
        $this->permission = $this->adminInfo['permission'];
    }

    /**
     * 检查权限
     * @return array|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @author 牧羊人
     * @since 2020/7/9
     */
    private function checkAuth()
    {
        if (!in_array($this->request->controller(), ['Login', 'Index'])) {
            // 获取菜单操作权限
            $menuMod = new Menu();
            $requestUrl = strtolower("/" . $this->request->controller() . "/" . $this->request->action());
            $menuInfo = $menuMod->where([
                'type' => 3,
                'url' => $requestUrl,
                'mark' => 1
            ])->find();
            if (!$menuInfo) {
                if (IS_POST || IS_GET) {
                    return message('暂无操作权限', false);
                }
                return $this->render('public/404');
            }

            // 获取节点操作权限
            $funcArr = isset($this->permission[$menuInfo['id']]) ? $this->permission[$menuInfo['id']] : [];
            $funcList = [];
            if (is_array($funcArr)) {
                $keys = array_values($funcArr);
                // 加入当前菜单
                $keys[] = $menuInfo['id'];
                $funcList = $menuMod->where([
                    ['id', 'in', $keys]
                ])->column('permission');
            }
            $this->assign('funcList', $funcList);
            if (!in_array($menuInfo['permission'], $funcList)) {
                if (IS_POST) {
                    return message('暂无操作权限', false);
                }
                return $this->render('public/404');
            }
        }
    }

    /**
     * 数据列表页入口
     * @return mixed
     * @since 2020/7/9
     * @author 牧羊人
     */
    public function index()
    {
        if (IS_POST) {
            $result = $this->service->getList();
            return $result;
        }
        // 默认参数
        $data = func_get_args();
        if (isset($data[0])) {
            foreach ($data[0] as $key => $val) {
                $this->assign($key, $val);
            }
        }
        return $this->render();
    }

    /**
     * 添加或编辑入口
     * @return mixed
     * @since 2020/7/9
     * @author 牧羊人
     */
    public function edit()
    {
        if (IS_POST) {
            $result = $this->service->edit();
            return $result;
        }
        $info = [];
        $id = input("get.id", 0);
        if ($id) {
            $info = $this->model->getInfo($id);
        } else {
            $data = func_get_args();
            if (isset($data[0])) {
                foreach ($data[0] as $key => $val) {
                    $info[$key] = $val;
                }
            }
        }
        $this->assign('info', $info);
        return $this->render();
    }

    /**
     * 详情页入口
     * @return mixed
     * @since 2020/7/9
     * @author 牧羊人
     */
    public function detail()
    {
        if (IS_POST) {
            $result = $this->service->edit();
            return $result;
        }
        $id = input("get.id", 0);
        if ($id) {
            $info = $this->model->getInfo($id);
            $this->assign('info', $info);
        }
        return $this->render();
    }

    /**
     * 模板渲染
     * @param string $tpl 模板地址
     * @param array $data 参数
     * @return mixed
     * @author 牧羊人
     * @date 2019/2/25
     */
    public function render($tpl = "", $data = [])
    {
        return $this->fetch($tpl, $data);
    }

    /**
     * 删除单条记录
     * @return array
     * @author 牧羊人
     * @date 2019/2/25
     */
    public function drop()
    {
        if (IS_POST) {
            $id = input('post.id');
            $info = $this->model->getInfo($id);
            if ($info) {
                $result = $this->model->drop($id);
                if ($result !== false) {
                    return message();
                }
            }
            return message($this->model->getError(), false);
        }
    }

    /**
     * 重置缓存
     * @return array
     * @author 牧羊人
     * @date 2019/5/12
     */
    public function cache()
    {
        if (IS_POST) {
            $id = input('post.id');
            if (!$id) {
                return message("记录ID不能为空", false);
            }
            $result = $this->model->_cacheReset($id, '');
            if (!$result) {
                return message("缓存重置失败", false);
            }
            return message("缓存重置成功");
        }
    }

    /**
     * 一键复制
     * @return mixed
     * @author 牧羊人
     * @date 2019/5/12
     */
    public function copy()
    {
        if (IS_POST) {
            $result = $this->service->edit();
            return $result;
        }
        $info = [];
        $id = input("get.id", 0);
        if ($id) {
            $info = $this->model->getInfo($id);
        } else {
            $data = func_get_args();
            if (isset($data[0])) {
                foreach ($data[0] as $key => $val) {
                    $info[$key] = $val;
                }
            }
        }
        // 复制作为新增数据，主键ID必须置空
        unset($info['id']);
        $this->assign('info', $info);
        return $this->render('edit');
    }

    /**
     * 更新单个字段
     * @return array
     * @author 牧羊人
     * @date 2019/5/12
     */
    public function update()
    {
        if (IS_POST) {
            $data = request()->param();
            $result = $this->model->edit($data);
            if ($result) {
                return message("更新成功");
            } else {
                return message("更新失败", false);
            }
        }
    }

    /**
     * 批量删除记录
     * @return array
     * @author 牧羊人
     * @date 2019/2/25
     */
    public function batchDrop()
    {
        if (IS_POST) {
            $ids = explode(',', $_POST['id']);
            //批量删除
            $num = 0;
            foreach ($ids as $key => $val) {
                $res = $this->model->drop($val);
                if ($res !== false) {
                    $num++;
                }
            }
            return message('本次共选择' . count($ids) . "个条数据,删除" . $num . "个");
        }
    }

    /**
     * 批量重置缓存
     * @return array
     * @author 牧羊人
     * @date 2019/5/9
     */
    public function batchCache()
    {
        if (IS_POST) {
            $ids = explode(',', $_POST['id']);
            //重置缓存
            foreach ($ids as $key => $val) {
                $this->model->_cacheReset($val);
            }
            return message('重置缓存成功！');
        }
    }

    /**
     * 批量设置状态
     * @return array
     * @author 牧羊人
     * @date 2019/5/15
     */
    public function batchStatus()
    {
        if (IS_POST) {
            $ids = explode(',', $_POST['id']);
            $status = (int)$_POST['status'];
            if (!is_array($ids)) {
                return message("请选择数据记录", false);
            }
            $num = 0;
            foreach ($ids as $key => $val) {
                $result = $this->model->edit([
                    'id' => $val,
                    'status' => $status,
                ]);
                if ($result) {
                    $num++;
                }
            }
            return message("本次共更新【{$num}】条记录");
        }
    }

    /**
     * 设置状态
     * @return mixed
     * @author 牧羊人
     * @date 2019/11/2
     */
    public function setStatus()
    {
        if (IS_POST) {
            $result = $this->service->setStatus();
            return $result;
        }
    }
}