<div class="content-wrapper">
    <?php
    $form = $this->form;
    $form->prepare();

    $form->get('company_name|base')->setAttributes([
        'placeholder' => $this->translate('公司名称')
    ]);

    ?>
    <?= $this->form()->openTag($form); ?>
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('保存设置')?></button>
            <?=$this->HelpUrl('adminPassword')?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab_1" data-toggle="tab"><?=$this->translate('基本设置')?></a></li>
                        <!--li><a href="#tab_2" data-toggle="tab">高级设置</a></li>
                        <li><a href="#tab_3" data-toggle="tab">货币设置</a></li-->
                    </ul>
                    <div class="tab-content">
                        <?=$this->partial('layout/messages'); ?>
                        <div class="tab-pane active" id="tab_1">
                            <div class="box-body">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label"><?=$this->translate('公司名称')?><span class="must_add_value">*</span></label>
                                    <div class="col-sm-6">
                                        <?= $this->formElement($form->get('company_name|base')); ?>
                                        <?= $this->formElementErrors($form->get('company_name|base'), ['class'=>'error-message']); ?>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="tab_2">

                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="tab_3">

                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                    <div>
                        <div class="box-footer text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> <?=$this->translate('保存设置')?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <?= $this->form()->closeTag(); ?>
</div>