<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> <?php if($info['id']){?>编辑<?php }else{?>新增<?php }?>后台菜单
				</div>
				
			</div>
			<div class="portlet-body form">
				<form role="form" action="<?php echo $_SERVER['REQUEST_URI']?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
                <input type="hidden" name="id" value="<?php echo $info['id'] ?: "";?>">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">菜单标题：</label>
							<div class="col-md-9">
								<input type="text" name="title" value="<?php echo $info['title'] ?: "";?>" placeholder="" class="form-control">
                                <span class="help-block">
								    （用于后台显示的配置标题） 
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">排序：</label>
							<div class="col-md-9">
								<input type="text" name="sort" value="<?php echo $info['sort'] ?: 0;?>" placeholder="" class="form-control">
                                <span class="help-block">
								    （用于分组显示的顺序） 
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">菜单URL：</label>
							<div class="col-md-9">
								<input type="text" name="url" value="<?php echo $info['url'] ?: "";?>" placeholder="" class="form-control">
                                <span class="help-block">
								    （Controlle/Method） 
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">上级菜单：</label>
							<div class="col-md-9">
								<select class="form-control" name="pid">
                                    <?php foreach($Menus as $key=>$menu){ ?>
                                        <option value="<?php echo $menu['id']?>" <?php if($menu['id'] == $info['pid']){?>selected="selected"<?php }?> ><?php echo $menu['title_show']?></option>
                                    <?php }?>
								</select>
                                <span class="help-block">
								    （支持无限级） 
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">分组：</label>
							<div class="col-md-9">
								<input type="text" name="group" value="<?php echo $info['group'] ?: "";?>" placeholder="" class="form-control">
                                <span class="help-block">
								    （用于左侧分组二级菜单） 
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">隐藏：</label>
							<div class="col-md-9">
								<div class="radio-list">
									<label class="radio-inline">
                                        <input type="radio" name="hide" value="1" <?php if($info['hide'] ==1){?>checked="checked"<?php }?> /> 是
                                    </label>
									<label class="radio-inline">
                                        <input type="radio" name="hide" value="0" <?php if($info['hide'] !=1){?>checked="checked"<?php }?> /> 否 
                                    </label>
								</div>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">仅开发者模式可见：</label>
							<div class="col-md-9">
								<div class="radio-list">
									<label class="radio-inline">
                                        <input type="radio" name="is_dev" value="1" <?php if($info['is_dev'] ==1){?>checked="checked"<?php }?> /> 是
                                    </label>
									<label class="radio-inline">
                                        <input type="radio" name="is_dev" value="0" <?php if($info['is_dev'] !=1){?>checked="checked"<?php }?> /> 否 
                                    </label>
								</div>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">说明：</label>
							<div class="col-md-9">
								<input type="text" name="tip" value="<?php echo $info['tip'] ?: "";?>" placeholder="" class="form-control">
                                <span class="help-block">
								    （菜单详细说明） 
                                </span>
							</div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>