<div class="content-wrapper">
    <?php
    $form = $this->form;
    $form->prepare();

    $form->get('customerCategoryCode')->setAttributes([
        'placeholder' => $this->translate('客户分类编码')
    ]);

    $form->get('customerCategoryName')->setAttributes([
        'placeholder' => $this->translate('客户分类名称')
    ]);

    $form->get('customerCategorySort')->setAttributes([
        'placeholder' => $this->translate('客户分类排序')
    ]);

    ?>
    <?= $this->form()->openTag($form); ?>
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('customer-category');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?=$this->translate('返回客户分类列表')?></a>
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('保存客户分类')?></button>
            <?=(isset($customerCategory) ? $this->HelpUrl('customerCategoryEdit') : $this->HelpUrl('customerCategoryAdd'))?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=((isset($customerCategory) && $customerCategory->getCustomerCategoryId()) ? $this->translate('编辑客户分类') : $this->translate('添加客户分类'))?></h3>
                    </div>

                    <div class="box-body">
                        <?=$this->formElementErrors($form->get('dberp_csrf'), ['class'=>'error-message']); ?>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('客户分类编码')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-3">
                                <?= $this->formElement($form->get('customerCategoryCode')); ?>
                                <?= $this->formElementErrors($form->get('customerCategoryCode'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('客户分类名称')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-6">
                                <?= $this->formElement($form->get('customerCategoryName')); ?>
                                <?= $this->formElementErrors($form->get('customerCategoryName'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('排序')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-3">
                                <?= $this->formElement($form->get('customerCategorySort')); ?>
                                <?= $this->formElementErrors($form->get('customerCategorySort'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                    </div>

                    <div>
                        <div class="box-footer">
                            <?=$this->formElement($form->get('dberp_csrf')); ?>
                            <button type="submit" class="btn btn-primary col-md-offset-2"><i class="fa fa-check"></i> <?=$this->translate('保存客户分类')?></button>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </section>
    <?= $this->form()->closeTag(); ?>

</div>
<script>
    $(document).ready(function() {
        $("#<?=$form->getName()?>").validate({
            rules: {
                customerCategoryCode: {
                    required: true
                },
                customerCategoryName: {
                    required: true
                },
                customerCategorySort: {
                    required: true,
                    number: true,
                    min: 1
                }
            },
            messages: {
                customerCategoryCode: {
                    required: "<?=$this->translate('客户分类编码不能为空！')?>"
                },
                customerCategoryName: {
                    required: "<?=$this->translate('客户分类名称不能为空！')?>"
                },
                customerCategorySort: {
                    required: "<?=$this->translate('排序不能为空！')?>",
                    number: "<?=$this->translate('排序必须为数字！')?>",
                    min: "<?=$this->translate('排序最小为1！')?>"
                }
            }
        });
    });
</script>