<?php 

$auth = @$_SESSION['auth'];
if (empty($auth)) { 
	header('Location:?c=user&a=login');
	die();
}

?>
<div class="container account-head">
	<div class="row clearfix">
		<div class="col-md-10 column">
			<h2>
				<strong id="center_user_name"><?php echo $auth['name'] ?></strong> <small>的账户 <a class="btn btn-default btn-sm" href="?c=account&a=account_charge">充值</a> </small>
			</h2>
		</div>
		<div class="col-md-2 column">
			<img src="img/center/user_face/<?php echo $auth['id'] ?>.jpg" class="img-rounded pull-right hidden-xs"/>
		</div>
	</div>
</div>
<div class="container account-nav">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="nav nav-tabs">
				<li id="detail">
				<a href="?c=account&a=index">账户明细</a>
				</li>
				<li id="account_addr_set">
				<a href="?c=account&a=account_addr_set">收货地址</a>
				</li>
				<li id="pay_password_set">
				<a href="?c=account&a=pay_password_set">支付密码</a>
				</li>
				<li id="account_charge">
				<a href="?c=account&a=account_charge">账户充值</a>
				</li>
			</ul>
		</div>

	</div>
</div>
