document.write('<div class="buttons"><a href="#dl"><img src="./images/down.gif" alt="下载地址" width="98" height="31" border="0" /></a> <a href="#pl"><img src="./images/feedback.gif" alt="用户反馈" width="98" height="31" border="0" /></a> <a href="#help"><img src="./images/help.gif" alt="下载帮助" width="98" height="31" border="0" /></a> <a href="###" onClick="window.external.AddFavorite(document.location.href,document.title);"><img src="./images/favorite.gif" alt="收藏该页" width="98" height="31" border="0" /></a></div>');
				  
document.write('	<table border="0" align="center" cellpadding="0" cellspacing="0">');
document.write('      <tr>');
document.write('        <td class="ding-Out" onClick="Ok3w_Soft_Hits(\'./\','+softID+',1);" onMouseOver="this.className=\'ding-Over\'" onMouseOut="this.className=\'ding-Out\'"><br />');
document.write('            <table border="0" cellspacing="0" cellpadding="0">');
document.write('              <tr>');
document.write('                <td>&nbsp;</td>');
document.write('                <td><div class="ding-bar">');
document.write('                    <div id="eimg1" style="width:1px; overflow:hidden;">d</div>');
document.write('                </div></td>');
document.write('                <td>&nbsp;</td>');
document.write('                <td><span id="barnum1"><span id="sp1">0%</span> (<span id="s1">0</span>)</span></td>');
document.write('              </tr>');
document.write('          </table></td>');
document.write('        <td>&nbsp;</td>');
document.write('        <td class="cai-Out" onClick="Ok3w_Soft_Hits(\'./\','+softID+',2);" onMouseOver="this.className=\'cai-Over\'" onMouseOut="this.className=\'cai-Out\'"><br />');
document.write('            <table border="0" cellspacing="0" cellpadding="0">');
document.write('              <tr>');
document.write('                <td>&nbsp;</td>');
document.write('                <td><div class="cai-bar">');
document.write('                    <div id="eimg2" style="width:1px; overflow:hidden;">c</div>');
document.write('                </div></td>');
document.write('                <td>&nbsp;</td>');
document.write('                <td><span id="barnum2"><span id="sp2">0%</span> (<span id="s2">0</span>)</span></td>');
document.write('              </tr>');
document.write('          </table></td>');
document.write('      </tr>');
document.write('    </table>');
document.write('	<br />');