document.write('<table border="0" align="center" cellpadding="0" cellspacing="0">');
document.write('<form method="post" action="">');
document.write('<input type="hidden" name="mood" />');
document.write('<tr>');
document.write('<td height="20" colspan="8" align="left" valign="middle" scope="col">您读过此篇文章后的感受是：</td>');
document.write('</tr>');
document.write('<tr>');
document.write('  <td width="60" height="80" align="center" valign="bottom" scope="col"> <span id="moodnum1">0</span><br />');
document.write('      <img id="moodimg1" name="" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum2">0</span><br />');
document.write('      <img id="moodimg2" src="./images/mood/100.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum3">0</span><br />');
document.write('      <img id="moodimg3" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum4">0</span><br />');
document.write('      <img id="moodimg4" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum5">0</span><br />');
document.write('      <img id="moodimg5" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum6">0</span><br />');
document.write('      <img id="moodimg6" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum7">0</span><br />');
document.write('      <img id="moodimg7" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('  <td width="60" align="center" valign="bottom" scope="col"> <span id="moodnum8">0</span><br />');
document.write('      <img id="moodimg8" src="./images/mood/101.gif" width="20" height="1" /></td>');
document.write('</tr>');
document.write('<tr>');
document.write('  <td height="50" align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,1)" title="点击投票"><img src="./images/mood/1.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,2)" title="点击投票"><img src="./images/mood/2.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,3)" title="点击投票"><img src="./images/mood/3.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,4)" title="点击投票"><img src="./images/mood/4.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,5)" title="点击投票"><img src="./images/mood/5.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,6)" title="点击投票"><img src="./images/mood/6.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,7)" title="点击投票"><img src="./images/mood/7.gif" width="40" height="40" /></td>');
document.write('  <td align="center" style="cursor:pointer;" onClick="Ok3w_Article_Hits_Mood(\'./\',ArticleID,8)" title="点击投票"><img src="./images/mood/8.gif" width="40" height="40" /></td>');
document.write('</tr>');
document.write('<tr>');
document.write('  <td align="center">欠扁</td>');
document.write('  <td align="center">支持</td>');
document.write('  <td align="center">很棒</td>');
document.write('  <td align="center">找骂</td>');
document.write('  <td align="center">搞笑</td>');
document.write('  <td align="center">扯淡</td>');
document.write('  <td align="center">不解</td>');
document.write('  <td align="center">吃惊</td>');
document.write('</tr>');
document.write('</form>');
document.write('</table>');