<form action="<?php echo $this->URL;?>/update?navTabId=<?php echo $this->MODULE;?>" method="post" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone)">
<input type="hidden" name="id" value="<?php echo $this->vo->id;?>"/>
<div class="pageContent">
	<div class="pageFormContent" layoutH="58">
		<dl>
			<dt>编号：</dt><dd><input name="code" class="required digits" alt="请输入整数" type="text" value="<?php echo $this->vo->code;?>"/></dd>
		</dl>
		<dl>
			<dt>名称：</dt><dd><input name="name" class="required" type="text" value="<?php echo $this->vo->name;?>"/></dd>
		</dl>
		<dl class="nowrap">
			<dt>描述：</dt>
			<dd>
				<textarea class="editor" name="description" rows="4" cols="75"><?php echo $this->escape($this->vo->description);?></textarea>
			</dd>
		</dl>
	</div>
	<div class="formBar">
		<ul>
			<li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
			<li><div class="button"><div class="buttonContent"><button class="close" type="button">关闭</button></div></div></li>
		</ul>
	</div>
</div>
</form>