
<div class="pageContent">
	<div class="pageFormContent" layoutH="58">
		<dl>
			<dt>编号：</dt><dd><?php echo $this->vo->code;?></dd>
		</dl>
		<dl>
			<dt>名称：</dt><dd><?php echo $this->vo->name;?></dd>
		</dl>
		<dl class="nowrap">
			<dt>描述：</dt>
			<dd>
				<?php echo $this->escape($this->vo->description);?>
			</dd>
		</dl>
	</div>
	<div class="formBar">
		<ul>
			<li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
			<li><div class="button"><div class="buttonContent"><button class="close" type="button">关闭</button></div></div></li>
		</ul>
	</div>
</div>
