<div class="content-wrapper">

    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('goods-category', ['action'=> 'add']);?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <?=$this->translate('添加商品分类')?></a>
            <?=$this->HelpUrl('goodsCategoryList')?>
        </h1>

    </section>

    <section class="content">
        <?=$this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <form method="post" action="<?=$this->url('goods-category', ['action' => 'updateAll']);?>" name="edit-all-form" id="edit-all-form">
                    <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr class="erp-bg-thead">
                                    <th width="2%"><input type="checkbox" class="minimal select-all-checkbox"></th>
                                    <th><?=$this->translate('分类名称(分类ID)')?></th>
                                    <th><?=$this->translate('分类编码')?></th>
                                    <th width="8%"><?=$this->translate('排序')?></th>
                                    <th width="18%"><?=$this->translate('操作')?></th>
                                </tr>
                                </thead>

                                <?php if($this->category) foreach ($this->category as $value) { ?>
                                    <tr>
                                        <td><input  name="select_id[]" value="<?=$value->getGoodsCategoryId()?>" type="checkbox" class="minimal"></td>
                                        <td>
                                            <?php if($value->getGoodsCategoryTopId() > 0) echo str_repeat('&nbsp;', substr_count($value->getGoodsCategoryPath(), ',') * 3); ?>|----
                                            <?= $this->escapeHtml($value->getGoodsCategoryName()).'(ID:'.$value->getGoodsCategoryId().')'?></td>
                                        <td><?= $this->escapeHtml($value->getGoodsCategoryCode())?></td>
                                        <td><input type="text" name="goods_category_sort[<?=$value->getGoodsCategoryId()?>]" value="<?= $value->getGoodsCategorySort()?>" class="form-control input-sm"></td>
                                        <td>
                                            <a href="<?= $this->url('goods-category',
                                                ['action'=>'edit', 'id'=>$value->getGoodsCategoryId()]); ?>"
                                               class="btn btn-xs btn-success"><i class="fa fa-pencil"></i> <?=$this->translate('编辑')?>
                                            </a>

                                            <a href="javascript:;" onclick="deleteConfirm('<?php echo $this->translate('您确实要删除该商品分类吗？'); ?>', '<?= $this->url('goods-category', ['action'=>'delete', 'id'=>$value->getGoodsCategoryId()], ['query' => ['qToken' => $this->adminHelper()->getCsrfValue()]]); ?>');" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash"></i> <?=$this->translate('删除')?>
                                            </a>

                                        </td>
                                    </tr>
                                <?php } ?>
                            </table>

                    </div>
                    <div class="box-footer clearfix">
                        <input type="checkbox" class="minimal select-all-checkbox"> <?=$this->translate('全选')?>
                        <select name="editAllState">
                            <option value=""><?=$this->translate('选择状态')?></option>
                            <option value="sort"><?=$this->translate('更新排序')?></option>
                        </select>
                        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('更新')?></button>
                    </div>
                    </form>
                </div>

            </div>
        </div>

    </section>
</div>