<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "case_tab"
 *
 * Auto generated by Extension Builder 2019-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '应用案例',
    'description' => '应用案例，用于tab页切换模式',
    'category' => 'plugin',
    'author' => '杨世昌',
    'author_email' => 'yangshichang@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
