<?php 

if (!empty($_POST)) die;

?>
<div class="container">
	<div class="row clearfix">
		<div class="col-md-8 column" style="border-right: 1px solid #ddd">
			<div class="account-well">
				<form class="form-horizontal" method="get" target="_blank">
					<div class="alert alert-success">
						<b>提示</b>
						<ol>
							<li>HIICI采用支付宝担保交易进行充值操作。</li>
						</ol>
					</div>
					<input type="hidden" name="c" value="account"/>
					<input type="hidden" name="a" value="do_account_charge_submit"/>
					<br>
					<div class="row clearfix">
						<div class="col-md-6 column">
							<input type="text" class="form-control" name="price" required="" value="50"/>
						</div>
						<div class="col-md-3 column">
							<label class="control-label">充值金额（元）</label>
						</div>
					</div>
					<br>
					<!-- token -->
					<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
					<div class="row clearfix">
						<div class="col-md-3 column">
							<button type="submit" class="btn btn-success btn-block">充值</button>
						</div>
						<div class="col-md-5 column">
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="col-md-4 column">
			<?php require_once('inc/account_pub_sidebar.phtml') ?>	
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	$('li#account_charge').addClass('active');
});

</script>
