<?php 

if (!empty($_POST)) die;

?>
<div class="container">
	<div class="row clearfix">
		<div class="col-md-8 column" style="border-right: 1px solid #ddd">
			<div class="account-well">
				<div class="alert alert-info">
					<b>提示</b>
					<ol>
						<li>默认的支付密码与登录密码相同，QQ用户的默认支付密码为“QQ”。</li>
						<li>强烈建议修改默认支付密码,且异于登录密码。</li>
					</ol>
				</div>
				<form class="form-horizontal" action="javascript:do_pay_password_set()" id="do_pay_password_set">
					<br>
					<div class="row clearfix">
						<div class="col-md-8 column">
							<input type="password" class="form-control" id="password_old" name="password_old" required=""/>
						</div>
						<div class="col-md-3 column">
							<label class="control-label">旧支付密码</label>
						</div>
					</div>
					<hr>
					<div class="row clearfix">
						<div class="col-md-8 column">
							<input type="password" class="form-control" id="password_new" name="password_new" required=""/>
						</div>
						<div class="col-md-3 column">
							<label class="control-label">新支付密码</label>
						</div>
					</div>
					<br>
					<div class="row clearfix">
						<div class="col-md-8 column">
							<input type="password" class="form-control" id="password_new_r" name="password_new_r" required=""/>
						</div>
						<div class="col-md-3 column">
							<label class="control-label">重复新支付密码</label>
						</div>
					</div>
					<hr>
					<!-- token -->
					<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
					<div class="row clearfix">
						<div class="col-md-3 column">
							<button type="submit" class="btn btn-primary btn-block">重置</button>
						</div>
						<div class="col-md-5 column">
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="col-md-4 column">
			<?php require_once('inc/account_pub_sidebar.phtml') ?>	
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	$('li#pay_password_set').addClass('active');
});

</script>
