Ext.define('MyApp.view.{NAME}',{
	extend:'Ext.window.Window',
	title:'标题',
	xtype:'{XTYPE}',
	layout:'fit',
	autoShow:true,
	modal:true,
	items:[
		{
			xtype:'form',
			bodyPadding:10,
			border:false,
			relationStore:'',
			items:[
				{
					xtype:'hidden',
					name:'id'
				},
				{
					xtype:'textfield',
					name:'',
					allowBlank:false,
					fieldLabel:'文本框'
				},
				{
					xtype:'combobox',
					name:'',
					fieldLabel:'下拉菜单',
					valueField:'value',
					displayField:'label',
					store:{
						fields:['value','label'],
						data:[
							{
								value:'否',
								label:'是'
							}
						]
					}
				}
			],
			afterDataLoaded:function(){
				
			}
		}
	],
	buttons:[
		{
			text:'保存',
			scale:'medium',
			name:'save'
		},
		{
			text:'取消',
			scale:'medium',
			name:'cancel'
		}
	]
});