<?php
$settings = array(
	'title' => array(
		'field' => 'string',
		'widget' => 'Text',
		'isLabel' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'minLength' => 1,
		'maxLength' => 11,
		'isTitle' => true,
		'left' => true,
		'number' => 1,
		'addition' => true,
		'label' => '书本名称',
		'description' => '',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'cataloging' => array(
		'addition' => true,
		'label' => '书本目录',
	),
	'author' => array(
		'addition' => true,
		'label' => '书本作者',
	),
	'body' => array(
		'field' => 'textLong',
		'widget' => 'Textarea',
		'left' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'fullTextSearch' => true,
		'toc' => true,
		'wordsmith' => true,
		'minLength' => 1,
		'maxLength' => 11,
		'filter' => array('imagesToLocal'),
		'number' => 1,
		'addition' => true,
		'label' => '书本简介',
		'description' => '',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'cat' => array(
		'required' => false,
		'field' => 'term',
		'widget' => 'Select',
		'left' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'addTerm' => true,
		'valueType' => 'id',
		'type' => 'article',
		'maxNum' => 10,
		'taxonomy' => 'book_cat',
		'mainTable' => 2,
		'parent' => 0,
		'addition' => true,
		'label' => '书本分类',
		'description' => '书本分类',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'images' => array(
		'field' => 'fileBox',
		'widget' => 'FileBox',
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'left' => true,
		'wordsmith' => true,
		'minLength' => 1,
		'maxLength' => 11,
		'required' => false,
		'number' => 1,
		'addition' => true,
		'label' => '书本封面',
		'description' => '特色图片',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'commentContentModel' => 'comment',
);
