<?php
$settings = array(
	'title' => array(
		'field' => 'string',
		'widget' => 'Text',
		'isLabel' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'minLength' => 1,
		'maxLength' => 11,
		'isTitle' => true,
		'left' => true,
		'number' => 1,
		'addition' => true,
		'label' => '标题',
		'description' => '',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'keywords' => array(
		'field' => 'string',
		'widget' => 'Text',
		'isLabel' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'minLength' => 1,
		'maxLength' => 11,
		'isTitle' => true,
		'left' => true,
		'number' => 1,
		'addition' => true,
		'label' => '关键字',
		'description' => '内容关键字',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'description' => array(
		'left' => true,
		'field' => 'textLong',
		'widget' => 'Textarea',
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'minLength' => 1,
		'maxLength' => 11,
		'number' => 1,
		'addition' => true,
		'label' => '简介',
		'description' => '内容简介',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'body' => array(
		'left' => true,
		'field' => 'textLong',
		'widget' => 'Textarea',
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'fullTextSearch' => true,
		'toc' => true,
		'wordsmith' => true,
		'minLength' => 1,
		'maxLength' => 11,
		'number' => 1,
		'filter' => array('imagesToLocal'),
		'addition' => true,
		'label' => '内容',
		'description' => '',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'tags' => array(
		'required' => false,
		'left' => true,
		'field' => 'term',
		'widget' => 'Tags',
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'addTerm' => true,
		'valueType' => 'name',
		'type' => 'article',
		'maxNum' => 10,
		'taxonomy' => 'file_tags',
		'mainTable' => 2,
		'parent' => 0,
		'addition' => true,
		'label' => '标签',
		'description' => '文章标签',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'images' => array(
		'left' => true,
		'field' => 'fileBox',
		'widget' => 'FileBox',
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'wordsmith' => true,
		'minLength' => 1,
		'maxLength' => 11,
		'required' => false,
		'number' => 1,
		'addition' => true,
		'label' => '图片',
		'description' => '特色图片',
		'error' => '',
		'attributes' => array(
			'class' => 'form-control',
		),
	),
	'download' => array(
		'left' => true,
		'field' => 'kvgroup',
		'widget' => 'Kvgroup',
		'addition' => true,
		'access' => array(
			'addForm' => true,
			'editForm' => true,
		),
		'label' => '下载链接',
		'default' => 1,
		'required' => false,
		'maxNum' => 1,
		'attributes' => array(),
		'error' => '',
		'description' => '可以设置多个下载链接',
	),
	'commentContentModel' => 'comment',
);
