<?php
$settings = array(
    'title' => array(
        'field' => 'string',
        'widget' => 'Text',
        'isLabel' => true,
        'access' => array(
            'addForm' => true,
            'editForm' => true,
        ),
        'minLength' => 1,
        'maxLength' => 11,
        'isTitle' => true,
        'number' => 1,
        'fullTextSearch' => true,
        'addition' => true,
        'label' => '标题',
        'description' => '',
        'error' => '',
        'attributes' => array(
            'class' => 'form-control',
        ),
    ),
    'gold' => array(
        'field' => 'string',
        'widget' => 'Text',
        'isLabel' => true,
        'access' => array(
            'addForm' => true,
            'editForm' => true,
        ),
        'model' => '\Modules\Community\Entity\Fields\NodeFieldGold',
        'minLength' => 1,
        'maxLength' => 11,
        'isTitle' => true,
        'number' => 1,
        'addition' => true,
        'label' => '金币',
        'description' => '',
        'error' => '',
        'attributes' => array(
            'class' => 'form-control',
        ),
    ),
    'body' => array(
        'field' => 'textLong',
        'widget' => 'Textarea',
        'access' => array(
            'addForm' => true,
            'editForm' => true,
        ),
        'search' => true,
        'fullTextSearch' => true,
        'wordsmith' => true,
        'minLength' => 1,
        'maxLength' => 11,
        'number' => 1,
        'addition' => true,
        'label' => '内容',
        'description' => '',
        'error' => '',
        'attributes' => array(
            'class' => 'form-control',
        ),
    ),
    'best' => array(
        'addition' => true,
        'label' => '最佳答案',
        'model' => '\Modules\Community\Entity\Fields\NodeFieldBest',
        'default' => 0,
    ),
    'tags' => array(
        'field' => 'term',
        'widget' => 'Tags',
        'access' => array(
            'addForm' => true,
            'editForm' => true,
        ),
        'addTerm' => true,
        'valueType' => 'name',
        'type' => 'article',
        'maxNum' => 10,
        'taxonomy' => 'question',
        'mainTable' => 2,
        'parent' => 0,
        'addition' => true,
        'label' => '标签',
        'description' => '文章标签',
        'error' => '',
        'attributes' => array(
            'class' => 'form-control',
        ),
    ),
    'commentContentModel' => 'answer',
);
