<pre>

此示例前后台通用，哦耶

#在有jquery的情况下，加载JS
js/WPF_bootbox.js

在程序中可以使用
$this->footerjs->addJs("js/WPF_bootbox.js");


页面中的处理方式如下
WPF.bootbox({
   type:"dialog",//可选择dialog或者alert 默认dialog
   status:"error",//可选择success或error 默认success
   message:"可以包含HTML",
   title:"标题",//
   size:"large"  //可选择large大或者small小，或者为空
});


WPF.ajax({
   url:"a.php",
   type:"get",//可选择GET或POST,默认GET
   data:{id:1,name:"aaa"},
   title:"管理页面",
   bootboxtype:"dialog",//可选择dialog或者alert
   size:"large",  //可选择large大或者small小，或者为空
   success:function(ret,UTbox){
      alert(111);//执行成功后要执行的函数
   },
   error:function(ret,UTbox){
      alert(222);//执行失败后要执行的函数
   }
});
</pre>
<button class="btn blue testalert" type="button">alert</button>
<button class="btn blue testdialog" type="button">dialog</button>

当然还有AJAX的，没例子，自己抄吧


<script>
$(function(){
    $(".testalert").on("click",function(){
        WPF.bootbox({
           type:"alert",//可选择dialog或者alert 默认dialog
           status:"success",//可选择success或error 默认success
           message:"可以包含HTML",
           title:"标题",//
           size:"large"  //可选择large大或者small小，或者为空
        });
    }) 
    $(".testdialog").on("click",function(){
        WPF.bootbox({
           type:"dialog",//可选择dialog或者alert 默认dialog
           status:"success",//可选择success或error 默认success
           message:"可以包含HTML",
           title:"标题",//
           size:"large"  //可选择large大或者small小，或者为空
        });
    }) 
});
</script>