<div class="row">	
	<div class="col-md-8 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> 富文本编辑器示例
				</div>
				
			</div>
			<div class="portlet-body form">
				<form target="_blank" method="post" action="<?php echo $_SERVER['REQUEST_URI']?>" class="form-horizontal form-bordered" role="form">
					<div class="form-body">
						
                        <div class="form-group">
							<label class="col-md-3 control-label">wysihtml5</label>
                            <div class="col-md-9">
                            <?php $this->partial("_common/wysihtml5",array("inputname"=>"","inputvalue"=>"","inputrows"=>6)) ?>
                            </div>
						</div>
					</div>
                    <div class="form-body">
						
                        <div class="form-group">
							<label class="col-md-3 control-label">summernote</label>
                            <div class="col-md-9">
                                <?php $this->partial("_common/summernote",array("inputname"=>"summernote","inputvalue"=>"","inputrows"=>300)) ?>
                                <span class="help-block">
    							    （summernote的富文本内容不能随form提交，需要在提交前用$(".inputname").code()来获得，inputname不要使用summernote，summernote是默认的CLASS名称）
                                </span>
                            </div>
                                
                        </div>
					</div>
                    <div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green">Submit</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
                </form>
			</div>
					
				
		</div>
	</div>
</div>

