<div class="row">	
	<div class="col-md-8 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> 邮件示例
				</div>
				
			</div>
			<div class="portlet-body form">
				<form class="form-horizontal form-bordered" action="<?php echo $_SERVER['REQUEST_URI']?>" method="POST" enctype="application/x-www-form-urlencoded" role="form">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">发送服务器</label>
                            <div class="col-md-9">
                                <input type="text" name="Host" value="<?php echo $this->config->EMAIL_HOST?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">发送帐号</label>
                            <div class="col-md-9">
                                <input type="text" name="Username" value="<?php echo $this->config->EMAIL_USERNAME?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">发送密码</label>
                            <div class="col-md-9">
                                <input type="text" name="Password" value="<?php echo $this->config->EMAIL_PASSWORD?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">发送端口号</label>
                            <div class="col-md-9">
                                <input type="text" name="Port" value="<?php echo $this->config->EMAIL_PORT?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">是否SMTP认证</label>
                            <div class="col-md-9">
                                <div class="radio-list">
    								<label class="radio-inline">
                                        <input type="radio" name="SMTPAuth" value="0" <?php if(!$this->config->EMAIL_SMTPAUTH){?>checked="checked"<?php }?> /> 否
                                    </label>
    								<label class="radio-inline">
                                        <input type="radio" name="SMTPAuth" value="1" <?php if($this->config->EMAIL_SMTPAUTH){?>checked="checked"<?php }?> /> 是 
                                    </label>
    							</div>
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">是否加密发送</label>
                            <div class="col-md-9">
                                <div class="radio-list">
    								<label class="radio-inline">
                                        <input type="radio" name="SMTPSecure" value="0" <?php if(!$this->config->EMAIL_SMTPSECURE){?>checked="checked"<?php }?>/> 否
                                    </label>
    								<label class="radio-inline">
                                        <input type="radio" name="SMTPSecure" value="ssl" <?php if($this->config->EMAIL_SMTPSECURE=="ssl"){?>checked="checked"<?php }?> /> ssl加密 
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="SMTPSecure" value="tls" <?php if($this->config->EMAIL_SMTPSECURE=="tls"){?>checked="checked"<?php }?> /> tls加密 
                                    </label>
    							</div>
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">发送邮箱，即回复邮箱</label>
                            <div class="col-md-9">
                                <input type="text" name="From" value="<?php echo $this->config->EMAIL_FROM?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">发送者名称</label>
                            <div class="col-md-9">
                                <input type="text" name="FromName" value="<?php echo $this->config->EMAIL_FROMNAME?>" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">收件邮箱</label>
                            <div class="col-md-9">
                                <input type="text" name="addAddress" value="" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">收件者姓名</label>
                            <div class="col-md-9">
                                <input type="text" name="addAddressName" value="" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">是否HTML邮件</label>
                            <div class="col-md-9">
                                <div class="radio-list">
    								<label class="radio-inline">
                                        <input type="radio" name="isHTML" value="0" <?php if(!$this->config->EMAIL_ISHTML){?>checked="checked"<?php }?> /> 否
                                    </label>
    								<label class="radio-inline">
                                        <input type="radio" name="isHTML" value="1" <?php if($this->config->EMAIL_ISHTML){?>checked="checked"<?php }?> /> 是 
                                    </label>
    							</div>
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">邮件标题</label>
                            <div class="col-md-9">
                                <input type="text" name="Subject" value="" placeholder="" class="form-control">
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">邮件正文</label>
                            <div class="col-md-9">
                                <?php $this->partial("_common/wysihtml5",array("inputname"=>"Body","inputvalue"=>"","inputrows"=>6)) ?>
                            </div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green">Submit</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

