<div class="row">	
	<div class="col-md-8 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> 图片示例
				</div>
				
			</div>
			<div class="portlet-body form">
				<form target="_blank" method="post" action="<?php echo $_SERVER['REQUEST_URI']?>" class="form-horizontal form-bordered" role="form">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">单图上传</label>
                            <div class="col-md-9">
                            <?php $this->partial("_common/fileupload_single",array("inputname"=>"","inputvalue"=>"","no_selector"=>true,"imgurl"=>STATIC_URL."/img/common/no_img_80x80.png")) ?>
                            </div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">多图上传</label>
                            <div class="col-md-9">
                            <?php $this->partial("_common/fileupload_multiple",array("inputname"=>"","inputvalue"=>"","no_selector"=>true)) ?>
                            </div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green">Submit</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

