<div class="row">	
	<div class="col-md-8 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> 地图示例
				</div>
				
			</div>
			<div class="portlet-body form">
				<form class="form-horizontal form-bordered" role="form">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">后台地图打点</label>
                            <div class="col-md-9">
                                <?php $this->partial("_common/map_geocoding",array("divname"=>"gmap_geocoding","inputlat"=>"lat","inputlng"=>"lng","inputzoom"=>"zoom","lat"=>"39.904211","lng"=>"116.40739","zoom"=>"12")) ?>
                            </div>
						</div>
                        
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn green">Submit</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

