<?php
use \sy\base\Router;
use \blog\libs\Common;
?>
<!DOCTYPE html>
<html>
<head>
	<title>基本设置 - SYBlog</title>
	<?php $this->display('common/header'); ?>
</head>
<body>
	<?php $this->display('common/navbar'); ?>
	<div id="option" class="page-content">
		<h2 class="title">基本设置</h2>
		<div class="row">
			<div class="input-field col s4">
				<input type="text" name="sitename" class="option_input" value="<?=addslashes(Common::option('sitename'))?>" />
				<label for="title">站点名称</label>
			</div>
			<div class="input-field col s4">
				<input type="text" name="description" class="option_input" value="<?=addslashes(Common::option('description'))?>" />
				<label for="title">站点描述</label>
			</div>
			<div class="input-field col s4">
				<input type="text" name="author" class="option_input" value="<?=addslashes(Common::option('author'))?>" />
				<label for="title">文章作者</label>
			</div>
			<div class="input-field col s4">
				<input type="number" name="pagesize" class="option_input" value="<?=addslashes(Common::option('pagesize'))?>" />
				<label for="title">单页文章数量</label>
			</div>
			<div class="input-field col s4">
				<input type="text" name="cronPassword" class="option_input" value="<?=addslashes(Common::option('cronPassword'))?>" />
				<label for="title">Cron密码</label>
			</div>
			<div class="input-field col s4">
				<input type="text" name="apiKey" class="option_input" value="<?=addslashes(Common::option('apiKey'))?>" />
				<label for="title">API KEY</label>
			</div>
		</div>
		<div><button id="opt_bas_submit" type="button" class="waves-effect waves-light btn">保存</button></div>
	</div>
	<script>
	window.sy = {
		"url": {
			"submit": "<?=Router::createUrl('admin/option/save', 'json')?>"
		},
		"page": "Option"
	};
	</script>
	<?php $this->display('common/footer'); ?>
</body>
</html>