<?php
use \sy\base\Router;
?>
<!DOCTYPE html>
<html>
<head>
	<title>修改密码 - SYBlog</title>
	<?php $this->display('common/header'); ?>
</head>
<body>
	<?php $this->display('common/navbar'); ?>
	<div class="page-content">
		<h2 class="title">修改密码</h2>
		<div class="row">
			<div class="col s12">
				<div class="card-panel teal">
					<span class="white-text">Tips: 密码必须不小于5个字符</span>
				</div>
			</div>
			<div class="input-field col s12">
				<input id="old" type="password" placeholder="旧密码"/>
				<label>旧密码</label>
			</div>
			<div class="input-field col s12">
				<input id="new1" type="password" placeholder="新密码"/>
				<label>新密码</label>
			</div>
			<div class="input-field col s12">
				<input id="new2" type="password" placeholder="请再输一遍"/>
				<label>请再输一遍</label>
			</div>
		</div>
		<button id="submit" class="waves-effect waves-light btn">修改密码</button>
	</div>
	<script>
	window.sy = {
		"url": {
			"submit": "<?=Router::createUrl('admin/option/password', 'json')?>"
		},
		"page": "OptionPassword"
	};
	</script>
	<?php $this->display('common/footer'); ?>
</body>
</html>