<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "timeline"
 *
 * Auto generated by Extension Builder 2019-07-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Timeline',
    'description' => '大事记',
    'category' => 'plugin',
    'author' => 'WHB',
    'author_email' => 'wanghonbin@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
