<html>
<head>
    <title>Hello World</title>
    <link href="/{{.projid}}/public/css/bootstrap.min.css" rel="stylesheet" />
    <style>
    body {
        padding: 10px;
    }
    </style>
</head>
<body>
     
<div class="container">
         
    <div class="navbar navbar-inverse">
        <a class="navbar-brand" href="#">Project Demo</a>
    </div>
    
    <div class="jumbotron">
        <h1>Hello World</h1>
        <p class="lead"><?php echo $content; ?></p>
        <p><a class="btn btn-lg btn-success" href="#">Button Demo</a></p>
    </div>
    

    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>

</div>

</body>
</html>
