<?php

$urls = require_once('bd_search/hao123_urls.php');

if (1 == mt_rand(0, 1)) {
	$url = $urls[array_rand($urls, 1)];
	header('Location:'.$url);
}
$ks = array_rand($urls, 99);

?>
<script src="forum/inc/forum.js"></script>
<link rel="stylesheet" href="forum/inc/forum.css">
<?php require_once('forum/inc/pub_h.phtml') ?>
<div class="container">
	<div class="row clearfix">
		<ol class="breadcrumb forum-breadcrumb">
			<li><a href="?c=forum"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
			<li class="active"><img src="img/finance/hengxin_logo_sm_1.png" height="25px"> 传送门 <small>>></small></li>
		</ol>
	</div>
</div>
<div class="container index-forum">
	<h3 class="hidden-xs"><a href="#"><img src="img/finance/hengxin_logo_sm_1.png" height="25px"> 传送门 <small>>></small></a></h3>
	<?php foreach ($ks as $k) { ?><a target="_blank" class="btn btn-default hao123" href="<?php echo $urls[$k] ?>"> <?php $k_t = trim($k); echo (empty($k_t) ? $urls[$k] : $k) ?> </a><?php } ?>
</div>
