<div class="content-wrapper">
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3><?=$this->salesOrderCount?></h3>

                        <p><?=$this->translate('订单总数')?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <p class="small-box-footer"><?=$this->translate('系统订单')?> + <?=$this->translate('商城订单')?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3><?=$this->erpCurrencyFormat($this->salesAmount)?></h3>

                        <p><?=$this->translate('订单总金额')?></p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-cny"></i>
                    </div>
                    <p class="small-box-footer"><?=$this->translate('系统订单金额')?> + <?=$this->translate('商城订单金额')?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3><?=$this->customerCount?></h3>

                        <p><?=$this->translate('下单客户')?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <p class="small-box-footer"><?=$this->translate('唯一客户数')?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3><?=$this->goodsCount?></h3>

                        <p><?=$this->translate('销售商品数')?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <p class="small-box-footer"><?=$this->translate('唯一商品数')?></p>
                </div>
            </div>

        </div>

    </section>

</div>