<?php
use \sy\base\Router;
use \blog\model\Article;
use \blog\model\Meta;
use \blog\model\Link;
use \blog\libs\Html;
use \blog\libs\Common;
?>
	<footer class="page-footer">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text"><?=Common::option('sitename')?></h5>
					<p class="grey-text text-lighten-4"><?=Common::option('description')?></p>
				</div>
				<div class="col l4 offset-l2 s12">
					<h5 class="white-text">友情链接</h5>
					<ul>
						<?php
						$link = Link::getList();
						while ($one = $link->next()) {
							echo '<li><a class="grey-text text-lighten-3" href="' . $one->url . '" rel="' . $one->rel . '">' . $one->title . '</a></li>';
						}
						?>
					</ul>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				Copyright &copy; 2015 <?=Html::encode(Common::option('sitename'))?>. Powered by <a href="http://blog.sylingd.com" target="_blank">SYBlog</a>
				<a class="grey-text text-lighten-4 right" href="<?=Router::createUrl('admin/page/home')?>">进入后台</a>
			</div>
		</div>
	</footer>
	<?=Html::js('@root/assets/js/jquery.min.js')?>
	<?=Html::js('@root/assets/js/materialize.min.js')?>