<?php
use \blog\model\Article;
use \blog\model\Meta;
use \blog\model\Link;
use \blog\libs\Html;
use \blog\libs\Common;
?>
	<?php
	if (isset($article)) {
		$description = mb_substr($article->body, 0, 50);
		$keywords = $article->tags;
	} else {
		$description = Common::option('description');
		$description = Common::option('keyword');
	}
	Html::meta(['name|viewport' => 'width=device-width, initial-scale=1', 'name|description' => $description, 'name|keywords' => $keyword]);
	?>
	<?=Html::css('@root/assets/css/materialize.min.css')?>
	<?=Html::css('@root/assets/css/style.css')?>