<?php
use \sy\base\Router;
use \blog\model\Article;
use \blog\model\Meta;
use \blog\libs\Html;
use \blog\libs\Common;
$homeurl = Router::createUrl();
?>
	<nav>
		<div class="nav-wrapper">
			<a href="<?=$homeurl?>" class="brand-logo"><?=Common::option('sitename')?></a>
			<ul id="nav-mobile" class="right">
				<?php
				$m = Meta::getList(['type' => 1]);
				while ($one = $m->next()) {
					echo '<li';
					if ($one->id == $tid) {
						echo ' class="active"';
					}
					echo '><a href="' , Router::createUrl(['index/article/list', 'type' => 'id', 'val' => $one->id, 'page' => 1]), '">';
					$one->title();
					echo '</a></li>';
				}
				?>
			</ul>
		</div>
	</nav>