<?php
use \sy\base\Router;
use \blog\model\Article;
use \blog\model\Meta;
use \blog\libs\Html;
use \blog\libs\Common;
?>
	<aside class="col s3">
		<div class="card-panel">
			<h4>Tags</h4>
			<div>
			<?php
			$meta = Meta::getList(['limit' => '0,6', 'sort' => ['num', 'DESC']]);
			while ($one = $meta->next()) {
				echo '<p><a href="' . Router::createUrl(['index/article/list', 'type' => 'id', 'val' => $one->id, 'page' => 1]) . '">' . $one->title . '</a></p>';
			}
			?>
			</div>
		</div>
	</aside>