<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> <?php if($info['id']){?>编辑<?php }else{?>新增<?php }?>用户
				</div>
				
			</div>
			<div class="portlet-body form">
				<form role="form" action="<?php echo $_SERVER['REQUEST_URI']?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
                <input type="hidden" name="id" value="<?php echo $info['id'] ?: "";?>">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">用户名</label>
							<div class="col-md-9">
								<input type="text" name="username" value="<?php echo $info['username'] ?: "";?>" placeholder="用户名" class="form-control">
							</div>
						</div>		
                        <div class="form-group">
							<label class="col-md-3 control-label">密码</label>
							<div class="col-md-9">
								<input type="password" name="password" value="" placeholder="用户密码不能少于6位" class="form-control">
							</div>
						</div>	
                        <div class="form-group">
							<label class="col-md-3 control-label">确认密码</label>
							<div class="col-md-9">
								<input type="password" name="repassword" value="" placeholder="用户密码不能少于6位" class="form-control">
							</div>
						</div>	
                        <div class="form-group">
							<label class="col-md-3 control-label">邮箱</label>
							<div class="col-md-9">
								<input type="text" name="email" value="<?php echo $info['email'] ?: "";?>" placeholder="" class="form-control">
							</div>
						</div>				
						
						
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>