<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> 修改密码
				</div>
				
			</div>
			<div class="portlet-body form">
				<form role="form" action="<?php echo $_SERVER['REQUEST_URI']?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">原密码：</label>
							<div class="col-md-9">
								<input type="password" name="old" placeholder="" class="form-control">
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">新密码：</label>
							<div class="col-md-9">
								<input type="password" name="password" placeholder="" class="form-control">
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">确认密码：</label>
							<div class="col-md-9">
								<input type="password" name="repassword" placeholder="" class="form-control">
							</div>
						</div>	
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>