<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "photo_album"
 *
 * Auto generated by Extension Builder 2019-08-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '相册管理',
    'description' => '',
    'category' => 'plugin',
    'author' => 'yangshichang',
    'author_email' => 'yangshichang@ngoos.org',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
