<?php
$settings = array(
    'formId' => 'blockType-nodeList',
    'form' => array(
        'action' => '',
        'method' => 'post',
        'class' => array(),
        'ajaxSubmit' => 'right_handle',
        'accept-charset' => 'utf-8',
        'role' => 'form',
        'id' => 'blockType-nodeList',
    ),
    'machine' => array(
        'label' => '机读名',
        'error' => '',
        'userOptions' => array(),
        'description' => '机读名',
        'field' => 'string',
        'widget' => 'Text',
        'filter' => array('striptags'),
        'validate' => array(),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'name' => array(
        'label' => '区块名',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'string',
        'widget' => 'Text',
        'validate' => array(),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'limit' => array(
        'label' => '获取数量',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'number',
        'widget' => 'Text',
        'validate' => array(),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'nodeType' => array(
        'label' => '内容类型',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'string',
        'widget' => 'Select',
        'options' => nodeTypeList(),
        'validate' => array(),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'state' => array(
        'label' => '状态',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'string',
        'widget' => 'Select',
        'validate' => array(),
        'options' => array(
            0 => '不筛选',
            1 => '正常',
            2 => '垃圾箱',
        ),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'uid' => array(
        'label' => '用户',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'string',
        'widget' => 'Text',
        'validate' => array(),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'comment' => array(
        'label' => '评论',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'number',
        'widget' => 'Select',
        'validate' => array(),
        'options' => array(
            0 => '不筛选',
            1 => '开启评论文章',
            2 => '未开启评论',
        ),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'top' => array(
        'label' => '是否置顶',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'number',
        'widget' => 'Select',
        'validate' => array(),
        'options' => array(
            0 => '不筛选',
            1 => '置顶',
            2 => '非置顶',
        ),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'hot' => array(
        'label' => '是否热点',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'number',
        'widget' => 'Select',
        'validate' => array(),
        'options' => array(
            0 => '不筛选',
            1 => '热点',
            2 => '非热点',
        ),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'essence' => array(
        'label' => '是否精华',
        'error' => '',
        'userOptions' => array(),
        'description' => '',
        'field' => 'number',
        'widget' => 'Select',
        'validate' => array(),
        'options' => array(
            0 => '不筛选',
            1 => '精华',
            2 => '非精华',
        ),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'cache' => array(
        'label' => '缓存时间',
        'error' => '',
        'userOptions' => array(),
        'description' => '内容缓存时间，如果不缓存请设置为0',
        'field' => 'number',
        'widget' => 'Text',
        'validate' => array(),
        'filter' => array('striptags'),
        'attributes' => array(
            'class' => 'form-control',
        ),
        'required' => true,
    ),
    'settings' => array(
        'save' => '\Modules\Region\Library\Form::saveBlock',
    ),
);
