<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_front_edit"
 *
 * Auto generated by Extension Builder 2014-08-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News Front Edit',
	'description' => '',
	'category' => 'plugin',
	'author' => 'TaoJiang',
	'author_email' => 'ribeter267@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);