<?php return array (
  'base' => 
  array (
    'name' => 'category',
    'comment' => '分类表',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0
    ),
    'name' => 
    array (
      'name' => 'name',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '名称',
      'type' => 'string',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'en_name' => 
    array (
      'name' => 'en_name',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '英文名称',
      'type' => 'string',
      'length' => '40',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'pic_dir' => 
    array (
      'name' => 'pic_dir',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '关联图片地址',
      'type' => 'string',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'father_id' => 
    array (
      'name' => 'father_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '父级分类id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"category","field"=>"id","select"=>["name"],"comment"=>"父级分类","filter"=>"id!=0"],
    ),
    'father_path' => 
    array (
      'name' => 'father_path',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '父级分类路径',
      'type' => 'string',
      'length' => '500',
      'in_list' => 0,
      'in_show' => 0,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'module' => 
    array (
      'name' => 'module',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '应用模型',
      'type' => 'enum',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'enum' => [
        "article"=>["key"=>"article","value"=>"文章"],
        "link"=>["key"=>"link","value"=>"链接"],
        "album"=>["key"=>"album","value"=>"相册"],
        "topic"=>["key"=>"topic","value"=>"专题"]
      ]
    ),
    'weight' => 
    array (
      'name' => 'weight',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '排序权重',
      'type' => 'number',
      'length' => '6',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_visible' => 
    array (
      'name' => 'is_visible',
      'null' => 'YES',
      'key' => '',
      'default' => true,
      'comment' => '是否可见',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_delete' => 
    array (
      'name' => 'is_delete',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '是否删除',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);