<?php return array (
  'base' => 
  array (
    'name' => 'comment',
    'comment' => '评论表',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'object' => 
    array (
      'name' => 'object',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '评论实体',
      'type' => 'string',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'object_id' => 
    array (
      'name' => 'object_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '评论实体id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'father_id' => 
    array (
      'name' => 'father_id',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '父级评论id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'content' => 
    array (
      'name' => 'content',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '内容',
      'type' => 'fulltext',
      'length' => 0,
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_at' => 
    array (
      'name' => 'created_at',
      'null' => 'YES',
      'key' => '',
      'default' => 'CURRENT_TIMESTAMP',
      'comment' => '创建时间',
      'type' => 'datetime',
      'length' => 19,
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '创建用户id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_visible' => 
    array (
      'name' => 'is_visible',
      'null' => 'YES',
      'key' => '',
      'default' => true,
      'comment' => '是否显示',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_delete' => 
    array (
      'name' => 'is_delete',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '是否已删除',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);