<?php return array (
  'base' => 
  array (
    'name' => 'file',
    'comment' => '',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'title' => 
    array (
      'name' => 'title',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '文件标题',
      'type' => 'string',
      'length' => '100',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'description' => 
    array (
      'name' => 'description',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '文件描述',
      'type' => 'text',
      'length' => 0,
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'object' => 
    array (
      'name' => 'object',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '实体',
      'type' => 'string',
      'length' => '50',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'object_id' => 
    array (
      'name' => 'object_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '实体id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'file_path' => 
    array (
      'name' => 'file_path',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '文件路径',
      'type' => 'string',
      'length' => '500',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_at' => 
    array (
      'name' => 'created_at',
      'null' => 'NO',
      'key' => '',
      'default' => 'CURRENT_TIMESTAMP',
      'comment' => '创建时间',
      'type' => 'datetime',
      'length' => 11,
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '创建人',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_visible' => 
    array (
      'name' => 'is_visible',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '是否可见',
      'type' => 'number',
      'length' => '4',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_delete' => 
    array (
      'name' => 'is_delete',
      'null' => 'NO',
      'key' => '',
      'default' => '0',
      'comment' => '是否删除',
      'type' => 'number',
      'length' => '4',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'view_num' => 
    array (
      'name' => 'view_num',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '下载量',
      'type' => 'string',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);