<?php return array (
  'base' => 
  array (
    'name' => 'menu',
    'comment' => '导航表',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'title' => 
    array (
      'name' => 'title',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '标题',
      'type' => 'string',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'description' => 
    array (
      'name' => 'description',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '描述',
      'type' => 'string',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'img_dir' => 
    array (
      'name' => 'img_dir',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '图片地址',
      'type' => 'img',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'object' => 
    array (
      'name' => 'object',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '内部实体',
      'type' => 'enum',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'enum' => [
        "category"=>["key"=>"category","value"=>"分类"],
        "article"=>["key"=>"article","value"=>"文章"],
        "link"=>["key"=>"link","value"=>"链接"],
        "album"=>["key"=>"album","value"=>"相册"],
        "picture"=>["key"=>"picture","value"=>"图片"],
        "topic"=>["key"=>"topic","value"=>"专题"]
      ]
    ),
    'object_id' => 
    array (
      'name' => 'object_id',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '内部实体id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'url' => 
    array (
      'name' => 'url',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '外部链接',
      'type' => 'string',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'father_id' => 
    array (
      'name' => 'father_id',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '父级导航id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"menu","field"=>"id","select"=>["title"],"comment"=>"父级导航","filter"=>"id!=0"],
    ),
    'is_visible' => 
    array (
      'name' => 'is_visible',
      'null' => 'YES',
      'key' => '',
      'default' => true,
      'comment' => '是否显示',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'weight' => 
    array (
      'name' => 'weight',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '排序权重',
      'type' => 'number',
      'length' => '6',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);