<?php return array (
  'base' => 
  array (
    'name' => 'picture',
    'comment' => '图片表',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'album_id' => 
    array (
      'name' => 'album_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '所属相册id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"album","field"=>"id","select"=>["title"],"comment"=>"所属相册","filter"=>""],
    ),
    'title' => 
    array (
      'name' => 'title',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '标题',
      'type' => 'string',
      'length' => '40',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'description' => 
    array (
      'name' => 'description',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => '描述',
      'type' => 'string',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'dir' => 
    array (
      'name' => 'dir',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '路径',
      'type' => 'img',
      'length' => '200',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_at' => 
    array (
      'name' => 'created_at',
      'null' => 'YES',
      'key' => '',
      'default' => 'CURRENT_TIMESTAMP',
      'comment' => '创建时间',
      'type' => 'datetime',
      'length' => 19,
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '创建用户id',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"user","field"=>"id","select"=>["name"],"comment"=>"创建用户","filter"=>""],
    ),
    'is_visible' => 
    array (
      'name' => 'is_visible',
      'null' => 'YES',
      'key' => '',
      'default' => true,
      'comment' => '是否可见',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'is_delete' => 
    array (
      'name' => 'is_delete',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '是否已删除',
      'type' => 'boolean',
      'length' => '1',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'weight' => 
    array (
      'name' => 'weight',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '排序权重',
      'type' => 'number',
      'length' => '6',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);