<?php return array (
  'base' => 
  array (
    'name' => 'topic_category',
    'comment' => '',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'topic_id' => 
    array (
      'name' => 'topic_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '专题页id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"topic","field"=>"id","select"=>["title"],"comment"=>"专题","filter"=>""],
    ),
    'category_module' => 
    array (
      'name' => 'category_module',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '关联分类的模型',
      'type' => 'enum',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'enum' => [
        "article"=>["key"=>"article","value"=>"文章"],
        "link"=>["key"=>"link","value"=>"链接"],
        "album"=>["key"=>"album","value"=>"相册"],
        "topic"=>["key"=>"topic","value"=>"专题"]
      ]
    ),
    'category_id' => 
    array (
      'name' => 'category_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '关联分类的id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"category","field"=>"id","select"=>["name"],"comment"=>"分类","filter"=>"id!=0"],
    ),
    'config' => 
    array (
      'name' => 'config',
      'null' => 'YES',
      'key' => '',
      'default' => NULL,
      'comment' => 'json配置',
      'type' => 'string',
      'length' => '200',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'weight' => 
    array (
      'name' => 'weight',
      'null' => 'YES',
      'key' => '',
      'default' => '0',
      'comment' => '排序权重',
      'type' => 'number',
      'length' => '6',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);