<?php return array (
  'base' => 
  array (
    'name' => 'user',
    'comment' => '用户表',
    'opera' => 
    array (
      'show' => 1,
      'store' => 1,
      'update' => 1,
      'destroy' => 1,
      'search' => 1,
      'filter' => 1,
      'page' => 1,
    ),
  ),
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'null' => 'NO',
      'key' => 'PRI',
      'default' => NULL,
      'comment' => '',
      'type' => 'number',
      'length' => '11',
      'in_list' => 0,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 0,
    ),
    'name' => 
    array (
      'name' => 'name',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '用户名',
      'type' => 'string',
      'length' => '20',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 1,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
    'password' => 
    array (
      'name' => 'password',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '密码',
      'type' => 'string',
      'length' => '62',
      'in_list' => 0,
      'in_show' => 0,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 0,
      'in_sort' => 0,
    ),
    'role_id' => 
    array (
      'name' => 'role_id',
      'null' => 'NO',
      'key' => '',
      'default' => NULL,
      'comment' => '角色id',
      'type' => 'relate',
      'length' => '11',
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 1,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
      'relate' => ["table"=>"role","field"=>"id","select"=>["name"],"comment"=>"角色","filter"=>""],
    ),
    'created_at' => 
    array (
      'name' => 'created_at',
      'null' => 'YES',
      'key' => '',
      'default' => 'CURRENT_TIMESTAMP',
      'comment' => '',
      'type' => 'datetime',
      'length' => 11,
      'in_list' => 1,
      'in_show' => 1,
      'in_store' => 0,
      'in_search' => 0,
      'in_filter' => 1,
      'in_sort' => 1,
    ),
  ),
);