<?php 

$auth = $_SESSION['auth'];
if (empty($auth)) die('用户未登录！');

global $config;
if (!in_array($auth['id'], $config['manager'])) die('用户权限不够!');
?>
<?php require_once('finance/inc/nav_sub_im.html') ?>
<div class="container finance-item-add" style="padding-top:15px">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h3><span class="glyphicon glyphicon-edit"></span> 发布公告</h3>
			<hr class="solid">
			<div class="col-md-12 column">
				<form class="form-horizontal" action="?c=finance&a=do_issue_add" method="post">
					<fieldset>
						<!-- select -->
						<div class="form-group">
							<label class="col-md-2 control-label">公告类别</label>  
							<div class="col-md-7">
								<select name="kind" class="form-control">
									<option value="PTGG">平台公告</option>
									<option value="HKGG">还款公告</option>
									<option value="MTBD">媒体报道</option>
								</select>
							</div>
						</div>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-2 control-label">公告标题</label>  
							<div class="col-md-7">
								<input name="title" type="text" placeholder="公告标题" class="form-control input-md" required="">
							</div>
						</div>

						<!-- Text input-->
						<br>
						<div class="form-group">
							<label class="col-md-2 control-label">公告内容</label>  
							<div class="col-md-9">
								<textarea id="issue_content" name="content" type="text" class="form-control input-md finance-item-well" style="height:800px" required=""></textarea>
							</div>
						</div>


						<!-- token -->
						<input type="hidden" name="token" value="<?php echo get_token() ?>"/>

						<!-- Button -->
						<br>
						<div class="form-group">
							<label class="col-md-2 control-label"></label>
							<div class="col-md-2">
								<button onclick="save_input()" class="btn btn-primary btn-block">发布公告</button>
							</div>
						</div>

					</fieldset>
				</form>	


			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

var issue_content = UM.getEditor("issue_content");  

$(document).ready(function(){
		recover_input(); 
		});


function recover_input() {
	$("input").each(function(){
			if ('token' != $(this).attr('name')) {
			$(this).val(getCookie('issue_add_'+$(this).attr('name'))); 
			}
			});
}

function save_input() {
	$("input").each(function(){ setCookie('issue_add_'+$(this).attr('name'), $(this).val(), 365, '/'); });
}

</script>
