<?php require_once('finance/inc/item_kind.php'); ?>
<?php $lmcy_id = @intval($_GET['lmcy_id']); ?>
<?php if (empty($lmcy_id)) { ?>
<?php require_once('finance/inc/nav_sub_rz.html') ?>
<?php } else { ?>
<div class="finance-lmcy-h-img" style="background-image:url('img/finance/lmcy/h_img/<?php echo $lmcy_id ?>')">
	<div class="container">
		<div class="row clearfix">
			<div class="col-md-9 column"> </div>
			<div class="col-md-3 column">
				<a class="btn btn-success btn-lg" href="<?php echo s_url('?c=finance&a=item_list_cond&lmcy_id='.$lmcy_id) ?>">我要投资</a>
			</div>
		</div>
	</div>
</div>
<?php } ?>
<div class="container" style="padding-top:30px">
	<div class="row clearfix">
		<?php foreach ($item_kind as $key => $kind) { ?>
		<div class="col-md-4 column">
			<div class="finance-item-add finance-item-add-index">
				<h3><?php echo $kind['name'] ?></h3>
				<hr class="dashed">
				<ul class="list-unstyled">
					<li>适用区域：<?php echo $kind['location'] ?></li>
					<li>借款期限：<?php echo $kind['term'] ?></li>
					<li>收款速度：<?php echo $kind['receive'] ?></li>
					<li>借款成本：<?php echo $kind['cost'] ?></li>
				</ul>
				<hr class="dashed">                
				<a class="btn btn-success" href="<?php echo s_url('?c=finance&a=item_add&kind='.$key.'&lmcy_id='.$lmcy_id) ?>">立即申请</a>
			</div>
		</div>
		<?php } ?>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
		$("li#finance_rz").addClass("active");
		$('li#rz_ptrz').addClass('active');
		});

</script>
