<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\service;

use app\admin\model\User;
use app\common\service\BaseService;

/**
 * 会员管理-服务类
 * @author 牧羊人
 * @since 2020/7/11
 * Class UserService
 * @package app\admin\service
 */
class UserService extends BaseService
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/11
     */
    public function initialize()
    {
        parent::initialize();
        $this->model = new User();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2020/7/11
     * @author 牧羊人
     */
    public function edit()
    {
        // 请求参数
        $data = request()->param();
        // 头像处理
        $avatar = trim($data['avatar']);
        if (strpos($avatar, "temp")) {
            $data['avatar'] = save_image($avatar, 'user');
        }
        // 出生日期
        if ($data['birthday']) {
            $data['birthday'] = strtotime($data['birthday']);
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }
}
