<div class="content-wrapper">
    <?php
    $form = $this->form;
    $form->prepare();

    $form->get('unitName')->setAttributes([
        'placeholder' => $this->translate('计量单位名称')
    ]);

    $form->get('unitSort')->setAttributes([
        'placeholder' => $this->translate('排序')
    ]);

    ?>
    <?= $this->form()->openTag($form); ?>
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('unit');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?=$this->translate('返回计量单位列表')?></a>
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?=$this->translate('保存计量单位')?></button>
            <?=(isset($unit) ? $this->HelpUrl('unitEdit') : $this->HelpUrl('unitnAdd'))?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=((isset($unit) && $unit->getUnitId()) ? $this->translate('编辑单位') : $this->translate('添加单位'))?></h3>
                    </div>

                    <div class="box-body">
                        <?=$this->formElementErrors($form->get('dberp_csrf'), ['class'=>'error-message']); ?>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('计量单位')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-6">
                                <?= $this->formElement($form->get('unitName')); ?>
                                <?= $this->formElementErrors($form->get('unitName'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-sm-2 control-label"><?=$this->translate('排序')?><span class="must_add_value">*</span></label>
                            <div class="col-sm-2">
                                <?= $this->formElement($form->get('unitSort')); ?>
                                <?= $this->formElementErrors($form->get('unitSort'), ['class'=>'error-message']); ?>
                            </div>
                        </div>

                    </div>

                    <div>
                        <div class="box-footer">
                            <?=$this->formElement($form->get('dberp_csrf')); ?>
                            <button type="submit" class="btn btn-primary col-md-offset-2"><i class="fa fa-check"></i> <?=$this->translate('保存计量单位')?></button>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </section>
    <?= $this->form()->closeTag(); ?>

</div>
<script>
    $(document).ready(function() {
        $("#<?=$form->getName()?>").validate({
            rules: {
                unitName: {
                    required: true
                },
                unitSort: {
                    required: true,
                    number: true,
                    min: 1
                }
            },
            messages: {
                unitName: {
                    required: "<?=$this->translate('计量单位不能为空！')?>"
                },
                unitSort: {
                    required: "<?=$this->translate('排序不能为空！')?>",
                    number: "<?=$this->translate('排序必须为数字！')?>",
                    min: "<?=$this->translate('排序最小为1！')?>"
                }
            }
        });
    });
</script>
