<?php
// +----------------------------------------------------------------------
// | Copyright (c) 2017 http://www.sycit.cn
// +----------------------------------------------------------------------
// | Author: Peter.Zhang  <hyzwd@outlook.com>
// +----------------------------------------------------------------------
// | Date:   2017/9/6
// +----------------------------------------------------------------------
// | Title:  AuthRule.php
// +----------------------------------------------------------------------
namespace app\index\model;

use think\Model;

class AuthRule extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}