<?php
if(!defined('INSTALL_STATUS')) exit('Access Denied');
$lang = array(
	'install_license' => '公司网站系统-安装用户协议',
	'install_is_lock' => '您已成功安装HDCWS，需重新安装请手动删除网站目录下install/install.lock文件', 
	'install_db_error' => '数据库文件无法读取，请检查install/inc/web.sql是否存在。',
	'install_title' => 'HDCWS 1.0 安装向导',
	'welcome_to_install' => '欢迎安装',
	'install_wizard' => '安装向导',
	'install_error' => '安装出错',
	'install_tips' => '注意事项',
	'install_tips_content' => '这个安装程序仅仅用在你首次安装HDCWS。如果你已经在使用 HDCWS 或者要更新到一个新版本，请不要运行这个安装程序。',
	'install_notes' => '安装须知',
	'install_notes_content' => '<p>一、运行环境需求：PHP(5.2.0+)+MYSQL(4.1+)</p><p>二、安装步骤：<br />1、使用ftp工具以二进制模式，将该软件包里的 HDCWS 目录下的文件上传到您的空间，假设上传后目录网站根目录。<br />2、如果您使用的是Linux 或 Freebsd 服务器，先确认以下目录或文件属性为 (777) 可写模式。<br />目录: install<br />文件: config.php<br />3、运行 http://www.hidoger.com/install/index.php 安装程序，填入安装相关信息与资料，完成安装！<br />4、运行 http://www.hidoger.com/index.php 开始体验HDCWS 1.0版！<br /></p>',
	'install_env' => '运行环境检测',
	'php_os' => '操作系统',
	'php_version' => 'PHP版本',
	'file_upload' => '附件上传',
	'php_extention' => 'PHP扩展',
	'php_extention_unload_gd' => '您的服务器没有安装这个PHP扩展：gd',
	'php_extention_unload_mbstring' => '您的服务器没有安装这个PHP扩展：mbstring',
	'php_extention_unload_mysql' => '您的服务器没有安装这个PHP扩展：mysql',
	'php_extention_unload_curl' => '您的服务器没有安装这个PHP扩展：curl',
	'mysql' => 'MySQL数据库',
	'mysql_unsupport' => '您的服务器不支持MYSQL数据库，无法安装HDCWS。',
	'dirmod' => '目录和文件属性',
	'install_setting' => '数据库设置',
	'install_mysql_host' => '数据库服务器',
	'install_mysql_host_intro' => '数据库服务器地址，一般为 localhost，或为IP地址',
	'install_mysql_username' => '数据库帐号',
	'install_mysql_password' => '数据库密码',
	'install_mysql_name' => '数据库名称',
    'install_mysql_name_intro' => '同名数据库将被覆盖，请做好备份',
	'install_mysql_prefix' => '数据表前缀',
	'install_mysql_prefix_intro' => '同一数据库安装多HDCWS程序时可改变默认值',
	'founder' => '管理员帐号设置',
	'install_founder_name' => '超级管理员帐号',
	'install_founder_password' => '管理员密码',
	'install_founder_rpassword' => '确认密码',
	
	'install_mysql_host_empty' => '数据库服务器不能为空',
	'install_mysql_username_empty' => '数据库帐号不能为空',
	'install_mysql_name_empty' => '数据库名称不能为空',
	'install_founder_name_empty' => '创建管理员帐号不能为空',
	'install_founder_password_length' => '管理员密码必须大于6位',
	
	'mysql_invalid_configure' => '数据库配置信息不完整',
	'mysql_invalid_prefix' => '您指定的数据表前缀包含点字符(".")，请返回修改。',
	'forbidden_character' => '用户名包含非法字符',
	'founder_invalid_email' => '电子邮件格式不正确',
	'founder_invalid_configure' => '创建者信息不完整',
	'founder_invalid_password' => '密码长度必须大于或等于6位',
	'config_log_success' => '数据库配置信息写入完成',
	'config_read_failed' => '数据库配置文件写入错误，请检查config.ini.php文件是否存在或属性是否为777',
	'yycms_rebuild' => '数据库中已经安装过 HDCWS，继续安装会清空原有数据！',
	'mysql_import_data' => '点击下一步开始导入数据',
	'import_processing' => '导入数据库',
	'import_processing_error' => '导入数据库失败',
	'create_table' => '创建表',
	'create_founder' => '创建超级管理员帐号',
	'create_founder_success' => '超级管理员帐号创建成功',
	'create_founder_error' => '超级管理员帐号创建失败',
	'install_success' => '安装成功',
	'install_failure' => '安装失败',
	'reinstall' => '<a href="index.php">请点击这里重新安装</a>',
	'install_success_intro' => '安装程序执行完毕，请尽快删除整个 install 目录，以免被他人恶意利用。如要重新安装，请删除install目录中的 install.lock 文件！',
	'install_dbFile_error' => '数据库文件无法读取，请检查install/inc/web.sql是否存在。',
	
	'install_step_license' => '1.许可协议',
	'install_step_os' => '2.环境检测',
	'install_step_option' => '3.安装配置',
	'install_step_finish' => '4.安装完成',
	
	'install_btn_start' => '开始安装',
	'install_btn_prev' => '上一步',
	'install_btn_next' => '下一步',
	'support' => '支持',
	'unsupport' => '不支持',
    'mustopen' => '必须开启',
	'suggestopen' => '建议开启',
);
?>