<div class="page-slider margin-bottom-40">
  <div class="fullwidthbanner-container revolution-slider">
    <div class="fullwidthabnner" style="text-shadow: 0 0px 1px rgba(0,0,0,0.5),0 2px 5px #000,0 2px 1px #000,0 0 10px #000,0 0 20px rgba(0,0,0,0.5);">
      <ul id="revolutionul">
        <!-- THE NEW SLIDE -->
        <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="4000" data-thumb="<?php echo STATIC_URL?>/img/demo/ly1.jpg">
          <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
          <img src="<?php echo STATIC_URL?>/img/demo/ly1.jpg" alt="">
          
          <div class="caption slide_title_white"
            data-x="center"
            data-y="center"
            data-speed="400"
            data-start="1500"
            data-easing="easeOutExpo">
            <span class="slide_title_white_bold">游心旅行 管家招募</span> <br />
            <a class="btn green" href="/">查看详情</a>
          </div>
        </li>
        <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="4000" data-thumb="<?php echo STATIC_URL?>/img/demo/ly2.jpg">
          <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
          <img src="<?php echo STATIC_URL?>/img/demo/ly2.jpg" alt="">
          
          <div class="caption slide_title_white"
            data-x="center"
            data-y="center"
            data-speed="400"
            data-start="1500"
            data-easing="easeOutExpo">
            <span class="slide_title_white_bold">大美欧洲 七日自由之旅</span> <br />
            <a class="btn green" href="/">查看详情</a>
          </div>
        </li>
        <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="4000" data-thumb="<?php echo STATIC_URL?>/img/demo/ly3.jpg">
          <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
          <img src="<?php echo STATIC_URL?>/img/demo/ly3.jpg" alt="">
          
          <div class="caption slide_title_white"
            data-x="center"
            data-y="center"
            data-speed="400"
            data-start="1500"
            data-easing="easeOutExpo">
            <span class="slide_title_white_bold">高端奢华酒店 优质航空公司</span> <br />
            <a class="btn green" href="/">查看详情</a>
          </div>
        </li>
        <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="4000" data-thumb="<?php echo STATIC_URL?>/img/demo/ly4.jpg">
          <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
          <img src="<?php echo STATIC_URL?>/img/demo/ly4.jpg" alt="">
          
          <div class="caption slide_title_white"
            data-x="center"
            data-y="center"
            data-speed="400"
            data-start="1500"
            data-easing="easeOutExpo">
            <span class="slide_title_white_bold">畅游美西一号公路 11日深度自驾旅行</span> <br />
            <a class="btn green" href="/">查看详情</a>
          </div>
        </li>
        <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="4000" data-thumb="<?php echo STATIC_URL?>/img/demo/ly5.jpg">
          <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
          <img src="<?php echo STATIC_URL?>/img/demo/ly5.jpg" alt="">
          
          <div class="caption slide_title_white"
            data-x="center"
            data-y="center"
            data-speed="400"
            data-start="1500"
            data-easing="easeOutExpo">
            <span class="slide_title_white_bold">缤纷澳妙纯净假期 11日亲子旅行</span> <br />
            <a class="btn green" href="/">查看详情</a>
          </div>
        </li>
                    
      </ul>
      <div class="tp-bannertimer tp-bottom"></div>
    </div>
  </div>
</div>



<div class="team-block content content-center margin-bottom-40" id="team">
    <div class="container">
      <h2>游心 <strong>旅行管家</strong> 团队 <strong>2000名管家</strong></h2>
      <h4>游心旅行管家来自于专业的旅游服务行业，可以为您量身打造最适合您的出行计划，并且全程提供专业的旅行服务</h4>
      <div class="row">
        <div class="col-md-4 item">
          <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/people/img6-large.jpg" alt="Marcus Doe" class="img-responsive">
          <h3>张某某</h3>
          <em>太美团队</em>
          <p>20年高端旅游行业从业经验，曾经服务过超过3万人次的出境游，丰富的目的地相关知识储备，为您出行节省大量时间</p>
          
        </div>
        <div class="col-md-4 item">
          <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/people/img7-large.jpg" alt="Elena Taylor" class="img-responsive">
          <h3>李某某</h3>
          <em>美国SABC地接社</em>
          <p>全美最大华人地接社，从业10余年，对北美各地非常熟悉</p>
          
        </div>
        <div class="col-md-4 item">
          <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/people/img8-large.jpg" alt="Cris Nilson" class="img-responsive">
          <h3>刘某某</h3>
          <em>欧洲自由行达人</em>
          <p>在欧洲徒步了两年，行程达8万公里</p>
          
        </div>
      </div>
    </div>
</div>


<div class="message-block content content-center valign-center" id="message-block">
    <div class="valign-center-elem">
      <h2>无论你身在何方 无论你想去往何处 <strong>游心，您的贴身旅行管家</strong></h2>
    </div>
</div>

<div class="portfolio-block content content-center" id="portfolio">
    <div class="container">
      <h2 class="margin-bottom-50">目的地 <strong>3000个热门玩法</strong></h2>
    </div>
    <div class="row">
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/1.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/1.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/2.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/2.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/3.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/3.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/4.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/4.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/5.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/5.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/6.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/6.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/7.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/7.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/8.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/8.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/9.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/9.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/10.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/10.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/3.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/3.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
      <div class="item col-md-2 col-sm-6 col-xs-12">
        <img src="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/5.jpg" alt="NAME" class="img-responsive">
        <a href="<?php echo STATIC_URL?>/theme/assets/frontend/onepage/img/portfolio/5.jpg" class="zoom valign-center">
          <div class="valign-center-elem">
            <strong>意大利缤纷浪漫诗 11日深度旅行</strong>
            <em>12,999 元/人起 </em>
            <b>查看详情</b>
          </div>
        </a>
      </div>
    </div>
</div>



<div class="prices-block content content-center" id="prices">
    <div class="container">
      <h2 class="margin-bottom-50"><strong>限时抢购</strong> 游心专属 每周更新</h2>
      <div class="row">
        <!-- Pricing item BEGIN -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="pricing-item">
            <div class="pricing-head">
              <h3>意大利缤纷浪漫诗 11日深度旅行</h3>
            </div>
            <div class="pricing-content">
              <div class="pi-price">
                <strong>$<em>19</em></strong>
                <p>每人</p>
              </div>
              <ul class="list-unstyled">
                <li><i class="fa fa-circle"></i> 往返机票</li>
                <li><i class="fa fa-circle"></i> 酒店专车接送</li>
                <li><i class="fa fa-circle"></i> 私人导游</li>
              </ul>
            </div>
            <div class="pricing-footer">
              <a class="btn btn-default" href="javascript:void(0);">立刻出发</a>
            </div>
          </div>
        </div>
        <!-- Pricing item END -->
        <!-- Pricing item BEGIN -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="pricing-item">
            <div class="pricing-head">
              <h3>意大利缤纷浪漫诗 11日深度旅行</h3>
            </div>
            <div class="pricing-content">
              <div class="pi-price">
                <strong>$<em>19</em></strong>
                <p>每人</p>
              </div>
              <ul class="list-unstyled">
                <li><i class="fa fa-circle"></i> 往返机票</li>
                <li><i class="fa fa-circle"></i> 酒店专车接送</li>
                <li><i class="fa fa-circle"></i> 私人导游</li>
              </ul>
            </div>
            <div class="pricing-footer">
              <a class="btn btn-default" href="javascript:void(0);">立刻出发</a>
            </div>
          </div>
        </div>
        <!-- Pricing item END -->
        <!-- Pricing item BEGIN -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="pricing-item">
            <div class="pricing-head">
              <h3>意大利缤纷浪漫诗 11日深度旅行</h3>
            </div>
            <div class="pricing-content">
              <div class="pi-price">
                <strong>$<em>19</em></strong>
                <p>每人</p>
              </div>
              <ul class="list-unstyled">
                <li><i class="fa fa-circle"></i> 往返机票</li>
                <li><i class="fa fa-circle"></i> 酒店专车接送</li>
                <li><i class="fa fa-circle"></i> 私人导游</li>
              </ul>
            </div>
            <div class="pricing-footer">
              <a class="btn btn-default" href="javascript:void(0);">立刻出发</a>
            </div>
          </div>
        </div>
        <!-- Pricing item END -->
        <!-- Pricing item BEGIN -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="pricing-item">
            <div class="pricing-head">
              <h3>意大利缤纷浪漫诗 11日深度旅行</h3>
            </div>
            <div class="pricing-content">
              <div class="pi-price">
                <strong>$<em>19</em></strong>
                <p>每人</p>
              </div>
              <ul class="list-unstyled">
                <li><i class="fa fa-circle"></i> 往返机票</li>
                <li><i class="fa fa-circle"></i> 酒店专车接送</li>
                <li><i class="fa fa-circle"></i> 私人导游</li>
              </ul>
            </div>
            <div class="pricing-footer">
              <a class="btn btn-default" href="javascript:void(0);">立刻出发</a>
            </div>
          </div>
        </div>
        <!-- Pricing item END -->
      </div>
    </div>
</div>


<div class="facts-block content content-center" id="facts-block">
    <h2>游心</h2>
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="item">
            <strong>2K+</strong>
            专业旅行管家
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="item">
            <strong>3K+</strong>
            目的地出行线路
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="item">
            <strong>1W+</strong>
            出行服务经验
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="item">
            <strong>24H</strong>
            24小时服务响应
          </div>
        </div>
        
      </div>
    </div>
</div>

<div class="choose-us-block content text-center margin-bottom-40" id="benefits">
    <div class="container">
      <h2>为什么 <strong>选择游心</strong></h2>
      <h4>游心旅行成立于2014年，是一家旅行体验至上的定制旅行平台，为实际出行配以细致的贴心服务，用完美体验重新定义你的每一次旅行。基于对用户需求的深刻洞察，对旅行意义的独到见解，以专业买手姿态搜罗全球景致，精选出涵盖自由行、定制旅行、半定制旅行及碎片化的一系列高性价比旅行产品，全方位满足个性化需求，让旅行自在，记忆游心</h4>
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12 text-left">
          <img src="<?php echo STATIC_URL?>/img/demo/ly7.jpg" alt="Why to choose us" class="img-responsive">
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12 text-left">
          <div class="panel-group" id="accordion1">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_1">自由旅途</a>
                </h5>
              </div>
              <div id="accordion1_1" class="panel-collapse collapse in">
                <div class="panel-body">
                  <p>国内知名品牌高端定制旅行机构合作发起，玩家甄选精品，全球主题旅行，目的地深度体验，一价全包服务。游心网精品度假产品线路覆盖全球，如"泰国"、"毛里求斯"、"美国"、"欧洲"、"俄罗斯"、"南非"、"日韩"等各色旅游线路。</p>
                  
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_2">当地游</a>
                </h5>
              </div>
              <div id="accordion1_2" class="panel-collapse collapse">
                <div class="panel-body">
                  <p>海外著名品牌旅行机构产品中国市场深度合作，不限出发地、当地游、英文环境、安全信赖、原汁原味，和老外一起游天下。最自由的旅行组合方式，是自在随性地畅游，还是跟随专人去探索当地文化，可随时变换旅行的节奏。</p>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_3">定制旅行</a>
                </h5>
              </div>
              <div id="accordion1_3" class="panel-collapse collapse">
                <div class="panel-body">
                  <p>记忆由心！我们心怀天下，放眼四海，集全球目的地之大成，选全球品牌伙伴之精华，"烹"旅行如小鲜，"礼"客户如家宾，用工匠情怀之心锻造每一次行走的记忆。量身剪裁旅行线路及碎片化服务，自驾游、主题游、亲子游、轻度探险游……你想要的，就是我们的使命。</p>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_4">度假产品</a>
                </h5>
              </div>
              <div id="accordion1_4" class="panel-collapse collapse">
                <div class="panel-body">
                  <p>全球甄选精品格调酒店中国市场合作推出，随套餐附送早餐、或接送机、或餐食、或当地观光等增值服务，最优性价比组合搭配，自由自在随心行。游心网拥有全球多家4星级以上酒店资源。</p>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_5">限时抢购</a>
                </h5>
              </div>
              <div id="accordion1_5" class="panel-collapse collapse">
                <div class="panel-body">
                  <p>限时、限量、限价格，不定时放送抢购</p>
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>
</div>
