<?php
require_once dirname(__FILE__).'/../include.php';
require_once dirname(__FILE__).'/../attendance/attendance_define.php';
require_once dirname(__FILE__).'/../model/EBAttendRecord.class.php';
require_once dirname(__FILE__).'/../model/EBAttendDaily.class.php';
require_once dirname(__FILE__).'/../model/EBAttendReq.class.php';
require_once dirname(__FILE__).'/../model/EBAttendReqItem.class.php';
require_once dirname(__FILE__).'/../model/EBAttendReqForm.class.php';
require_once dirname(__FILE__).'/../model/EBAttendTime.class.php';
require_once dirname(__FILE__).'/../model/EBAttendRule.class.php';
require_once dirname(__FILE__).'/../model/EBAttendSetting.class.php';
require_once dirname(__FILE__).'/../model/EBAttSetTarget.class.php';
require_once dirname(__FILE__).'/../model/EBHolidaySetting.class.php';
require_once dirname(__FILE__).'/../model/EBHolSetTarget.class.php';
require_once dirname(__FILE__).'/../model/EBUserDefine.class.php';
require_once dirname(__FILE__).'/../model/EBDictionaryInfo.class.php';
// require_once dirname(__FILE__).'/../model/EBShareUserForm.class.php';
// require_once dirname(__FILE__).'/../model/EBEmployeeInfo.class.php';
// require_once dirname(__FILE__).'/../model/EBEmployeeInfoForm.class.php';
// require_once dirname(__FILE__).'/../shareuser/ShareUserService.class.php';
// require_once dirname(__FILE__).'/../useraccount/UserAccountService.class.php';
// require_once dirname(__FILE__).'/../operaterecord/operaterecord.php';
// require_once dirname(__FILE__).'/../task/task.php';
require_once dirname(__FILE__).'/../shareuser/shareuser.php';
require_once dirname(__FILE__).'/../attendance/AttendRecordService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendDailyService.class.php';
require_once dirname(__FILE__).'/../attendance/HolidaySettingService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendReqItemService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendReqService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendSettingService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendTimeService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendRuleService.class.php';
require_once dirname(__FILE__).'/../attendance/AttendSetTargetService.class.php';
require_once dirname(__FILE__).'/../attendance/HolidaySetTargetService.class.php';
require_once dirname(__FILE__).'/../foundation/UserDefineService.class.php';
require_once dirname(__FILE__).'/../foundation/DictionaryInfoService.class.php';
require_once dirname(__FILE__).'/../useraccount/UserAccountService.class.php';
