#!/bin/sh  
pure_config_pl=/server/pureftpd/pure-config.pl
pure_ftpd_conf=/server/pureftpd/etc/pure-ftpd.conf

case "$1" in 
start)  
$pure_config_pl $pure_ftpd_conf
;;
stop)  
killall pure-ftpd
;;
status)  
ps -ef|grep pure-ftpd
;;
restart) 
killall pure-ftpd
sleep 3
$pure_config_pl $pure_ftpd_conf
;;
*)  
echo "Usage: `basename $0` {start | stop | restart | status}" >&2  
;;  
esac
