<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php
    $this->headtitle('DBErp管理后台');
    $this->headtitle('Powered by 珑大软件');
    echo $this->headTitle()->setSeparator(' - ');

    $this->headMeta()->appendName('author', '北京珑大钜商科技有限公司');
    $this->headMeta()->appendName('copyright', 'DBErp Inc. All Rights Reserved');

    $this->headMeta()->setAutoEscape(false);

    echo $this->headMeta();
    ?>
    <link rel="icon" href="<?php echo $this->basePath('favicon.ico'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/bootstrap/css/bootstrap.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome/css/font-awesome.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/Ionicons/css/ionicons.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('js/plugins/iCheck/all.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/AdminLTE.css'); ?>">

    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/skins/_all-skins.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/stylesheet.css'); ?>">

    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('js/html5shiv.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/respond.min.js'); ?>"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="<?php echo $this->basePath('css/bootstrap/js/bootstrap.min.js'); ?>"></script>
    <!-- iCheck -->
    <script src="<?php echo $this->basePath('js/plugins/iCheck/icheck.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/adminlte.js'); ?>"></script>

    <script src="<?php echo $this->basePath('js/plugins/jquery-validation/jquery.validate.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/jquery-validation/additional-methods.js'); ?>" ></script>

    <script src="<?php echo $this->basePath('js/plugins/layer/layer.js'); ?>" ></script>
    <script src="<?php echo $this->basePath('js/plugins/laydate/laydate.js'); ?>" ></script>

    <script src="<?=$this->basePath('js/plugins/echarts/echarts.min.js')?>"></script>
    <script src="<?=$this->basePath('js/plugins/echarts/theme/shine.js')?>"></script>

    <script src="<?=$this->basePath('js/plugins/jquery-number/jquery.number.min.js')?>"></script>

    <script src="<?php echo $this->basePath('js/headCommon.js'); ?>"></script>

</head>
<body class="hold-transition skin-purple sidebar-mini">
<div class="wrapper">
    <?php
    $moduleName = $this->currentRoute()->getModule();
    $controllerName = $this->currentRoute()->getController();
    ?>
    <?=$this->partial('layout/header', ['moduleName' => $moduleName, 'controllerName' => $controllerName]); ?>
    <?=$this->partial('layout/left', ['moduleName' => $moduleName, 'controllerName' => $controllerName]); ?>

    <?=$this->content;?>
    <?=$this->partial('layout/footer'); ?>

</div>
<script src="<?php echo $this->basePath('js/common.js'); ?>" ></script>
</body>
</html>
