<?php

use yii\db\Migration;

class m200731_161943_core_paylog extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%core_paylog}}', [
            'plid' => "bigint(11) unsigned NOT NULL AUTO_INCREMENT",
            'bloc_id' => "int(11) NULL",
            'store_id' => "int(11) NULL",
            'type' => "varchar(20) NOT NULL COMMENT '支付类型'",
            'openid' => "varchar(40) NOT NULL COMMENT 'openid'",
            'uniontid' => "varchar(64) NULL COMMENT '跨应用标识'",
            'tid' => "varchar(128) NULL",
            'fee' => "decimal(10,2) NOT NULL COMMENT '支付金额'",
            'status' => "tinyint(4) NOT NULL COMMENT '支付状态'",
            'module' => "varchar(50) NOT NULL COMMENT '模块'",
            'tag' => "varchar(2000) NOT NULL",
            'is_usecard' => "tinyint(3) unsigned NULL COMMENT '是否使用会员卡'",
            'card_type' => "tinyint(3) unsigned NULL COMMENT '会员卡类型'",
            'card_id' => "varchar(50) NULL COMMENT '会员卡id'",
            'card_fee' => "decimal(10,2) unsigned NULL COMMENT '会员卡余额'",
            'encrypt_code' => "varchar(100) NULL COMMENT '加密字符串'",
            'is_wish' => "tinyint(11) NULL",
            'create_time' => "int(11) NULL",
            'update_time' => "int(11) NULL",
            'PRIMARY KEY (`plid`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8");
        
        /* 索引设置 */
        $this->createIndex('idx_openid','{{%core_paylog}}','openid',0);
        $this->createIndex('idx_tid','{{%core_paylog}}','tid',0);
        $this->createIndex('uniontid','{{%core_paylog}}','uniontid',0);
        
        
        /* 表数据 */
        $this->insert('{{%core_paylog}}',['plid'=>'9','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>NULL,'tid'=>NULL,'fee'=>'40.00','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'10','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>NULL,'tid'=>NULL,'fee'=>'40.00','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'11','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449995152','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'12','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454975355','tid'=>NULL,'fee'=>'80.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'13','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455515510','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'14','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451100102','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'15','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498485155','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'16','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410256571','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'17','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455524949','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'18','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453981005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'19','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031452101971','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'20','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448514951','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'21','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499521004','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'22','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451549754','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'23','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499525351','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'24','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449531001','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'25','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453974950','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'26','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454511019','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'27','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410010198','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'28','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410055494','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'29','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455535548','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'30','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448515797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'31','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031497555655','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'32','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454574950','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'33','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448529799','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'34','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453539910','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'35','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455515410','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'36','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498501005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'37','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410048541','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'38','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031456495097','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'39','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498551005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'40','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448101571','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'41','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031450571015','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'42','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031457975110','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'43','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451101100','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'44','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448565453','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'45','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031497545051','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'46','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410156531','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'47','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498525010','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'48','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410151995','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'49','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451521005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'50','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453579797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'51','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499565256','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'52','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410298985','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'53','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455525410','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'54','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498495352','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'55','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031452545797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'56','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454971015','tid'=>NULL,'fee'=>'240.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'57','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449531009','tid'=>NULL,'fee'=>'0.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'58','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031599501025','tid'=>NULL,'fee'=>'0.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'59','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031555571021','tid'=>NULL,'fee'=>'0.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'60','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031654535557','tid'=>'','fee'=>'0.10','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'61','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031657981005','tid'=>'','fee'=>'0.15','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'62','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032151975653','tid'=>NULL,'fee'=>'0.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'63','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032110197100','tid'=>NULL,'fee'=>'0.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'64','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032199995652','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'65','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032157549749','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'66','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032110156975','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'67','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032149524850','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'68','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032154985397','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'69','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032156100555','tid'=>'','fee'=>'280.20','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'70','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032553100102','tid'=>NULL,'fee'=>'50.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'71','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032510053565','tid'=>NULL,'fee'=>'80.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'72','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032599975597','tid'=>NULL,'fee'=>'80.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'73','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032598545751','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'74','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032557974851','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'75','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032551565198','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'76','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032549499757','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'77','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032749485450','tid'=>NULL,'fee'=>'80.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'78','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032753565110','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'79','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020033010010199','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'80','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020033054544897','tid'=>NULL,'fee'=>'40.15','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'81','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020040151971015','tid'=>NULL,'fee'=>'130.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'82','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041149521001','tid'=>NULL,'fee'=>'18.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'83','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041598535649','tid'=>NULL,'fee'=>'3280.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'84','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041654481014','tid'=>NULL,'fee'=>'1000.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'85','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0Uvc4QkT_TgcfhgSfpO4LLQ','uniontid'=>'2020041651579957','tid'=>NULL,'fee'=>'200.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'86','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aRDVDME1L39dYWzt9bUGlI','uniontid'=>'2020041650565248','tid'=>NULL,'fee'=>'601.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'87','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0S5K7EMf1tCf1S3tIBXIbCw','uniontid'=>'2020041697569856','tid'=>NULL,'fee'=>'200.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'88','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041753535752','tid'=>NULL,'fee'=>'1697.50','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'89','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042948544910','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'90','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042955101565','tid'=>NULL,'fee'=>'402.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'91','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042997524957','tid'=>NULL,'fee'=>'402.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'92','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042910053495','tid'=>NULL,'fee'=>'357.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'93','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042952541025','tid'=>NULL,'fee'=>'357.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'94','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020051152971025','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'95','bloc_id'=>NULL,'store_id'=>NULL,'type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020051152559999','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>NULL,'update_time'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'96','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070849544899','tid'=>NULL,'fee'=>'12.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594180145','update_time'=>'1594180145']);
        $this->insert('{{%core_paylog}}',['plid'=>'97','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070950495156','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594288515','update_time'=>'1594288515']);
        $this->insert('{{%core_paylog}}',['plid'=>'98','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070910249101','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594288960','update_time'=>'1594288960']);
        $this->insert('{{%core_paylog}}',['plid'=>'99','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070949569856','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289474','update_time'=>'1594289474']);
        $this->insert('{{%core_paylog}}',['plid'=>'100','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070910052504','tid'=>NULL,'fee'=>'45.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289581','update_time'=>'1594289581']);
        $this->insert('{{%core_paylog}}',['plid'=>'101','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070953985699','tid'=>NULL,'fee'=>'45.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289653','update_time'=>'1594289653']);
        $this->insert('{{%core_paylog}}',['plid'=>'102','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070956101484','tid'=>NULL,'fee'=>'10.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289752','update_time'=>'1594289752']);
        $this->insert('{{%core_paylog}}',['plid'=>'103','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070910010251','tid'=>NULL,'fee'=>'45.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289838','update_time'=>'1594289838']);
        $this->insert('{{%core_paylog}}',['plid'=>'104','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070998565250','tid'=>NULL,'fee'=>'45.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594289851','update_time'=>'1594289851']);
        $this->insert('{{%core_paylog}}',['plid'=>'105','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070955101985','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594291975','update_time'=>'1594291975']);
        $this->insert('{{%core_paylog}}',['plid'=>'106','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070998539850','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594297291','update_time'=>'1594297291']);
        $this->insert('{{%core_paylog}}',['plid'=>'107','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070998975599','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594300363','update_time'=>'1594300363']);
        $this->insert('{{%core_paylog}}',['plid'=>'108','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070950499710','tid'=>NULL,'fee'=>'10.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594300434','update_time'=>'1594300434']);
        $this->insert('{{%core_paylog}}',['plid'=>'109','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070948101571','tid'=>NULL,'fee'=>'10.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594301040','update_time'=>'1594301040']);
        $this->insert('{{%core_paylog}}',['plid'=>'110','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070951100995','tid'=>NULL,'fee'=>'10.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594301139','update_time'=>'1594301139']);
        $this->insert('{{%core_paylog}}',['plid'=>'111','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070957989955','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594301993','update_time'=>'1594301993']);
        $this->insert('{{%core_paylog}}',['plid'=>'112','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070952102524','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594302213','update_time'=>'1594302213']);
        $this->insert('{{%core_paylog}}',['plid'=>'113','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070956994954','tid'=>NULL,'fee'=>'459.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594302408','update_time'=>'1594302408']);
        $this->insert('{{%core_paylog}}',['plid'=>'114','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070910252509','tid'=>NULL,'fee'=>'30.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594302911','update_time'=>'1594302911']);
        $this->insert('{{%core_paylog}}',['plid'=>'115','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070998971005','tid'=>NULL,'fee'=>'355.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594303227','update_time'=>'1594303227']);
        $this->insert('{{%core_paylog}}',['plid'=>'116','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020070910110152','tid'=>NULL,'fee'=>'10.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594303646','update_time'=>'1594303646']);
        $this->insert('{{%core_paylog}}',['plid'=>'117','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210151571','tid'=>NULL,'fee'=>'100.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594528782','update_time'=>'1594528782']);
        $this->insert('{{%core_paylog}}',['plid'=>'118','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071298991005','tid'=>NULL,'fee'=>'100.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594528875','update_time'=>'1594528875']);
        $this->insert('{{%core_paylog}}',['plid'=>'119','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071249575055','tid'=>'4200000580202007127237233976','fee'=>'0.01','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594528913','update_time'=>'1594528913']);
        $this->insert('{{%core_paylog}}',['plid'=>'120','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071257494998','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594530041','update_time'=>'1594530041']);
        $this->insert('{{%core_paylog}}',['plid'=>'121','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071252979752','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594533636','update_time'=>'1594533636']);
        $this->insert('{{%core_paylog}}',['plid'=>'122','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071297100100','tid'=>NULL,'fee'=>'499.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594533898','update_time'=>'1594533898']);
        $this->insert('{{%core_paylog}}',['plid'=>'123','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071252495399','tid'=>NULL,'fee'=>'499.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594533956','update_time'=>'1594533956']);
        $this->insert('{{%core_paylog}}',['plid'=>'133','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071253505650','tid'=>NULL,'fee'=>'499.00','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594534645','update_time'=>'1594534645']);
        $this->insert('{{%core_paylog}}',['plid'=>'134','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071253554853','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594534821','update_time'=>'1594534821']);
        $this->insert('{{%core_paylog}}',['plid'=>'135','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071251985455','tid'=>'4200000581202007129274281040','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594535667','update_time'=>'1594535667']);
        $this->insert('{{%core_paylog}}',['plid'=>'136','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071250501019','tid'=>'4200000593202007120278308858','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594535826','update_time'=>'1594535826']);
        $this->insert('{{%core_paylog}}',['plid'=>'137','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210210050','tid'=>NULL,'fee'=>'12.00','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594539807','update_time'=>'1594539807']);
        $this->insert('{{%core_paylog}}',['plid'=>'138','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071257565153','tid'=>'4200000575202007129308838624','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594545721','update_time'=>'1594545721']);
        $this->insert('{{%core_paylog}}',['plid'=>'139','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071297531011','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594546234','update_time'=>'1594546234']);
        $this->insert('{{%core_paylog}}',['plid'=>'140','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071251100579','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594546323','update_time'=>'1594546323']);
        $this->insert('{{%core_paylog}}',['plid'=>'141','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071298555650','tid'=>NULL,'fee'=>'0.01','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594546347','update_time'=>'1594546347']);
        $this->insert('{{%core_paylog}}',['plid'=>'142','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210252535','tid'=>'4200000590202007122887871986','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594546399','update_time'=>'1594546399']);
        $this->insert('{{%core_paylog}}',['plid'=>'143','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071250995697','tid'=>'4200000574202007126193755940','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594546914','update_time'=>'1594546914']);
        $this->insert('{{%core_paylog}}',['plid'=>'144','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210099575','tid'=>'4200000584202007120431648036','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594547021','update_time'=>'1594547021']);
        $this->insert('{{%core_paylog}}',['plid'=>'145','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210210052','tid'=>'4200000586202007127223074139','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594547151','update_time'=>'1594547151']);
        $this->insert('{{%core_paylog}}',['plid'=>'146','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071253481015','tid'=>'4200000575202007128141662610','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594547301','update_time'=>'1594547301']);
        $this->insert('{{%core_paylog}}',['plid'=>'147','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071254979956','tid'=>'4200000585202007123881968080','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594547414','update_time'=>'1594547414']);
        $this->insert('{{%core_paylog}}',['plid'=>'148','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071257991024','tid'=>'4200000574202007123799750608','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594548761','update_time'=>'1594548761']);
        $this->insert('{{%core_paylog}}',['plid'=>'149','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071257975657','tid'=>'4200000577202007125612303582','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594549065','update_time'=>'1594549065']);
        $this->insert('{{%core_paylog}}',['plid'=>'150','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071210255561','tid'=>'4200000593202007126127218035','fee'=>'0.01','status'=>'1','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594549215','update_time'=>'1594549215']);
        $this->insert('{{%core_paylog}}',['plid'=>'151','bloc_id'=>'4','store_id'=>'43','type'=>'wechat','openid'=>'oO3nO4g0FJrWQ23lrIx_6gydcnmw','uniontid'=>'2020071310297539','tid'=>NULL,'fee'=>'12.00','status'=>'0','module'=>'diandi_distribution','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL,'create_time'=>'1594600703','update_time'=>'1594600703']);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%core_paylog}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

