<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box green ">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i> <?php if($info['id']){?>编辑<?php }else{?>新增<?php }?>配置
				</div>
				
			</div>
			<div class="portlet-body form">
				<form role="form" action="<?php echo $_SERVER['REQUEST_URI']?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
                <input type="hidden" name="id" value="<?php echo $info['id'] ?: ""?>">
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">配置标识</label>
							<div class="col-md-9">
								<input type="text" name="name" value="<?php echo $info['name'] ?: ""?>" placeholder="" class="form-control">
                                <span class="help-block">
    							    （用于C函数调用，只能使用英文且不能重复） 
                                </span>
							</div>                            
						</div>	
                        <div class="form-group">
							<label class="col-md-3 control-label">配置标题</label>
							<div class="col-md-9">
								<input type="text" name="title" value="<?php echo $info['title'] ?: ""?>" placeholder="" class="form-control">
                                <span class="help-block">
    							    （用于后台显示的配置标题）
                                </span>
							</div>                            
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">排序</label>
							<div class="col-md-9">
								<input type="text" name="sort" value="<?php echo $info['sort'] ?: 0?>" placeholder="" class="form-control">
                                <span class="help-block">
    							    （用于分组显示的顺序）
                                </span>
							</div>                            
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">配置类型</label>
							<div class="col-md-9">
								<select class="form-control" name="type">
                                    <?php foreach($this->config->CONFIG_TYPE_LIST->toArray() as $key=>$type){?>
                                        <option value="<?php echo $key?>" <?php if($key==$info['type']){?>selected="selected"<?php }?> ><?php echo $type?></option>
                                    <?php }?>
								</select>
                                <span class="help-block">
    							    （系统会根据不同类型解析配置值）
                                </span>
							</div>                            
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">配置分组</label>
							<div class="col-md-9">
								<select class="form-control" name="group">
                                    <option value="0">不分组</option>
                                    <?php foreach($this->config->CONFIG_GROUP_LIST->toArray() as $key=>$group){?>
                						<option value="<?php echo $key?>" <?php if($key==$info['group']){?>selected="selected"<?php }?> ><?php echo $group?></option>
                					<?php }?>
								</select>
                                <span class="help-block">
    							    （配置分组 用于批量设置）
                                </span>
							</div>                            
						</div>						
						<div class="form-group">
							<label class="col-md-3 control-label">配置值</label>
							<div class="col-md-9">
								<textarea rows="3" name="value" class="form-control"><?php echo $info['value'] ?: ""?></textarea>
                                <span class="help-block">
    							    （配置值）
                                </span>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label">配置项</label>
							<div class="col-md-9">
								<textarea rows="3" name="extra" class="form-control"><?php echo $info['extra'] ?: ""?></textarea>
                                <span class="help-block">
    							    （如果是枚举型 需要配置该项）
                                </span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-md-3 control-label">说明</label>
							<div class="col-md-9">
								<input type="text" name="remark" value="<?php echo $info['remark'] ?: ""?>" placeholder="" class="form-control">
                                <span class="help-block">
    							    （配置详细说明）
                                </span>
							</div>
						</div>
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>