<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">
            <ul class="nav nav-tabs">
                <?php foreach($this->config->CONFIG_GROUP_LIST->toArray() as $key=>$group){?>
    				<li <?php if($key==$id){?>class="active"<?php }?> >
    					<a href="<?php echo $this->url->get(CONTROLLER_NAME."/".ACTION_NAME."/id/".$key)?>">
    					   <?php echo $group?>配置 
                        </a>
    				</li>
                <?php }?>
			</ul>
            <div class="tab-content">
            </div>
        </div>
    </div>    
</div>
<div class="row">	
	<div class="col-md-6 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box  ">
			<div class="portlet-body form">
				<form role="form" action="<?php echo $this->url->get(CONTROLLER_NAME."/save")?>" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
					<div class="form-body">
                        <?php foreach($list as $config){?>
                            <div class="form-group">
    							<label class="col-md-3 control-label"><?php echo $config['title']?></label>
    							<div class="col-md-9">
                                        <?php if($config['type'] == "0"){?>
                                            <input type="text" name="config[<?php echo $config['name']?>]" value="<?php echo $config['value']?>" placeholder="" class="form-control">
                                        <?php }elseif($config['type']=="1"){?>                                       
                                            <input type="text" name="config[<?php echo $config['name']?>]" value="<?php echo $config['value']?>" placeholder="" class="form-control">
                                        <?php }elseif($config['type']=="2"){?>                                      
                                            <textarea rows="3" name="config[<?php echo $config['name']?>]" class="form-control"><?php echo $config['value']?></textarea>
                                        <?php }elseif($config['type']=="3"){?>                                      
                                            <textarea rows="3" name="config[<?php echo $config['name']?>]" class="form-control"><?php echo $config['value']?></textarea>
                                        <?php }elseif($config['type']=="4"){?>                                     
                                            <select class="form-control" name="config[<?php echo $config['name']?>]">
                                                <?php foreach(parse_config_attr($config['extra']) as $key=>$vo){?>
                                					<option value="<?php echo $key?>" <?php if($config['value']==$key){?>selected<?php }?> ><?php echo $vo?></option>
                                				<?php }?>
            								</select>
                                        <?php }elseif($config['type']=="5"){?>
                                            <?php $this->partial("_common/fileupload_single",array("inputname"=>"config[{$config['name']}]","inputvalue"=>$config['value'],"no_selector"=>1,"imgurl"=>getPhotoPathUrl($config['value'])."80x80")) ?>
                                        <?php }?>
                                    <?php if($config['remark']){?>
                                    <span class="help-block">
        							    （<?php echo $config['remark']?>）
                                    </span>
                                    <?php }?>
    							</div>                            
    						</div>
                        <?php }?>
							
                        
					</div>
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button class="btn green" type="submit">确 定</button>
								<button class="btn default" type="button" onclick="javascript:history.back(-1);return false;">返 回</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>