<div class="color-panel hidden-sm">
  <div class="color-mode-icons icon-color"></div>
  <div class="color-mode-icons icon-color-close"></div>
  <div class="color-mode">
    <p>THEME COLOR</p>
    <ul class="inline">
      <li class="color-red current color-default" data-style="red"></li>
      <li class="color-blue" data-style="blue"></li>
      <li class="color-green" data-style="green"></li>
      <li class="color-orange" data-style="orange"></li>
      <li class="color-gray" data-style="gray"></li>
      <li class="color-turquoise" data-style="turquoise"></li>
    </ul>
  </div>
</div>