<div class="header">

  <div class="container">
    <a class="site-logo" href="index.html"><img src="<?php echo STATIC_URL?>/img/common/logo.png" height="32" alt="Metronic FrontEnd"></a>

    <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

    <!-- BEGIN NAVIGATION -->
    <div class="header-navigation pull-left font-transform-inherit">
      <ul>
        <li class="dropdown active">
          <a class="dropdown-toggle" data-toggle="dropdown" data-target="/" href="javascript:;">
            首页
          </a>
          
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" data-target="/" href="javascript:;">
            定制旅行
          </a>
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" data-target="/" href="javascript:;">
            度假产品
          </a>
          <ul class="dropdown-menu">
            <li class="active"><a href="index.html">出境游</a></li>
            <li><a href="index-header-fix.html">国内短假</a></li>
            <li><a href="index-without-topbar.html">当地游</a></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" data-target="/" href="javascript:;">
            限时抢购
          </a>
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" data-target="/" href="javascript:;">
            游心故事
          </a>
        </li>

        
        
        
        

        <!-- BEGIN TOP SEARCH -->
        <li class="menu-search">
          <span class="sep"></span>
          <i class="fa fa-search search-btn"></i>
          <div class="search-box">
            <form action="#">
              <div class="input-group">
                <input type="text" placeholder="你想去的目的地" class="form-control">
                <span class="input-group-btn">
                  <button class="btn btn-primary" type="submit">立刻就走</button>
                </span>
              </div>
            </form>
          </div> 
        </li>
        <!-- END TOP SEARCH -->
      </ul>
    </div>
    <!-- END NAVIGATION -->
  </div>
</div>