<div class="pre-footer">
    <div class="container">
        <div class="row">
          <!-- BEGIN BOTTOM ABOUT BLOCK -->
          <div class="col-md-4 col-sm-6 pre-footer-col">
            <h2>关于游心</h2>
            <p>游心旅行成立于2014年，是一家旅行体验至上的定制旅行平台，为实际出行配以细致的贴心服务，用完美体验重新定义你的每一次旅行。基于对用户需求的深刻洞察，对旅行意义的独到见解，以专业买手姿态搜罗全球景致，精选出涵盖自由行、定制旅行、半定制旅行及碎片化的一系列高性价比旅行产品，全方位满足个性化需求，让旅行自在，记忆游心。</p>
          </div>
          <!-- END BOTTOM ABOUT BLOCK -->
        
          <!-- BEGIN BOTTOM CONTACTS -->
          <div class="col-md-4 col-sm-6 pre-footer-col">
            <h2>联系我们</h2>
            <address class="margin-bottom-40">
              北京市朝阳区静安东里12号院<br>
              国门大厦C座205室<br>
              客服电话: 4000-798-790（工作日 09:00-18:00）<br>
              酒店/旅行预定咨询: <a href="mailto:booking@uthing.cn">booking@uthing.cn</a><br>
              市场推广: <a href="mailto:marketing@uthing.cn">marketing@uthing.cn</a><br>
              战略合作: <a href="mailto:BD@uthing.cn">BD@uthing.cn</a><br>
              工作机会: <a href="mailto:Hr@uthing.cn">Hr@uthing.cn</a>
            </address>
          </div>
          
          <div class="col-md-4 col-sm-6 pre-footer-col photo-stream">
              <h2>旅行管家</h2>
              <ul class="list-unstyled">
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img5-small.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img4-large.jpg"></a></li>
                <li><a href="javascript:;"><img alt="" src="<?php echo STATIC_URL?>/theme/assets/frontend/pages/img/people/img2-large.jpg"></a></li>
              </ul>                    
          </div>
          
          
          <!-- END BOTTOM CONTACTS -->
        
          <!-- BEGIN TWITTER BLOCK --> 
          
          <!-- END TWITTER BLOCK -->
        </div>
    </div>
</div>