#!/usr/bin/env php
<?php
date_default_timezone_set('PRC'); //默认时区
ini_set('memory_limit', -1); //不限制内存使用
//ini_set("memory_limit", "1G");
ini_set('default_socket_timeout', -1);//socket没有时间限制
ini_set('set_time_limit', 0);//php执行时间没有限制

require __DIR__ . "/cli/bootstrap_cli.php";
