<?php $topic_ls = dt_query("SELECT id, title, icon_url,  user_name, reply_c, view_c, digest, today, l_r_at, c_at, today_up_c, pay, l_r_user_name FROM forum_topic WHERE forum_id = ".$topic['forum_id']." AND l_r_at > ".(time()-2*24*3600)." ORDER BY rand() LIMIT 5") ?>	
<div class="container">
	<div class="col-md-12 column forum-topic-list">
		<?php while($topic_l = mysql_fetch_array($topic_ls)) { ?>
		<?php require('forum/topic_list_item.phtml') ?>
		<?php } ?>
	</div>
</div>
