<?php

return array(
    'type'=>array(
        'title'=>'开启同步登录：',
        'type'=>'checkbox',
        'options'=>array(
            'Qq'=>'Qq',
            'Weibo'=>'Weibo',
            'Douban'=>'Douban',
            'Baidu'=>'Baidu',
            'Taobao'=>'Taobao',
        ),
    ),

    'group'=>array(
        'type'=>'group',
        'options'=>array(
            'Qq'=>array(
                'title'=>'腾讯QQ',
                'options'=>array(
                    'QqKEY'=>array(
                        'title'=>'QQ互联KEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    ),
                    'QqSecret'=>array(
                        'title'=>'QQ互联密匙：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://connect.qq.com',
                    ),
                    'Qqdescription' => array(
                        'title'=>'描述：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'',
                    )
                ),
             ),
            'Weibo'=>array(
                'title'=>'新浪微博',
                'options'=>array(

                    'WeiboKEY'=>array(
                        'title'=>'新浪KEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    ),
                    'WeiboSecret'=>array(
                        'title'=>'新浪密匙：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.weibo.com/',
                    ),
                    'Weibodescription' => array(
                        'title'=>'描述：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'',
                    )
                ),
            ),
            'Douban'=>array(
                'title'=>'豆瓣登录',
                'options'=>array(
                    'DoubanKEY'=>array(
                        'title'=>'豆瓣KEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://www.douban.com/',
                    ),
                    'DoubanSecret'=>array(
                        'title'=>'豆瓣密匙：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://www.douban.com/',
                    ),
                    'Doubandescription' => array(
                        'title'=>'描述：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'',
                    )
                ),
            ),
            'Baidu'=>array(
                'title'=>'百度登录',
                'options'=>array(
                    'BaiduKEY'=>array(
                        'title'=>'百度KEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://alading.baidu.com/',
                    ),
                    'BaiduSecret'=>array(
                        'title'=>'百度密匙：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://alading.baidu.com/',
                    ),
                    'Baidudescription' => array(
                        'title'=>'描述：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'',
                    )
                ),
            ),
            'Taobao'=>array(
                'title'=>'淘宝登录',
                'options'=>array(
                    'TaobaoKEY'=>array(
                        'title'=>'淘宝KEY：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.taobao.com/',
                    ),
                    'TaobaoSecret'=>array(
                        'title'=>'淘宝密匙：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'申请地址：http://open.taobao.com/',
                    ),
                    'Taobaodescription' => array(
                        'title'=>'描述：',
                        'type'=>'text',
                        'value'=>'',
                        'tip'=>'',
                    )
                ),
            ),
        )
    )
);