<div class="<?php echo $inputname?>"></div>
<script>
jQuery(document).ready(function() {
    
    
    if(typeof WPF.summernote === "undefined"){
        WPF.summernote = function(classname,value,height){
            $('.'+classname).summernote({
                height: height,
                lang:"zh-CN",
                onImageUpload:function(files, editor, $editable){
                    data = new FormData();
                    data.append("file", files[0]); 
                    $.ajax({
                        data: data,  
                        type: "POST",  
                        url: "<?php echo $this->url->get("Ajax/fileupload")?>", //图片上传出来的url，返回的是图片上传后的路径，http格式  
                        contentType: false,  
                        cache: false,  
                        processData: false,  
                        success: function(data) {
                            if(data.status){
                                editor.insertImage($editable,data.info.url);
                            }else{
                                alert(data.info)
                            }
                        }
                    });
                    
                         
                    
                }
            });
            $('.'+classname).code(value);
        }
    }
    
    if (!$().summernote) {
        $("head").append("<link href='<?php echo STATIC_URL?>/theme/assets/global/plugins/bootstrap-summernote/summernote.css' rel='stylesheet' type='text/css'/>")
    
        $.getScript("<?php echo STATIC_URL?>/theme/assets/global/plugins/bootstrap-summernote/summernote.min.js", function(){
            $.getScript("<?php echo STATIC_URL?>/theme/assets/global/plugins/bootstrap-summernote/lang/summernote-zh-CN.js", function(){
                WPF.summernote("<?php echo $inputname?>","<?php echo $inputvalue?>","<?php echo $inputrows?>");
            });
        });
    }else{
        WPF.summernote("<?php echo $inputname?>","<?php echo $inputvalue?>","<?php echo $inputrows?>");
    }
    
    
    
    
    
})
</script>