<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>游心网</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="<?php echo STATIC_URL?>/img/common/favicon.ico">
  
  
<script>
if(typeof WPF !== "object"){
    WPF = {};
}
WPF.files_hosts = "<?php echo STATIC_URL?>";
</script>
<?php $this->assets->outputCss("headercssurl") ?>
<?php $this->assets->outputCss("headercss") ?>
<?php $this->assets->outputCss("headercss__") ?>
<?php $this->assets->outputJs("headerjsurl") ?>
<?php $this->assets->outputJs("headerjs") ?>

  
  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">
    <!-- BEGIN STYLE CUSTOMIZER -->
    <?php //$this->partial("_layout/color_panel") ?>
    <!-- END BEGIN STYLE CUSTOMIZER --> 

    <!-- BEGIN TOP BAR -->
    <?php $this->partial("_layout/pre_header") ?>
    <!-- END TOP BAR -->
    <!-- BEGIN HEADER -->
    <?php $this->partial("_layout/header") ?>
    <!-- Header END -->

    <!-- BEGIN SLIDER -->
    
    <!-- END SLIDER -->
    <?php echo $this->getContent() ?>
    

    <!-- BEGIN PRE-FOOTER -->
    <?php $this->partial("_layout/pre_footer") ?>
    <!-- END PRE-FOOTER -->

    <!-- BEGIN FOOTER -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <!-- BEGIN COPYRIGHT -->
          <div class="col-md-6 col-sm-6 padding-top-10">
            游心旅行 | 2013-2015 | 浙ICP备14013955号
          </div>
          <!-- END COPYRIGHT -->
          <!-- BEGIN PAYMENTS -->
          <!-- END PAYMENTS -->
        </div>
      </div>
    </div>
    <!-- END FOOTER -->

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="<?php echo STATIC_URL?>/theme/assets/global/plugins/respond.min.js"></script>
    <![endif]--> 
<?php $this->assets->outputCss("footercssurl") ?>
<?php $this->assets->outputCss("footercss") ?>
<?php $this->assets->outputJs("footerjsurl") ?>
<?php $this->assets->outputJs("footerjs") ?>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            Layout.init();    
            Layout.initOWL();
            RevosliderInit.initRevoSlider();
            //Layout.initTwitter();
            //Layout.initFixHeaderWithPreHeader(); /* Switch On Header Fixing (only if you have pre-header) */
            //Layout.initNavScrolling(); 
        });
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>