<div class="register">
	<div class="container">
		<div class="row clearfix">
			<div class="col-md-2 column">
			</div>
			<div class="col-md-8 column">
				<div class="user-panel">
					<h3><span class="glyphicon glyphicon-magnet"></span> 新用户注册 </h3>
					<hr>
					<form class="form-horizontal" action="?c=user&a=do_register" method="post">
						<fieldset>
							<!-- Text input-->
							<div class="form-group has-feedback" id="username">
								<label class="col-md-4 control-label">用户名</label>  
								<div class="col-md-5">
									<input id="username" name="username" type="text" placeholder="用户名" class="form-control input-md" required="" onblur="do_register_check('username')">
									<span class="glyphicon form-control-feedback"></span>
								</div>
								<p class="control-label info"></p>
							</div>
							<!-- Text input-->
							<div class="form-group has-feedback" id="email">
								<label class="col-md-4 control-label">邮箱</label>  
								<div class="col-md-5">
									<input id="email" name="email" type="text" placeholder="example@example.com" class="form-control input-md" required="" onblur="do_register_check('email')">
									<span class="glyphicon form-control-feedback"></span>
								</div>
								<p class="control-label info"></p>
							</div>
							<!-- Password input-->
							<div class="form-group has-feedback" id="password">
								<label class="col-md-4 control-label">密码</label>
								<div class="col-md-5">
									<input id="password" name="password" type="password" placeholder="密码" class="form-control input-md" required="" onblur="check_password()">
									<span class="glyphicon form-control-feedback"></span>
								</div>
							</div>
							<!-- Password input-->
							<div class="form-group has-feedback" id="r_password">
								<label class="col-md-4 control-label">确认密码</label>
								<div class="col-md-5">
									<input id="r_password" name="r_password" type="password" placeholder="确认密码" class="form-control input-md" required="" onblur="check_r_password()">
									<span class="glyphicon form-control-feedback"></span>
								</div>
								<p class="control-label info"></p>
							</div>
							<!-- Text input-->
							<div class="form-group">
								<label class="col-md-4 control-label">激活码</label>  
								<div class="col-md-3">
									<input id="email_code" name="email_code" type="text" placeholder="邮箱激活码" class="form-control input-md" required="">
								</div>
								<div class="col-md-2">
									<a class="btn btn-default btn-block" type="button" href="javascript:get_email_code()">获取激活码</a>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"></label>
								<div class="col-md-7">
									<div class="checkbox"><label><input name="agreement" type="checkbox" checked="checked"> 我同意并接受<?php echo SYS_NAME ?>平台 <a href="?c=index&a=agreement">注册协议</a> </label></div>
								</div>
							</div>
							<!-- token -->
							<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
							<!-- Button (Double) -->
							<div class="form-group">
								<label class="col-md-4 control-label hidden-xs"></label>
								<div class="col-md-2 col-xs-5">
									<button id="do_register" class="btn btn-primary btn-block disabled">确认注册</button>
								</div>
								<div class="col-md-3 col-xs-7">
									<a class="btn btn-success btn-block" type="button" href="?c=user&a=login">直接登录</a>
								</div>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
	$("#zhuce").addClass("active");
});

</script>
