<?php 

if (empty($_GET['r_p_token'])) die;

if ($_SESSION['r_p_token'] != $_GET['r_p_token']) die('令牌错误！^_^');

?>
<div class="register">
	<div class="container">
		<div class="row clearfix">
			<div class="col-md-2 column">
			</div>
			<div class="col-md-8 column">
				<div class="user-panel">
					<h3><span class="glyphicon glyphicon-repeat"></span> 重置密码 </h3>
					<hr>
					<form class="form-horizontal" action="?c=user&a=do_reset_password" method="post">
						<fieldset>
							<div class="form-group">
								<label class="col-md-4 control-label">用户名</label>  
								<div class="col-md-6">
									<input name="password_new" type="text" disabled="disabled" placeholder="新密码" class="form-control input-md" required="" value="<?php echo $_SESSION['r_p_username'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label">新密码</label>  
								<div class="col-md-6">
									<input name="password_new" type="password" placeholder="新密码" class="form-control input-md" required="">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label">确认新密码</label>  
								<div class="col-md-6">
									<input name="password_new_r" type="password" placeholder="确认新密码" class="form-control input-md" required="">
								</div>
							</div>
							<!-- r_p_token -->
							<input type="hidden" name="r_p_token" value="<?php echo $_SESSION['r_p_token'] ?>"/>
							<!-- token -->
							<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
							<!-- Button (Double) -->
							<div class="form-group">
								<label class="col-md-4 control-label hidden-xs"></label>
								<div class="col-md-2 col-xs-5">
									<button class="btn btn-primary btn-block">重置密码</button>
								</div>
								<div class="col-md-4 col-xs-7">
									<a class="btn btn-success btn-block" type="button" href="?c=user&a=login">直接登录</a>
								</div>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
		});

</script>
