<div class="register">
	<div class="container">
		<div class="row clearfix">
			<div class="col-md-2 column">
			</div>
			<div class="col-md-8 column">
				<div class="user-panel">
					<h3><span class="glyphicon glyphicon-transfer"></span> 获取密码重置链接 </h3>
					<hr>
					<form class="form-horizontal" action="?c=user&a=do_send_r_p_link" method="post">
						<fieldset>
							<!-- Text input-->
							<div class="form-group">
								<label class="col-md-4 control-label">用户名/邮箱</label>  
								<div class="col-md-6">
									<input name="username" type="text" placeholder="用户名/邮箱" class="form-control input-md" required="">
								</div>
							</div>
							<!-- securimage -->
							<div class="form-group">
								<label class="col-md-4 control-label">验证码</label>
								<div class="col-md-3">
									<input id="captcha_code" name="captcha_code" type="text" placeholder="验证码" class="form-control input-md" maxlength="6" required="">
								</div>
								<div class="col-md-4"></div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"></label>
								<div class="col-md-7">
									<p><img id="captcha" src="inc/securimage/securimage_show.php" alt="CAPTCHA Image" /></p>
									<a href="#" onclick="document.getElementById('captcha').src = 'inc/securimage/securimage_show.php?' + Math.random(); return false">看不清，换一张。</a>

								</div>
							</div>
							<!-- token -->
							<!-- token -->
							<input type="hidden" name="token" value="<?php echo get_token() ?>"/>
							<!-- Button (Double) -->
							<div class="form-group">
								<label class="col-md-4 control-label hidden-xs"></label>
								<div class="col-md-2 col-xs-5">
									<button class="btn btn-primary btn-block">发送链接</button>
								</div>
								<div class="col-md-4 col-xs-7">
									<a class="btn btn-success btn-block" type="button" href="?c=user&a=login">直接登录</a>
								</div>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

$(document).ready(function(){
		});

</script>
