<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>


<div class="panel panel-info">
    <div class="panel-heading">
    	<h3 class="panel-title"><?= _('发布内容至Github') ?></h3>
    </div>
	<div class="panel-body">
		
        <?php if(!empty($result['finished'])) : ?>
        <p><?= _('发布完成') ?></p>
        <?php else : ?>
        <p><?= _('正在发布...') ?></p>
        <p><?= date('Y-m-d H:i:s'); ?></p>
        <p><a node-type="auto-go" data-timeout="1000" href="?_rand=<?= uniqid() ?> ?>"><?= _('如果浏览器没有自动跳转，请点击这里继续') ?></a></p>
        <?php endif; ?>
		
	</div>

	
</div>


<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/publish.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage', ['nav'=>'publish']) ?>