<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>
<form id="form-manage-publish" method="post" action="<?= $this->path('aj/manage/publish/create') ?>" onsubmit="return false">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><?= _('发布内容至Github') ?></h3>
  </div>
	<div class="panel-body">
		
		<div class="checkbox">
			<label> <input type="checkbox" name="publish[]" value="1-0" /> <?= _('首页') ?>
			</label>
		</div>
		
		<div node-type="publish-category">
    		<div class="checkbox">
    			<label> <input type="checkbox" id="publish-all" name="publish-all" value=""> <?= _('分类文章列表') ?></label>
    		</div>
    		<ul>
    			<?php foreach($categorys as $value) : ?>
    			<li class="checkbox"><label><input type="checkbox" name="publish[]" value="2-<?= $value['id'] ?>"> <?= $value['name'] ?></label></li>
    			<?php endforeach; ?>
    		</ul>
		</div>
		
		<div class="checkbox">
			<label><input type="checkbox" name="publish[]" value="3-0" /> <?= _('侧边栏') ?></label>
		</div>
		
	</div>
	
	<div class="panel-footer">
		<input type="submit" class="btn btn-default" value="<?= ('发布') ?>" />
	</div>
	
	
</div>
</form>

<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/publish.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage', ['nav'=>'publish']) ?>