<?php
use \blog\model\Article;
use \blog\model\Meta;
use \blog\libs\Html;
use \blog\libs\Common;
?>
<!DOCTYPE html>
<html>
<head>
	<?=Html::meta(['name|viewport' => 'width=device-width, initial-scale=1'])?>
	<title><?=Html::encode($title)?> - <?=Common::option('sitename')?></title>
	<?php $this->display('common/header'); ?>
	<?=Html::link()?>
</head>
<body>
	<?php $this->display('common/navbar') ?>
	<div class="row">
		<div class="col s9">
		<?php
		while ($a = $list->next()) {
			echo '<article class="card-panel"><h4><a href="';
			echo $a->url();
			echo '">';
			$a->title();
			echo '</a></h4><p class="info">';
			$a->date('Y年m月d日 H:i:s');
			echo '</p><p>';
			$a->excerpt(100,'...');
			echo '</p></article>';
		}
		?>
		<ul class="pagination center-align">
		<?php
		$list->pageNav('li', 'waves-effect', 'active', '<i class="mdi-arrow-back"></i>', '<i class="mdi-arrow-forward"></i>');
		?>
		</ul>
		</div>
		<?php $this->display('common/sidebar'); ?>
	</div>
	<?php $this->display('common/footer') ?>
</body>
</html>