<?php
use \blog\model\Article;
use \blog\model\Meta;
use \blog\libs\Html;
use \blog\libs\Common;
?>
<!DOCTYPE html>
<html>
<head>
	<?=Html::meta(['name|viewport' => 'width=device-width, initial-scale=1'])?>
	<title><?php $article->title(); ?> - <?=Common::option('sitename')?></title>
	<?php $this->display('common/header'); ?>
	<?=Html::link()?>
</head>
<body>
	<?php $this->display('common/navbar') ?>
	<div class="row">
		<div class="col s9">
			<article class="card-panel">
				<h2><?php $article->title(); ?></h2>
				<p class="info">Published at <?php $article->date('Y-m-d H:i:s'); ?></p>
				<p class="info">Tags:<?=Meta::tags($article->tags)?></p>
				<article class="article"><?php $article->body(['imgClass' => 'materialboxed', 'addNofollow' => TRUE]); ?></article>
			</article>
		</div>
		<?php $this->display('common/sidebar'); ?>
	</div>
	<?php $this->display('common/footer') ?>
</body>
</html>