<?php
use \sy\base\Router;
?>
<!DOCTYPE html>
<html>
<head>
	<title>标签 - SYBlog</title>
	<?php $this->display('common/header'); ?>
</head>
<body>
	<?php $this->display('common/navbar'); ?>
	<div class="page-content">
		<h2 class="title">标签</h2>
		<table class="striped">
			<thead><tr><th>标题</th><th>文章数</th><th class="action">操作</th></tr></thead>
			<tbody id="list"></tbody>
		</table>
		<ul id="page" class="pagination"></ul>
	</div>
	<div id="meta_form" class="modal">
		<div class="modal-content">
			<h4>编辑</h4>
			<input type="hidden" id="mid"/>
			<div class="row">
				<div class="input-field col s12">
					<input id="title" type="text" placeholder="标题"/>
					<label class="active" for="title">标题</label>
				</div>
				<div class="col s12">
					<label>类型</label>
					<select id="type" class="browser-default">
						<option value="1">分类</option>
						<option value="2">普通标签</option>
					</select>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<a id="meta_submit" class="modal-action modal-close waves-effect btn-flat">保存</a>
			<a class="modal-action modal-close waves-effect btn-flat">取消</a>
		</div>
	</div>
	<script>
	window.sy = {
		"url": {
			"list": "<?=Router::createUrl('admin/meta/list', 'json')?>",
			"ajaxEdit": "<?=Router::createUrl('admin/meta/edit', 'json')?>"
		},
		"page": "Meta"
	};
	</script>
	<?php $this->display('common/footer'); ?>
</body>
</html>