<div class="content-wrapper">
    <section class="content-header">
        <?=$this->partial('layout/breadcrumb')?>

        <h1 class="pull-right">
            <a href="<?=$this->url('erp-stock');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?=$this->translate('返回其他入库单列表')?></a>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?=$this->translate('其他入库单')?></h3>
                    </div>

                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('入库单号')?>：</b><?=$this->escapeHtml($this->otherWarehouseOrder->getWarehouseOrderSn());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('仓库')?>：</b><?=$this->escapeHtml($this->otherWarehouseOrder->getOneWarehouse()->getWarehouseName());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('状态')?>：</b><?=$this->translate('已入库')?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('入库时间')?>：</b><?=date("Y-m-d H:i:s", $this->otherWarehouseOrder->getOtherAddTime());?>
                                </div>
                            </div>
                            <div class="col-xs-8 form-group">
                                <div class="col-sm-12">
                                    <b><?=$this->translate('入库备注')?>：</b><?=$this->escapeHtml($this->otherWarehouseOrder->getWarehouseOrderInfo());?>
                                </div>
                            </div>
                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?=$this->translate('入库商品')?></h4>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="15%"><?=$this->translate('商品编号')?></th>
                                    <th width="20%"><?=$this->translate('商品名称')?></th>
                                    <th><?=$this->translate('商品规格')?></th>
                                    <th><?=$this->translate('单位')?></th>
                                    <th><?=$this->translate('采购单价')?></th>
                                    <th><?=$this->translate('采购数量')?></th>
                                    <th width="10%"><?=$this->translate('采购总价')?></th>
                                </tr>
                                </thead>
                                    <?php foreach ($this->orderGoods as $goodsValue) { ?>
                                        <tr>
                                            <td><?=$this->escapeHtml($goodsValue->getGoodsNumber())?></td>
                                            <td><?=$this->escapeHtml($goodsValue->getGoodsName())?></td>
                                            <td><?=$this->escapeHtml($goodsValue->getGoodsSpec())?></td>
                                            <td><?=$this->escapeHtml($goodsValue->getGoodsUnit())?></td>
                                            <td><?=$this->erpCurrencyFormat($goodsValue->getWarehouseGoodsPrice())?></td>
                                            <td><?=$goodsValue->getWarehouseGoodsBuyNum()?></td>
                                            <td><?=$this->erpCurrencyFormat($goodsValue->getWarehouseGoodsAmount())?></td>
                                        </tr>
                                <?php } ?>

                                <tfoot>
                                <tr>
                                    <td colspan="5"></td>
                                    <td colspan="2" class="text-right"><b><?=$this->translate('金额合计')?>：</b><span id="order-amount"><?=(isset($this->otherWarehouseOrder) ? $this->erpCurrencyFormat($this->otherWarehouseOrder->getWarehouseOrderAmount()) : 0)?></span></td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>

                </div>


            </div>
        </div>

    </section>

</div>