<?php

namespace Bluehouseapp\Bundle\CoreBundle\Entity;

use Bluehouseapp\Bundle\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{

    public function  getNode($nodeId){
      //  return parent::findOneBy(array('id'=>$nodeId,'status'=>true,'enabled'=>true));

        $node = parent::getQueryBuilder()
            ->innerJoin('n.category', 'c')
            ->where('n.id = :id')
            ->andWhere('n.status = :status')
            ->andWhere('n.enabled = :enabled')
            ->andWhere('c.status = :status')
            ->andWhere('c.enabled = :enabled')
            ->setParameters(array(':id'=>$nodeId,'status'=>true,'enabled'=>true))
           // ->setMaxResults(1)
           // ->setFirstResult(0)
            ->getQuery()
            ->getOneOrNullResult();

        return $node;

    }
    protected function getAlias()
    {
        return 'n';
    }
}
